import { expect, test } from '@playwright/test'

test.describe('URAI Spatial home release shell', () => {
  test('shows home spatial shell, passive orb, and avatar target', async ({ page }) => {
    await page.goto('/')
    await expect(page.locator('[data-urai-home-spatial-shell="true"]')).toBeVisible()
    await expect(page.locator('[data-urai-camera-target="home-wide"]')).toBeVisible()
    await expect(page.locator('[data-urai-orb-listening="passive"]')).toBeVisible()
    await expect(page.locator('[data-urai-home-target="avatar"]')).toHaveText(/Avatar/)
  })

  test('opens orb chat and voice scaffold states', async ({ page }) => {
    await page.goto('/')
    await page.locator('[data-urai-home-target="orb"]').click()
    await expect(page.locator('[data-urai-camera-target="open-orb"]')).toBeVisible()
    await expect(page.locator('[data-urai-orb-chat="shell"]')).toBeVisible()
    await expect(page.locator('[data-urai-orb-voice="scaffold"]')).toBeVisible()
    await page.locator('[data-urai-orb-voice-action="listen"]').click()
    await expect(page.locator('[data-urai-orb-voice-state="listening"]')).toBeVisible()
    await page.locator('[data-urai-orb-voice-action="stop"]').click()
    await expect(page.locator('[data-urai-orb-voice-state="speaking"]')).toBeVisible()
    await page.locator('[data-urai-orb-voice-action="mute"]').click()
    await expect(page.locator('[data-urai-orb-voice-state="muted"]')).toBeVisible()
  })

  test('opens avatar body regions', async ({ page }) => {
    await page.goto('/')
    await page.locator('[data-urai-home-target="avatar"]').click()
    await expect(page.locator('[data-urai-avatar-state="zoomed-region-select"]')).toBeVisible()
    await page.locator('[data-urai-home-target="head"]').click()
    await expect(page.locator('[data-urai-body-biometric-panel="head"]')).toBeVisible()
    await expect(page.locator('[data-urai-body-metric="Focus Load"]')).toBeVisible()
    await page.keyboard.press('Escape')
    await page.locator('[data-urai-home-target="avatar"]').click()
    await page.locator('[data-urai-home-target="torso"]').click()
    await expect(page.locator('[data-urai-body-biometric-panel="torso"]')).toBeVisible()
    await expect(page.locator('[data-urai-body-metric="Heart Rate"]')).toBeVisible()
    await page.keyboard.press('Escape')
    await page.locator('[data-urai-home-target="avatar"]').click()
    await page.locator('[data-urai-home-target="arms"]').click()
    await expect(page.locator('[data-urai-body-biometric-panel="arms"]')).toBeVisible()
    await expect(page.locator('[data-urai-body-metric="Device Strain"]')).toBeVisible()
    await page.keyboard.press('Escape')
    await page.locator('[data-urai-home-target="avatar"]').click()
    await page.locator('[data-urai-home-target="legs"]').click()
    await expect(page.locator('[data-urai-body-biometric-panel="legs"]')).toBeVisible()
    await expect(page.locator('[data-urai-body-metric="Grounding"]')).toBeVisible()
  })

  test('opens sky and ground layers', async ({ page }) => {
    await page.goto('/')
    await page.locator('[data-urai-home-target="sky"]').click()
    await expect(page.locator('[data-urai-home-panel="sky-life-map"]')).toBeVisible()
    await expect(page.locator('[data-urai-sky-node="memory-thread"]')).toBeVisible()
    await expect(page.locator('[data-urai-sky-node="forecast-path"]')).toBeVisible()
    await page.keyboard.press('Escape')
    await page.locator('[data-urai-home-target="ground"]').click()
    await expect(page.locator('[data-urai-home-panel="ground-world"]')).toBeVisible()
    await expect(page.locator('[data-urai-ground-object="room-anchor"]')).toBeVisible()
    await expect(page.locator('[data-urai-ground-object="object-memory"]')).toBeVisible()
  })

  test('body biometric API returns fallback snapshots', async ({ request }) => {
    const torso = await request.post('/api/body-biometric', { data: { userId: 'adamclamp', portal: 'chest-heart', source: 'live-device' } })
    expect(torso.ok()).toBeTruthy()
    const torsoPayload = await torso.json()
    expect(torsoPayload.service).toBe('urai-spatial')
    expect(torsoPayload.providerStatus).toBe('fallback')
    expect(torsoPayload.snapshot.region).toBe('torso')

    const head = await request.post('/api/body-biometric', { data: { portal: 'brain-synapses', source: 'mock' } })
    expect(head.ok()).toBeTruthy()
    const headPayload = await head.json()
    expect(headPayload.isDemoFallback).toBe(true)
    expect(headPayload.snapshot.region).toBe('head')
  })

  test('orb routing can open head and home', async ({ page }) => {
    await page.goto('/')
    await page.locator('[data-urai-home-target="orb"]').click()
    await page.getByLabel('Message URAI').fill('show my brain')
    await page.getByLabel('Message URAI').press('Enter')
    await expect(page.locator('[data-urai-orb-route-action="brain-synapses"]')).toBeVisible()
    await page.locator('[data-urai-orb-route-action="brain-synapses"]').click()
    await expect(page.locator('[data-urai-home-panel="brain-synapses"]')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.locator('[data-urai-camera-target="home-wide"]')).toBeVisible()
  })
})
