import { expect, test } from '@playwright/test'

test('Home weather respects saved motion preference and live OS changes', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.addInitScript(() => {
    localStorage.setItem('urai:onboarding:v3:setup-complete', '1')
    localStorage.setItem('urai:onboarding:v2:complete', '1')
  })
  await page.goto('/settings', { waitUntil: 'domcontentloaded' })
  const setting = page.locator('section[aria-labelledby="motion-heading"] input[type="checkbox"]')
  await setting.check()
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('urai.spatial.settings.v1') || '{}').reducedMotion)).toBe(true)
  await page.goto('/?homeSample=1', { waitUntil: 'domcontentloaded' })
  const weather = page.getByTestId('home-personal-emotional-weather')
  await expect(weather).toHaveAttribute('data-home-emotional-weather-visible', 'true')
  await expect(weather).toHaveAttribute('data-home-emotional-weather-reduced-stimulation', 'true')
  await expect(weather).toHaveCSS('opacity', '0.018')
  await expect(weather).toHaveCSS('mix-blend-mode', 'normal')
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(weather).toHaveCSS('opacity', '0.018')
  await page.goto('/settings', { waitUntil: 'domcontentloaded' })
  await setting.uncheck()
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('urai.spatial.settings.v1') || '{}').reducedMotion)).toBe(false)
  await page.goto('/?homeSample=1', { waitUntil: 'domcontentloaded' })
  await expect(weather).toHaveAttribute('data-home-emotional-weather-reduced-stimulation', 'false')
  await expect(weather).toHaveCSS('mix-blend-mode', 'soft-light')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(weather).toHaveCSS('opacity', '0.018')
  await expect(weather).toHaveCSS('mix-blend-mode', 'normal')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await expect(weather).toHaveAttribute('data-home-emotional-weather-reduced-stimulation', 'false')
  await expect(weather).toHaveCSS('mix-blend-mode', 'soft-light')
})
