import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const geology = fs.readFileSync(new URL('../src/app/focus/focusMemoryGeology.ts', import.meta.url), 'utf8')

test('selected memory remains one connected living-memory phenomenon rather than discrete shards or cards', () => {
  assert.match(geology, /V272 established one connected living-memory phenomenon/)
  assert.match(geology, /const MEMORY_SECTIONS = 41/)
  assert.match(geology, /const MEMORY_CROSS_POINTS = 9/)
  assert.match(geology, /function createLivingMemoryFold\(/)
  assert.match(geology, /const furrow = Math\.exp\(-Math\.pow\(lateral \/ \.20, 2\)\)/)
  assert.match(geology, /- \.052 \* furrow/)
  assert.match(geology, /focusMemoryRole = 'v272-single-connected-living-memory-fold'/)
  assert.match(geology, /focusMemoryTopology = 'v294-open-continuous-ground-ribbon-with-longitudinal-furrow'/)
  assert.match(geology, /focusLiteralPixelRepair = 'v272-no-crystal-crown-no-card-stack'/)
  assert.match(geology, /focusSilhouetteRule = 'one-ground-owned-scar-no-closed-volume-no-split-pair'/)
  assert.match(geology, /return \[createLivingMemoryFold\(\)\]/)

  assert.doesNotMatch(geology, /const MEMORY_FACETS:/)
  assert.doesNotMatch(geology, /function createMemoryFacet\(/)
  assert.doesNotMatch(geology, /v271-interlocked-volumetric-memory-facet/)
  assert.doesNotMatch(geology, /createMemoryLamella/)
  assert.doesNotMatch(geology, /v269-living-luminous-memory-lamella/)
  assert.doesNotMatch(geology, /Array\.from\(\{ length: 7 \}/)
})

test('V294 is one open sanctuary scar ribbon with no closed-volume split-pair topology', () => {
  assert.match(geology, /V294 changes topology instead of continuing to tune a closed volume/)
  assert.match(geology, /const deep = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /const mineral = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /const weathered = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /const warm = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /focusMemoryEnergy = 'weathered-mineral-restrained-warm-cool-response'/)
  assert.match(geology, /function fractureCenter\(t: number\)/)
  assert.match(geology, /const centralScar = Math\.exp/)
  assert.match(geology, /const nearPressure = Math\.exp/)
  assert.match(geology, /const farPressure = Math\.exp/)
  assert.match(geology, /const brokenKnot = Math\.exp/)
  assert.match(geology, /const centerY = -1\.285/)
  assert.match(geology, /const leftLip = Math\.exp/)
  assert.match(geology, /const rightLip = Math\.exp/)
  assert.match(geology, /const lateralDistance = lateral \* halfWidth/)
  assert.match(geology, /indices\.push\(a, b, c, b, d, c\)/)
  assert.match(geology, /focusLiteralPixelSuccessorV294 = 'v294-continuous-open-sanctuary-scar-jagged-edges-dark-furrow-asymmetric-lips'/)
  assert.match(geology, /focusVisualAuthority = 'v294-sanctuary-memory-scar-ribbon'/)
  assert.match(geology, /focusCurrentVisualAuthority = 'v294-open-continuous-memory-rupture'/)
  assert.match(geology, /color\.r = Math\.min\(\.52, color\.r\)/)
  assert.match(geology, /color\.g = Math\.min\(\.42, color\.g\)/)
  assert.match(geology, /color\.b = Math\.min\(\.25, color\.b\)/)
  assert.doesNotMatch(geology, /MEMORY_RING_POINTS|MEMORY_RENDER_RING_POINTS|terminalBurial|undersideSink|startCap|endCap/)
  assert.doesNotMatch(geology, /setRGB\(\.125, \.405, \.485\)|setRGB\(\.72, \.86, \.82\)|setRGB\(\.92, \.38, \.12\)/)
})