import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const worldEvents = fs.readFileSync(new URL('../src/spatial/world/worldEvents.ts', import.meta.url), 'utf8')
const semanticNavigator = fs.readFileSync(new URL('../src/components/lifemap/LifeMapSemanticNavigator.tsx', import.meta.url), 'utf8')
const telemetryBridge = fs.readFileSync(new URL('../src/app/HomeParallaxTelemetryBridge.tsx', import.meta.url), 'utf8')
const focus = fs.readFileSync(new URL('../src/app/focus/FocusChamberClient.tsx', import.meta.url), 'utf8')
const geology = fs.readFileSync(new URL('../src/app/focus/focusMemoryGeology.ts', import.meta.url), 'utf8')

test('deep-travel fallback cannot preempt the canonical transition controller', () => {
  const fallback = worldEvents.match(/WORLD_TRAVEL_FALLBACK_MS\s*=\s*(\d+)/)
  assert.ok(fallback)
  assert.ok(Number(fallback[1]) > 1900)
})

test('overview mode clears semantic selection without discarding route identity', () => {
  assert.match(semanticNavigator, /const overviewRequested = params\.get\(['"]overview['"]\) === ['"]1['"]/)
  assert.match(semanticNavigator, /const selectedId = overviewRequested \? null : params\.get\(['"]node['"]\) \|\| params\.get\(['"]memoryId['"]\)/)
})

test('home telemetry synchronizes from mutations and input without perpetual document polling', () => {
  assert.match(telemetryBridge, /new MutationObserver\(scheduleSynchronization\)/)
  assert.doesNotMatch(telemetryBridge, /requestAnimationFrame\(synchronize\)/)
  assert.doesNotMatch(telemetryBridge, /const synchronize = \(\) =>/)
})

test('Focus focal authority is the selected memory star and cannot regress to V321 terrain cavities', () => {
  assert.match(focus, /Locked product authority; V387 is the current literal-pixel implementation/)
  assert.match(focus, /data-focus-composition="selected-memory-star-with-contained-memory"/)\n  assert.match(focus, /data-focus-visual-revision="v387-photosphere-owned-no-spherical-shell-contained-memory"/)\n  assert.match(focus, /data-focus-stellar-treatment="selected-corona-plasma-irregular-photosphere-stellar-field-v387"/)
  assert.match(focus, /data-focus-spatial="selected-memory-star"/)
  assert.match(focus, /data-focus-terrain-owner="false"/)
  assert.match(focus, /name="focus-selected-memory-star"/)
  assert.match(focus, /name="focus-memory-star-glass-shell"/)
  assert.match(focus, /<MemoryVisualContent memory=\{memory\} \/>/)
  assert.match(focus, /selected-memory-star-resolving-through-memory-v387/)
  assert.match(focus, /geometry=\{photosphereGeometry\} scale=\{\[\.26, \.23, \.21\]\}/)
  assert.match(focus, /opacity=\{memory \? 0\.04 : 0\.05\}/)
  assert.match(focus, /function makeFocusCoronaTexture\(power: number, rays = false\)/)
  assert.match(focus, /const warpedAngle = angle \+ Math\.sin\(angle \* 3\.0 \+ \.37\) \* \.16/)
  assert.match(focus, /broadPlume/)
  assert.match(focus, /finePlume/)
  assert.match(focus, /const boundary = THREE\.MathUtils\.clamp\(\.62/)
  assert.match(focus, /const rayBoundary = rays/)
  assert.match(focus, /const compactCorona = rays/)
  assert.match(focus, /const streamerTexture = rays/)
  assert.match(focus, /data-focus-layer-budget="four-stellar-layers-plus-memory"/)
  assert.match(focus, /name="focus-memory-star-corona-glow"/)
  assert.match(focus, /name="focus-memory-star-organic-streamer-field"/)
  assert.match(focus, /name="focus-memory-star-photosphere-surface"/)
  assert.match(focus, /name="focus-memory-star-photosphere-core"/)
  assert.doesNotMatch(focus, /focus-memory-star-corona-streamer-primary|focus-memory-star-corona-streamer-secondary|focus-memory-star-corona-streamer-diagonal-a|focus-memory-star-corona-streamer-diagonal-b|focus-memory-star-white-hot-limb/)
  assert.match(focus, /scale=\{\[1\.98, 1\.66, 1\]\}/)
  assert.match(focus, /opacity=\{memory \? \.26 : \.10\}/)
  assert.match(focus, /scale=\{\[2\.18, 1\.78, 1\]\}/)
  assert.match(focus, /opacity=\{memory \? \.14 : \.06\}/)
  assert.match(focus, /scale=\{\[2\.02, 1\.72, 1\]\}/)
  assert.match(focus, /opacity=\{memory \? \.94 : \.05\}/)
  assert.match(focus, /function makeFocusPhotosphereGeometry\(\)/)
  assert.match(focus, /new THREE\.SphereGeometry\(1, 128, 96\)/)
  assert.doesNotMatch(focus, /makeFocusCoronaShellGeometry|geometry=\{coronaShellA\}|geometry=\{coronaShellB\}/)
  assert.match(focus, /width:236px;height:236px/)
  assert.match(focus, /focusStarMemoryButton\{width:184px;height:184px\}/)
  assert.match(focus, /focusStarMemoryButton\{width:164px;height:164px\}/)
  assert.match(focus, /focusMemoryVisual\{[^}]*width:44%;height:30%/)
  assert.match(focus, /focusMemoryVisual\{[^}]*border-radius:31% 69% 43% 57%/)
  assert.match(focus, /focusMemoryVisual\{[^}]*mask-image:radial-gradient\(ellipse/)
  assert.match(focus, /focusMemoryVisual\{[^}]*clip-path:none/)
  assert.match(focus, /opacity:\.92;filter:saturate\(1\.08\) contrast\(1\.26\) brightness\(\.90\)/)
  assert.match(focus, /focusMemoryVisual::before/)
  assert.match(focus, /mix-blend-mode:screen;opacity:\.05;z-index:4/)
  assert.match(focus, /mix-blend-mode:screen;opacity:\.04;z-index:5/)
  assert.match(focus, /focusMemoryVisual::after/)
  assert.doesNotMatch(focus, /background:conic-gradient\(/)
  assert.doesNotMatch(focus, /repeating-conic-gradient\(/)
  assert.match(focus, /\.focusFallbackStar\{[^}]*width:min\(40vw,320px\)/)
  assert.match(focus, /\.focusFallbackStar\{[^}]*filter:drop-shadow/)
  assert.match(focus, /\.focusFallbackStar::before/)
  assert.match(focus, /\.focusFallbackStar::after/)
  assert.match(focus, /opacity=\{memory \? 0 : 0\.012\}/)
  assert.match(focus, /function makeFocusSphereTexture\(\)/)
  assert.match(focus, /<meshBasicMaterial[\s\S]*map=\{sphereTexture\}[\s\S]*blending=\{THREE\.AdditiveBlending\}[\s\S]*depthWrite=\{false\}/)
  assert.match(focus, /memory\.sourceMedia\.find/)
  assert.match(focus, /Generated demo visualization/)
  assert.doesNotMatch(focus, /createFocusStrata|createFocusGroundIncision|FocusSanctuaryGround|FocusStoneBank/)
  assert.doesNotMatch(focus, /focus-v321-focal-readable-three-radial-pressure-cavity-bottoms|focus-v251-grounded-living-memory-manifestation/)
  assert.match(geology, /v321-focal-readable-three-radial-terrain-cavities-localized-bottoms-ground-blended-hairline-connector-buried-closed-body/)
})

test('Focus convergence preserves Replay activation, selected-memory semantics, reduced motion, and star interaction safety', () => {
  assert.match(focus, /if \(!memory \|\| !replayHref \|\| committed\) return/)
  assert.match(focus, /'Enter Replay for ' \+ memory\.title/)
  assert.doesNotMatch(focus, /Open Replay for/)
  assert.match(focus, /reducedMotion/)
  assert.match(focus, /requestUraiWorldTravel\(\{/)
  assert.match(focus, /destination: 'replay'/)
  assert.match(focus, /requestUraiWorldReturn\(\)/)
  assert.match(focus, /terrainOwner: false/)
})
