import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const geology = fs.readFileSync(new URL('../src/app/focus/focusMemoryGeology.ts', import.meta.url), 'utf8')

test('selected memory remains one connected living-memory phenomenon rather than discrete shards or cards', () => {
  assert.match(geology, /V272 established one connected living-memory phenomenon/)
  assert.match(geology, /const MEMORY_SECTIONS = 21/)
  assert.match(geology, /const MEMORY_RING_POINTS = 12/)
  assert.match(geology, /function createLivingMemoryFold\(/)
  assert.match(geology, /const furrow = Math\.exp\(-Math\.pow\(furrowDistance \/ \.16, 2\)\) \* scarWindow/)
  assert.match(geology, /- \.092 \* furrow/)
  assert.match(geology, /focusMemoryRole = 'v272-single-connected-living-memory-fold'/)
  assert.match(geology, /focusMemoryTopology = 'v292-ground-intersecting-longitudinal-fracture-with-deep-furrow'/)
  assert.match(geology, /focusLiteralPixelRepair = 'v272-no-crystal-crown-no-card-stack'/)
  assert.match(geology, /focusSilhouetteRule = 'ground-held-fracture-not-portable-object'/)
  assert.match(geology, /return \[createLivingMemoryFold\(\)\]/)

  assert.doesNotMatch(geology, /const MEMORY_FACETS:/)
  assert.doesNotMatch(geology, /function createMemoryFacet\(/)
  assert.doesNotMatch(geology, /v271-interlocked-volumetric-memory-facet/)
  assert.doesNotMatch(geology, /createMemoryLamella/)
  assert.doesNotMatch(geology, /v269-living-luminous-memory-lamella/)
  assert.doesNotMatch(geology, /Array\.from\(\{ length: 7 \}/)
})

test('V292 is a shallow sanctuary fracture with buried ends, broken scar lips and restrained mineral energy', () => {
  assert.match(geology, /V292 removes the remaining object read/)
  assert.match(geology, /const deep = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /const mineral = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /const weathered = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /const warm = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /focusMemoryEnergy = 'weathered-mineral-restrained-warm-cool-response'/)
  assert.match(geology, /const terminalBurial = THREE\.MathUtils\.smoothstep\(Math\.abs\(t\), \.62, 1\)/)
  assert.match(geology, /const centralScar = Math\.exp/)
  assert.match(geology, /const nearRidge = Math\.exp/)
  assert.match(geology, /const farRidge = Math\.exp/)
  assert.match(geology, /const brokenKnot = Math\.exp/)
  assert.match(geology, /const centerX = 2\.55 \* t/)
  assert.match(geology, /const centerY = -1\.48/)
  assert.match(geology, /- \.34 \* terminalBurial/)
  assert.match(geology, /const undersideSink = Math\.max\(0, -Math\.cos\(angle\)\)/)
  assert.match(geology, /const edgeSink = terminalBurial/)
  assert.match(geology, /positions\.push\(-2\.70, -1\.98, \.52\)/)
  assert.match(geology, /positions\.push\(2\.67, -1\.99, -\.60\)/)
  assert.match(geology, /focusLiteralPixelSuccessorV292 = 'v292-shallow-ground-fracture-buried-ends-broken-scar-lips-no-closed-arch'/)
  assert.match(geology, /focusVisualAuthority = 'v292-sanctuary-memory-fracture'/)
  assert.match(geology, /color\.r = Math\.min\(\.58, color\.r\)/)
  assert.match(geology, /color\.g = Math\.min\(\.46, color\.g\)/)
  assert.match(geology, /color\.b = Math\.min\(\.28, color\.b\)/)
  assert.doesNotMatch(geology, /setRGB\(\.125, \.405, \.485\)|setRGB\(\.72, \.86, \.82\)|setRGB\(\.92, \.38, \.12\)/)
})