import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const worldEvents = fs.readFileSync(new URL('../src/spatial/world/worldEvents.ts', import.meta.url), 'utf8')
const semanticNavigator = fs.readFileSync(new URL('../src/components/lifemap/LifeMapSemanticNavigator.tsx', import.meta.url), 'utf8')
const telemetryBridge = fs.readFileSync(new URL('../src/app/HomeParallaxTelemetryBridge.tsx', import.meta.url), 'utf8')
const focus = fs.readFileSync(new URL('../src/app/focus/FocusChamberClient.tsx', import.meta.url), 'utf8')
const geology = fs.readFileSync(new URL('../src/app/focus/focusMemoryGeology.ts', import.meta.url), 'utf8')

test('deep-travel fallback cannot preempt the canonical transition controller', () => {
  const fallback = worldEvents.match(/WORLD_TRAVEL_FALLBACK_MS\s*=\s*(\d+)/)
  assert.ok(fallback)
  assert.ok(Number(fallback[1]) > 1900)
})

test('overview mode clears semantic selection without discarding route identity', () => {
  assert.match(semanticNavigator, /const overviewRequested = params\.get\(['"]overview['"]\) === ['"]1['"]/)
  assert.match(semanticNavigator, /const selectedId = overviewRequested \? null : params\.get\(['"]node['"]\) \|\| params\.get\(['"]memoryId['"]\)/)
})

test('home telemetry synchronizes from mutations and input without perpetual document polling', () => {
  assert.match(telemetryBridge, /new MutationObserver\(scheduleSynchronization\)/)
  assert.doesNotMatch(telemetryBridge, /requestAnimationFrame\(synchronize\)/)
  assert.doesNotMatch(telemetryBridge, /const synchronize = \(\) =>/)
})

test('Focus focal authority is the selected memory star and cannot regress to V321 terrain cavities', () => {
  assert.match(focus, /Locked product authority; V376 is the current literal-pixel implementation/)
  assert.match(focus, /data-focus-composition="selected-memory-star-with-contained-memory"/)
  assert.match(focus, /data-focus-spatial="selected-memory-star"/)
  assert.match(focus, /data-focus-terrain-owner="false"/)
  assert.match(focus, /name="focus-selected-memory-star"/)
  assert.match(focus, /name="focus-memory-star-glass-shell"/)
  assert.match(focus, /<MemoryVisualContent memory=\{memory\} \/>/)
  assert.match(focus, /selected-memory-star-resolving-through-memory-v376/)
  assert.match(focus, /geometry=\{photosphereGeometry\} scale=\{\[0\.22, 0\.17, 0\.12\]\}/)
  assert.match(focus, /opacity=\{memory \? 0 : 0\.16\}/)
  assert.match(focus, /function makeFocusCoronaTexture\(power: number, rays = false\)/)
  assert.match(focus, /const warpedAngle = angle \+ Math\.sin\(angle \* 3\.0 \+ \.37\) \* \.16/)
  assert.match(focus, /broadPlume/)
  assert.match(focus, /finePlume/)
  assert.match(focus, /const boundary = THREE\.MathUtils\.clamp\(\.94/)
  assert.match(focus, /const rayBoundary = rays/)
  assert.match(focus, /const compactCorona = rays/)
  assert.match(focus, /const streamerTexture = rays/)
  assert.match(focus, /focus-memory-star-corona-filaments-primary/)
  assert.match(focus, /focus-memory-star-corona-filaments-secondary/)
  assert.match(focus, /scale=\{\[5\.20, 4\.10, 1\]\}/)
  assert.match(focus, /opacity=\{memory \? \.62 : \.04\}/)
  assert.match(focus, /distanceFactor=\{1\.92\}/)
  assert.match(focus, /function makeFocusPhotosphereGeometry\(\)/)
  assert.match(focus, /new THREE\.SphereGeometry\(1, 128, 96\)/)
  assert.doesNotMatch(focus, /makeFocusCoronaShellGeometry|geometry=\{coronaShellA\}|geometry=\{coronaShellB\}/)
  assert.match(focus, /opacity:\.58;filter:saturate\(\.84\)/)
  assert.match(focus, /focusMemoryVisual::before/)
  assert.match(focus, /mix-blend-mode:screen;opacity:\.72;z-index:4/)
  assert.match(focus, /opacity:\.46;z-index:5/)
  assert.match(focus, /focusMemoryVisual::after/)
  assert.match(focus, /box-shadow:inset 0 0 28px rgba\(255,255,222,\.42\)/)
  assert.match(focus, /focus-memory-star-photosphere-rays-secondary/)
  assert.match(focus, /name="focus-memory-star-corona-glow"/)
  assert.match(focus, /name="focus-memory-star-photosphere-rays"/)
  assert.match(focus, /name="focus-memory-star-coronal-arm-diagonal-a"/)
  assert.match(focus, /name="focus-memory-star-coronal-arm-diagonal-b"/)
  assert.match(focus, /name="focus-memory-star-white-hot-limb"/)
  assert.match(focus, /color="#fffbe8"/)
  assert.doesNotMatch(focus, /background:conic-gradient\(/)
  assert.match(focus, /width:144px;height:144px/)
  assert.match(focus, /focusStarMemoryButton\{width:126px;height:126px\}/)
  assert.match(focus, /focusStarMemoryButton\{width:116px;height:116px\}/)
  assert.match(focus, /opacity=\{memory \? \.78 : \.03\}/)
  assert.match(focus, /opacity=\{memory \? \.72 : \.02\}/)
  assert.match(focus, /clip-path:circle\(49% at 50% 50%\)/)
  assert.match(focus, /mix-blend-mode:screen/)
  assert.match(focus, /border-radius:50%/)
  assert.match(focus, /focusMemoryVisual\{[^}]*border-radius:50%/)
  assert.match(focus, /focusMemoryVisual\{[^}]*mask-image:radial-gradient\(circle/)
  assert.doesNotMatch(focus, /repeating-conic-gradient\(/)
  assert.doesNotMatch(focus, /\.focusStarMemoryButton::before\{[^}]*clip-path:polygon/)
  assert.match(focus, /\.focusFallbackStar\{[^}]*border-radius:50%/)
  assert.match(focus, /\.focusFallbackStar\{[^}]*clip-path:none/)
  assert.doesNotMatch(focus, /\.focusFallbackStar\{[^}]*clip-path:polygon/)
  assert.match(focus, /filter:blur\(\.9px\);opacity:\.68/)
  assert.match(focus, /opacity=\{memory \? 0 : 0\.012\}/)
  assert.match(focus, /function makeFocusSphereTexture\(\)/)
  assert.match(focus, /<meshBasicMaterial[\s\S]*map=\{sphereTexture\}[\s\S]*blending=\{THREE\.AdditiveBlending\}[\s\S]*depthWrite=\{false\}/)
  assert.match(focus, /memory\.sourceMedia\.find/)
  assert.match(focus, /Generated demo visualization/)
  assert.doesNotMatch(focus, /createFocusStrata|createFocusGroundIncision|FocusSanctuaryGround|FocusStoneBank/)
  assert.doesNotMatch(focus, /focus-v321-focal-readable-three-radial-pressure-cavity-bottoms|focus-v251-grounded-living-memory-manifestation/)
  assert.match(geology, /v321-focal-readable-three-radial-terrain-cavities-localized-bottoms-ground-blended-hairline-connector-buried-closed-body/)
})

test('Focus convergence preserves Replay activation, selected-memory semantics, reduced motion, and star interaction safety', () => {
  assert.match(focus, /if \(!memory \|\| !replayHref \|\| committed\) return/)
  assert.match(focus, /'Enter Replay for ' \+ memory\.title/)
  assert.doesNotMatch(focus, /Open Replay for/)
  assert.match(focus, /reducedMotion/)
  assert.match(focus, /requestUraiWorldTravel\(\{/)
  assert.match(focus, /destination: 'replay'/)
  assert.match(focus, /requestUraiWorldReturn\(\)/)
  assert.match(focus, /terrainOwner: false/)
})
