import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const geology = fs.readFileSync(new URL('../src/app/focus/focusMemoryGeology.ts', import.meta.url), 'utf8')

test('selected memory remains one connected CLOSED living-memory phenomenon rather than discrete shards, cards, or an open ribbon', () => {
  assert.match(geology, /V272 established one connected living-memory phenomenon/)
  assert.match(geology, /const MEMORY_SECTIONS = 41/)
  assert.match(geology, /const MEMORY_CROSS_POINTS = 9/)
  assert.match(geology, /function createLivingMemoryFold\(/)
  assert.match(geology, /const furrowCenter =/)
  assert.match(geology, /const furrow = Math\.exp/)
  assert.match(geology, /- \.175 \* furrow/)
  assert.match(geology, /const bottomOffset = topVertexCount/)
  assert.match(geology, /positions\.push\(positions\[i\], positions\[i \+ 1\] - \.18, positions\[i \+ 2\]\)/)
  assert.match(geology, /focusMemoryRole = 'v272-single-connected-living-memory-fold'/)
  assert.match(geology, /focusMemoryTopology = 'v295-closed-ground-fused-scar-volume-with-buried-closure'/)
  assert.match(geology, /focusLiteralPixelRepair = 'v272-no-crystal-crown-no-card-stack'/)
  assert.match(geology, /focusSilhouetteRule = 'one-closed-ground-owned-scar-no-split-pair-no-portable-outline'/)
  assert.match(geology, /return \[createLivingMemoryFold\(\)\]/)

  assert.doesNotMatch(geology, /const MEMORY_FACETS:/)
  assert.doesNotMatch(geology, /function createMemoryFacet\(/)
  assert.doesNotMatch(geology, /v271-interlocked-volumetric-memory-facet/)
  assert.doesNotMatch(geology, /createMemoryLamella/)
  assert.doesNotMatch(geology, /v269-living-luminous-memory-lamella/)
  assert.doesNotMatch(geology, /Array\.from\(\{ length: 7 \}/)
})

test('V298 preserves V295 watertight topology while eliminating the broad slab/ribbon read', () => {
  assert.match(geology, /V295 keeps the useful V294 top-surface language while restoring the non-negotiable/)
  assert.match(geology, /V297 removed the split-pair read/)
  assert.match(geology, /V298 therefore changes silhouette and/)
  assert.match(geology, /const deep = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /const mineral = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /const weathered = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /const warm = new THREE\.Color\(\)\.setRGB/)
  assert.match(geology, /focusMemoryEnergy = 'weathered-mineral-restrained-warm-cool-response'/)
  assert.match(geology, /function fractureCenter\(t: number\)/)
  assert.match(geology, /const x = 1\.56 \* t/)
  assert.match(geology, /const z = -1\.02 \* t/)
  assert.match(geology, /const terminalSink = THREE\.MathUtils\.smoothstep\(Math\.abs\(t\), \.66, 1\) \* \.34/)
  assert.match(geology, /const centralScar = Math\.exp/)
  assert.match(geology, /const nearPressure = Math\.exp/)
  assert.match(geology, /const farPressure = Math\.exp/)
  assert.match(geology, /const brokenKnot = Math\.exp/)
  assert.match(geology, /const pressureWindow =/)
  assert.match(geology, /const centerY = -1\.255/)
  assert.match(geology, /const dominantLipCenter =/)
  assert.match(geology, /const counterLipCenter =/)
  assert.match(geology, /const dominantLip = Math\.exp/)
  assert.match(geology, /const counterLip = Math\.exp/)
  assert.match(geology, /const minimalContinuity = scarCore/)
  assert.match(geology, /const localBuckling =/)
  assert.match(geology, /const edgeSink = THREE\.MathUtils\.smoothstep/)
  assert.match(geology, /const lateralDistance = lateral \* halfWidth/)
  assert.match(geology, /focusLiteralPixelSuccessorV298 = 'v298-narrow-short-deep-incision-broken-dominant-lip-counter-side-buried-no-panel'/)
  assert.match(geology, /focusVisualAuthority = 'v295-sanctuary-memory-scar-volume'/)
  assert.match(geology, /focusCurrentVisualAuthority = 'v298-narrow-broken-ground-held-memory-scar'/)
  assert.match(geology, /color\.r = Math\.min\(\.54, color\.r\)/)
  assert.match(geology, /color\.g = Math\.min\(\.36, color\.g\)/)
  assert.match(geology, /color\.b = Math\.min\(\.17, color\.b\)/)
  assert.doesNotMatch(geology, /focusSilhouetteRule = 'one-ground-owned-scar-no-closed-volume-no-split-pair'/)
  assert.doesNotMatch(geology, /focusCurrentVisualAuthority = 'v294-open-continuous-memory-rupture'/)
  assert.doesNotMatch(geology, /focusCurrentVisualAuthority = 'v297-off-axis-continuous-ground-held-memory-rupture'/)
  assert.doesNotMatch(geology, /setRGB\(\.125, \.405, \.485\)|setRGB\(\.72, \.86, \.82\)|setRGB\(\.92, \.38, \.12\)/)
})