import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const ground = readFileSync(new URL('../src/app/GroundSpatialWorldClean.tsx', import.meta.url), 'utf8')
const groundCanon = readFileSync(new URL('../src/spatial/ground/groundCanon.ts', import.meta.url), 'utf8')

test('Ground renders the current atmospheric lived world instead of the rejected root-vault substrate', () => {
  assert.match(ground, /data-ground-visual-revision="ground-lived-world-v2-canon-lock"/)
  assert.match(ground, /data-ground-art-revision="ground-v34-dense-small-leaf-broadleaf-atmospheric-depth"/)
  assert.match(ground, /data-ground-visual-owner="atmospheric-living-environment"/)
  assert.match(ground, /<AtmosphericGroundSky profile=\{profile\} \/>/)
  assert.match(ground, /<NaturalScatter profile=\{profile\} \/>/)
  assert.match(ground, /<DistantGroundContinuation profile=\{profile\} \/>/)
  assert.match(ground, /const GROUND_BROADLEAF_CANOPY = "\/assets\/urai\/ground-production\/cc0\/polyhaven-jacaranda-web-v1\.glb"/)
  assert.match(ground, /name="ground-cc0-jacaranda-canopy-v35"/)
  assert.match(ground, /visibleAuthority: "scanned-broadleaf-canopy-candidate-v35"/)
  assert.match(ground, /supersedesVisibleCandidate: "runtime-authored-canopy-v34"/)
  assert.match(ground, /treatment: "cc0-photoreal-broadleaf-canopy-v35"/)
  assert.match(ground, /sourceAuthority: "poly-haven-jacaranda-tree-cc0"/)
  assert.match(ground, /const FERN = "\/assets\/urai\/home-production\/cc0\/polyhaven-v48\/fern_02\/asset\.gltf"/)
  assert.match(ground, /function FernPatch/)
  assert.match(ground, /cc0-scanned-broadleaf-edge-canopy-v35/)
  assert.doesNotMatch(ground, /alphaMap=\{alphaMap\}/)
  assert.match(ground, /natural-soil-no-repeating-rock-maps-v27/)
  assert.match(ground, /organic-tapered-trunk-branch-silhouette-v28/)
  assert.match(ground, /v28-organic-tapered-trunk-branch-silhouette/)
  assert.match(ground, /ground-urban-authored-setback-architecture-v29/)
  assert.match(ground, /authored-setback-offset-skyline-v29-no-extruded-placeholder-massing/)
  assert.doesNotMatch(ground, /new THREE\.ExtrudeGeometry\(urbanFootprint/)
  assert.match(ground, /ground-coastal-deforming-water-surface-v29/)
  assert.match(ground, /ground-coastal-deforming-water-v29/)
  assert.doesNotMatch(ground, /<planeGeometry args=\{\[96, 42, 16, 10\]\}/)
  assert.match(ground, /makeOrganicTaperedTube/)
  assert.match(ground, /Array\.from\(\{ length: woodland \? 640 : 540 \}/)
  assert.match(ground, /const sx = 0\.20 \+ hash\(index \* 7 \+ 9\) \* 0\.18/)
  assert.match(ground, /slice\(0, woodland \? 18 : 14\)/)
  assert.match(ground, /v35-photoreal-jacaranda-edge-canopy-plus-scanned-understory/)
  assert.match(ground, /data-ground-canopy-repair="ground-v34-dense-small-leaf-broadleaf-no-cloned-tree-field"/)
  assert.match(ground, /data-ground-foliage-repair="ground-v34-scanned-fern-understory-separated-from-crown"/)
  assert.match(ground, /canopyFallback: "scanned-understory-remains-if-canopy-load-fails"/)
  assert.match(ground, /const ferns = items\.slice\(0, woodland \? 92 : 88\)/)
  assert.match(ground, /items\.slice\(0, 20\)/)
  assert.doesNotMatch(ground, /new THREE\.IcosahedronGeometry\(0\.5, 0\)/)
  assert.match(ground, /<ScannedRock/)
  assert.match(ground, /<FernPatch/)
  assert.match(ground, /map=\{albedo\}/)
  assert.match(ground, /normalMap=\{normal\}/)
  assert.match(ground, /roughnessMap=\{arm\}/)
  assert.match(ground, /<color attach="background" args=\{\[profile\.horizon\]\} \/>/)
  assert.match(ground, /<fogExp2 attach="fog" args=\{\[profile\.fog, 0\.0086/)
  assert.match(ground, /gl\.toneMappingExposure = 0\.84/)
  assert.match(ground, /data-ground-runtime-owner="first-person-lived-world"/)
  assert.match(ground, /name="ground-lived-world"/)
  assert.match(ground, /name="ground-visible-traversable-terrain"/)
  assert.doesNotMatch(ground, /<GroundSubstrateWorld profile=\{profile\} \/>/)
  assert.doesNotMatch(ground, /GroundPhysicalArchitecture|GroundVaultArchitecture|ground-destination-compass|ground-central-nexus/)
})

test('Ground uses true eye-level terrain-following first-person movement', () => {
  assert.match(groundCanon, /export const GROUND_EYE_HEIGHT_M = 1\.69/)
  assert.match(ground, /groundHeight\(position\.current\.x, position\.current\.z, profile\.id\)/)
  assert.match(ground, /desired\.current\.set\(position\.current\.x, surfaceY \+ GROUND_EYE_HEIGHT_M, position\.current\.z\)/)
  assert.match(ground, /data-ground-camera="eye-level-terrain-following-no-authored-bob"/)
  assert.match(ground, /data-ground-collision="terrain-plus-authored-obstacle-field"/)
  assert.match(ground, /stepEmbodiedMotion/)
  assert.match(ground, /buildGroundObstacleField\(profile\.id\)/)
  assert.doesNotMatch(ground, /cameraOffset|distance = portrait \? 1\.4 : 1\.1/)
})

test('Visible terrain owns traversal and private place data remains fail-closed by default', () => {
  assert.match(ground, /onClick=\{onTerrainClick\}/)
  assert.match(ground, /event\.delta > 8/)
  assert.match(ground, /data-ground-place-layer="consent-aware-empty-by-default"/)
  assert.match(ground, /data-ground-private-location-mounted="false"/)
  assert.match(ground, /href="\/location-map\/geographic\/"/)
  assert.match(ground, /href="\/privacy-controls"/)
  assert.doesNotMatch(ground, /ground-walkable-navigation-surface|planeGeometry args=\{\[30, 44\]\}/)
})

test('Ground preserves one adaptive opaque Canvas and five physical environment profiles', () => {
  assert.equal((ground.match(/<Canvas/g) || []).length, 1)
  assert.match(ground, /alpha: false/)
  for (const profile of ['temperate', 'urban', 'woodland', 'arid', 'coastal']) {
    assert.match(ground, new RegExp(`${profile}: \\{ id: "${profile}"`))
  }
  assert.match(ground, /MobileMovementPad input=\{input\} label="Ground first-person movement controls"/)
})
