import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
const source=readFileSync(new URL('../src/spatial/layout/HomeWorldProductionFinal.tsx',import.meta.url),'utf8')
const architecture=source.slice(source.indexOf('function ContinuousVaultSkin'),source.indexOf('function SanctuaryGlazing'))
const machine=source.slice(source.indexOf('function MachineCoreAssembly'),source.indexOf('function HumanPresence'))
const orb=source.slice(source.indexOf('function SacredOrb'),source.indexOf('function HumanPresence'))
test('V64 removes the rejected primitive arch and flat backboard composition',()=>{assert.match(source,/v64-photogrammetry-orb-sanctuary-retained-pixel-rebuild/);assert.match(source,/visualOwner:'photogrammetry-orb-sanctuary-v64'/);assert.doesNotMatch(architecture,/SanctuaryShellMass|ArchitecturalStone/);assert.doesNotMatch(architecture,/v63-deep-stone-sanctuary-with-integrated-geology-no-display-frame/)})
test('V64 makes committed photogrammetry geometry own the sanctuary depth',()=>{for(const name of ['home-v64-left-deep-wall','home-v64-right-deep-wall','home-v64-left-rear-depth','home-v64-right-rear-depth','home-v64-upper-left-vault','home-v64-upper-right-vault']) assert.match(architecture,new RegExp(name));assert.match(architecture,/v64-photogrammetry-cavern-sanctuary-no-arch-no-flat-backboard/)})
test('V64 buries service infrastructure instead of hanging pipe racks on the focal wall',()=>{assert.match(architecture,/v64-service-infrastructure-buried-behind-photogrammetry-geology/);assert.match(architecture,/home-v64-left-buried-service/);assert.match(architecture,/home-v64-right-buried-service/);assert.doesNotMatch(machine,/ProductionAsset url=\{V48_PIPE_SYSTEM\}/)})
test('V64 restores monumental authored Orb scale without primitive replacement geometry',()=>{assert.match(orb,/home-v64-monumental-authored-orb/);assert.match(orb,/scale=\{1\.02\}/);assert.match(orb,/<primitive object=\{authoredOrb\}/);assert.doesNotMatch(orb,/cylinderGeometry|sphereGeometry|icosahedronGeometry|dodecahedronGeometry|torusGeometry/);assert.match(source,/const ORB = new THREE\.Vector3\(0, 2\.38, -7\.35\)/)})
test('V64 remains fail closed pending literal retained-pixel review',()=>{assert.match(source,/data-home-visual-grade="cinematic-pbr-v64-photogrammetry-orb-sanctuary"/);assert.match(source,/data-home-final-art-revision="v64-photogrammetry-orb-sanctuary-candidate"/);assert.match(source,/data-home-art-certification="v64-retained-pixel-candidate-not-certified"/);assert.match(source,/data-home-animation-owner="photogrammetry-orb-sanctuary-v64-plus-governed-orb-identity"/);assert.doesNotMatch(source,/PRODUCTION CERTIFIED|retained-pixel-pass|pixel-certified/)})
