import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
const source=readFileSync(new URL('../src/spatial/layout/HomeWorldProductionFinal.tsx',import.meta.url),'utf8')
const machine=source.slice(source.indexOf('function FacetedMachinePanel'),source.indexOf('function HumanPresence'))
const architecture=source.slice(source.indexOf('function ContinuousVaultSkin'),source.indexOf('function SanctuaryGlazing'))
test('V60 owns a continuous enclosed chamber with a faceted wall relic',()=>{assert.match(source,/v60-faceted-wall-relic-retained-pixel-rebuild/);assert.match(source,/visualOwner:'faceted-wall-relic-v60'/);assert.match(architecture,/v59-continuous-asymmetric-enclosed-chamber-no-arch-facade/);assert.match(source,/const ORB = new THREE\.Vector3\(0, 2\.18, -6\.42\)/)})
test('V60 visible relic eliminates the rejected rounded-bar, spoke and spherical Orb grammar',()=>{assert.match(machine,/v60-wall-integrated-faceted-reliquary-no-rods-no-spokes-no-display-frame/);assert.match(machine,/v60-recessed-faceted-state-aperture-inside-wall-integrated-relic-machine/);assert.match(machine,/home-v60-orb-state-slit/);assert.doesNotMatch(machine,/OrbArmorPlate|TaperedLoadBeam|sphereGeometry|icosahedronGeometry|dodecahedronGeometry|torusGeometry|circleGeometry|TubeGeometry/);assert.doesNotMatch(machine,/RoundedBox/)})
test('V60 retains governed Orb identity invisibly while visible pixels are machine-owned',()=>{assert.match(machine,/visible=\{false\}/);assert.match(machine,/v60-governed-glb-animation-identity-retained-invisibly-for-state-contract/);assert.match(source,/data-home-animation-owner="faceted-wall-relic-v60-plus-governed-orb-identity"/)})
test('V60 remains candidate-only until literal retained pixels pass',()=>{assert.match(source,/data-home-visual-grade="cinematic-pbr-v60-faceted-wall-relic"/);assert.match(source,/data-home-final-art-revision="v60-faceted-wall-relic-candidate"/);assert.match(source,/data-home-art-certification="v60-retained-pixel-candidate-not-certified"/);assert.doesNotMatch(source,/PRODUCTION CERTIFIED|retained-pixel-pass|pixel-certified/)})
