import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const runtime = readFileSync(new URL('../src/spatial/layout/HomeWorldProductionV70.tsx', import.meta.url), 'utf8')
const art = readFileSync(new URL('../src/spatial/layout/HomeWorldProductionV76.tsx', import.meta.url), 'utf8')
const styles = readFileSync(new URL('../src/spatial/layout/HomeWorldProduction.module.css', import.meta.url), 'utf8')

test('V167 preserves the single opaque responsive Canvas owner', () => {
  assert.doesNotMatch(runtime, /backgroundImage:/)
  assert.match(runtime, /data-home-desktop-mobile-world="same-scene"/)
  assert.match(runtime, /alpha: false/)
  assert.match(runtime, /gl\.setClearColor\(0x080b0b, 1\)/)
  assert.match(runtime, /const fov = portrait \? 50 : 40/)
  assert.match(styles, /\.canvas/)
})

test('V167 gives one continuous ground authority, raised canyon relief, and an irregular contained memory swarm', () => {
  assert.match(art, /governed-landscape-provenance-retained-nonrendered-single-ground-owner/)
  assert.match(art, /<primitive object=\{environment\} visible=\{false\} \/>/)
  assert.match(art, /<primitive object=\{thresholds\} visible=\{false\} \/>/)
  assert.match(art, /const xSegments = 72/)
  assert.match(art, /const zSegments = 96/)
  assert.match(art, /const farBasinLift = Math\.pow\(tz,2\.35\)\*0\.92/)
  assert.match(art, /single-authority-deep-canyon-basin-raised-horizon-no-overlap-islands/)
  assert.match(art, /normalScale=\{new THREE\.Vector2\(0\.48,0\.48\)\}/)
  assert.match(art, /name="home-v154-inlaid-stone-approach"[^>]*visible=\{false\}/)
  assert.match(art, /name="home-v131-passive-signal-arrival-path"[^>]*visible=\{false\}/)
  assert.match(art, /edge-scans-outside-primary-frustum-no-pasted-islands/)
  assert.match(art, /terrain-flush-readable-destination-cut-clear-camera-corridor-no-door-no-ring/)
  assert.match(art, /name="home-v149-weathered-rift-threshold-sanctuary" visible=\{false\}/)
  assert.match(art, /name="home-v126-layered-apse-orb-cradle" visible=\{false\}/)
  assert.match(art, /for\(let index=0;index<1080;index\+=1\)/)
  assert.match(art, /filled-irregular-memory-swarm-small-seed-no-shell-silhouette/)
  assert.match(art, /name="home-v126-apse-integrated-orb"[^>]*scale=\{\[1\.30,1\.30,1\.30\]\}/)
  assert.match(art, /name="home-v132-orb-memory-volume"[^>]*scale=\{\[0\.48,0\.54,0\.46\]\}/)
  assert.match(art, /transparent opacity=\{0\.055\}/)
  assert.match(art, /name="home-v126-orb-memory-motes"[^>]*scale=\{\[1\.14,1\.18,1\.08\]\}/)
  assert.match(art, /name="home-v154-orb-memory-depth-motes"[^>]*scale=\{\[1\.30,1\.34,1\.20\]\}/)
  assert.match(art, /name="home-v133-orb-memory-seed"[^>]*scale=\{\[0\.24,0\.30,0\.22\]\}/)
  assert.match(art, /currentVisualRefinement:'v167-single-ground-deep-canyon-irregular-memory-swarm-no-runway'/)
  assert.match(art, /remove-overlapping-ground-islands-raise-canyon-horizon-rebuild-orb-as-filled-swarm/)
  assert.match(art, /object\.name === 'orb-aura'/)
  assert.match(art, /object\.name\.startsWith\('orb-orbit-'/)
  assert.doesNotMatch(art, /function canyonShelfGeometry|function CanyonShelf|home-v164-\$\{side\}-continuous-canyon-shelf/)
  assert.doesNotMatch(art, /<ringGeometry|<torusGeometry|<RoundedBox/)
  assert.doesNotMatch(art, /retained-pixel-pass|pixel-certified|PRODUCTION CERTIFIED/)
})
