import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
const source=readFileSync(new URL('../src/spatial/layout/HomeWorldProductionFinal.tsx',import.meta.url),'utf8')
const machine=source.slice(source.indexOf('function MachineCoreAssembly'),source.indexOf('function HumanPresence'))
const architecture=source.slice(source.indexOf('function ContinuousVaultSkin'),source.indexOf('function SanctuaryGlazing'))
test('V62 removes the rejected procedural relic-slab display composition',()=>{assert.match(source,/v62-asset-backed-service-vault-retained-pixel-rebuild/);assert.match(source,/visualOwner:'asset-backed-service-vault-v62'/);assert.doesNotMatch(machine,/RelicMass|ExtrudeGeometry|v61-thick-asymmetric-load-bearing-relic-mass/);assert.match(machine,/v62-real-industrial-service-manifold-layered-through-stone-no-procedural-relic-slabs/)})
test('V62 uses committed real service assets for the visible machine and side galleries',()=>{assert.match(machine,/home-v62-machine-main-manifold/);assert.match(machine,/home-v62-machine-left-load-path/);assert.match(machine,/home-v62-machine-right-load-path/);assert.match(architecture,/home-v62-left-service-gallery/);assert.match(architecture,/home-v62-right-service-gallery/);assert.match(architecture,/home-v62-rear-service-manifold/)})
test('V62 integrates geology as foundation and upper key instead of floating side props',()=>{assert.match(architecture,/home-v62-left-geology-foundation/);assert.match(architecture,/home-v62-right-geology-foundation/);assert.match(architecture,/home-v62-upper-geology-key/);assert.match(architecture,/v62-open-service-vault-with-integrated-geology-no-display-frame/)})
test('V62 preserves governed Orb identity and a machine-owned visible state core',()=>{assert.match(machine,/visible=\{false\}/);assert.match(machine,/v62-governed-glb-animation-identity-retained-invisibly-for-state-contract/);assert.match(machine,/home-v62-orb-core-housing/);assert.match(machine,/home-v62-orb-state-window/);assert.match(source,/data-home-animation-owner="asset-backed-service-vault-v62-plus-governed-orb-identity"/)})
test('V62 remains fail closed pending literal retained-pixel review',()=>{assert.match(source,/data-home-visual-grade="cinematic-pbr-v62-asset-backed-service-vault"/);assert.match(source,/data-home-final-art-revision="v62-asset-backed-service-vault-candidate"/);assert.match(source,/data-home-art-certification="v62-retained-pixel-candidate-not-certified"/);assert.doesNotMatch(source,/PRODUCTION CERTIFIED|retained-pixel-pass|pixel-certified/)})
