import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const runtime = readFileSync(new URL('../src/spatial/layout/HomeWorldProductionV70.tsx', import.meta.url), 'utf8')
const art = readFileSync(new URL('../src/spatial/layout/HomeWorldProductionV76.tsx', import.meta.url), 'utf8')
const styles = readFileSync(new URL('../src/spatial/layout/HomeWorldProduction.module.css', import.meta.url), 'utf8')

test('V105 uses one opaque responsive Canvas with balanced portrait hierarchy', () => {
  assert.doesNotMatch(runtime, /backgroundImage:/)
  assert.match(runtime, /data-home-desktop-mobile-world="same-scene"/)
  assert.match(runtime, /alpha: false/)
  assert.match(runtime, /gl\.setClearColor\(0x080b0b, 1\)/)
  assert.match(runtime, /camera=\{\{ position: \[SPAWN\.x, 1\.60, SPAWN\.z\], fov: 42/)
  assert.match(runtime, /const fov = portrait \? 58 : 42/)
  assert.doesNotMatch(runtime, /const fov = portrait \? 86 : 42/)
  assert.match(styles, /\.canvas/)
})

test('V158 keeps responsive framing while replacing the V157 road/gate read with a hairline stone trace, ground-laid rifts and sunken geology around the contained no-pedestal memory core', () => {
  assert.doesNotMatch(art, /SANCTUARY_BACKDROP|scene\.userData\.sanctuaryBackdrop/)
  assert.match(art, /function SculptedCanyonGround/)
  assert.match(art, /name="home-v125-sculpted-canyon-ground"/)
  assert.match(art, /function SanctuaryTerraces/)
  assert.match(art, /home-v126-continuous-walkable-terrace-network/)
  assert.match(art, /home-v154-inlaid-stone-approach/)
  assert.match(art, /narrow-meandering-inlay-not-road-slab/)
  assert.match(art, /hairline-stone-trace-integrated-into-ground-no-road-read/)
  assert.match(art, /const stations = 80/)
  assert.match(art, /const half = 0\.13 - t \* 0\.035/)
  assert.match(art, /function GeologicalFrame/)
  assert.match(art, /name="home-v126-bounded-geological-edge-masses"/)
  assert.match(art, /scan-provenance-kept-off-axis-while-authored-ground-owns-frame/)
  assert.match(art, /scan-provenance-remains-off-axis-after-ground-scar-refinement/)
  assert.match(art, /position: \[-9\.65, -1\.20, -4\.2\]/)
  assert.match(art, /position: \[9\.62, -1\.20, -4\.5\]/)
  assert.match(art, /function FramedFissure/)
  assert.match(art, /home-v126-\$\{side\}-framed-fissure/)
  assert.match(art, /v154-buried-irregular-stone-fissure-no-facade-hoops-or-translucent-panels/)
  assert.match(art, /ground-laid-navigation-scar-no-upright-gate-silhouette/)
  assert.match(art, /rotation=\{\[-1\.02, isGround \? 0\.16 : -0\.16, isGround \? -0\.12 : 0\.12\]\}/)
  assert.match(art, /scale=\{isGround \? \[0\.24, 0\.44, 0\.28\] : \[0\.23, 0\.46, 0\.28\]\}/)
  assert.match(art, /for \(let index = 0; index < 48; index \+= 1\)/)
  assert.match(art, /new THREE\.ExtrudeGeometry\(frame, \{ depth: 0\.12/)
  assert.match(art, /boxGeometry args=\{\[4\.20, 4\.20, 2\.80\]\}/)
  assert.match(art, /function weatheredSanctuaryMassGeometry/)
  assert.match(art, /home-v149-weathered-rift-threshold-sanctuary/)
  assert.match(art, /v154-faceted-broken-buttresses-no-rounded-boulder-gates/)
  assert.match(art, /terrain-relief-shelves-sunk-into-ground-no-boulder-piles/)
  assert.match(art, /ground-rift-settled-shoulder/)
  assert.match(art, /life-map-rift-settled-shoulder/)
  assert.match(art, /function ApseAndOrbCradle/)
  assert.match(art, /home-v126-layered-apse-orb-cradle/)
  assert.match(art, /v154-broken-side-shelves-frame-orb-without-pedestal/)
  assert.match(art, /apse-ledges-sunk-into-terrain-clear-orb-air-gap/)
  assert.match(art, /function LivingOrb/)
  assert.match(art, /name="home-v126-apse-integrated-orb"/)
  assert.match(art, /home-v154-orb-memory-depth-motes/)
  assert.match(art, /contained-memory-core-not-particle-fountain/)
  assert.match(art, /orb-floats-over-continuous-terrain-without-rock-cradle-clutter/)
  assert.match(art, /name="home-v125-atmospheric-depth-motes"/)
  assert.match(art, /activeArtRevision: 'v154-visible-canyon-fissures-memory-swarm-no-pedestal'/)
  assert.match(art, /visualIteration: 'v158-ground-scar-thresholds-hairline-path-sunken-geology'/)
  assert.match(art, /predecessorVisualIteration: 'v157-canyon-path-thin-rifts-low-geology-contained-orb'/)
  assert.match(art, /predecessorArtRevision: 'v153-localized-fissures-asymmetric-orb-plume-no-pedestal'/)
  assert.match(art, /new THREE\.IcosahedronGeometry\(1, 2\)/)
  assert.match(art, /new THREE\.IcosahedronGeometry\(0\.72, 3\)/)
  assert.match(art, /for \(let index = 0; index < 980; index \+= 1\)/)
  assert.match(art, /Array\.from\(\{ length: 6 \}/)
  assert.match(art, /retained-stone-provenance[^\n]*castShadow receiveShadow>/)
  assert.match(art, /retired-threshold-panel[^\n]*geometry=\{field\}[^\n]*>/)
  assert.match(art, /const rejectedHorizonRepeat = object\.name\.startsWith\('horizon-mountain-'\)/)
  assert.match(art, /const ORB = new THREE\.Vector3\(-0\.18, 2\.18, -6\.90\)/)
  assert.match(art, /object\.name === 'orb-aura'/)
  assert.match(art, /object\.name\.startsWith\('orb-orbit-'/)
  assert.doesNotMatch(art, /function layeredSanctuaryWingGeometry|function cradleSupportGeometry/)
  assert.doesNotMatch(art, /<ringGeometry|<torusGeometry|<RoundedBox/)
})