import assert from 'node:assert/strict'
import { readFileSync, statSync } from 'node:fs'
import test from 'node:test'

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const world = read('src/components/lifemap/LifeMapProductionWorld.tsx')
const scene = read('src/components/lifemap/ComposedLifeMapScene.tsx')
const focus = read('src/app/focus/FocusChamberClient.tsx')
const geology = read('src/app/focus/focusMemoryGeology.ts')
const replay = read('src/app/replay/CinematicReplayClient.tsx')
const companion = read('src/spatial/world/persistentWorldCompanion.css')
const generator = read('scripts/blender/generate-life-map-sanctuary-v215.py')

test('historical V215 single-surface source remains reproducible but is not runtime-mounted', () => {
  const asset = new URL('../public/assets/urai/life-map-production/authored-v215/life-map-memory-sanctuary-v215.glb', import.meta.url)
  assert.ok(statSync(asset).size > 1_000_000)
  assert.match(generator, /def sanctuary_height/)
  assert.match(generator, /one continuous camera-safe sanctuary/)
  assert.doesNotMatch(generator, /braided_channel|integrated_relief|def scarp/)
  assert.match(world, /V237 literal-pixel authority: a continuous illuminated memory valley/)
  assert.doesNotMatch(world, /authored-v215\/life-map-memory-sanctuary-v215\.glb/)
})

test('V237 runtime keeps retired V215 strata out while grounded outcrops inhabit continuous geography', () => {
  assert.match(world, /function memoryHeartGeometry\(/)
  assert.match(world, /function memoryFilamentGeometry\(/)
  assert.match(world, /life-map-v229-open-branching-memory-grove/)
  assert.doesNotMatch(world, /function smoothMemoryGeometry\(/)
  assert.match(world, /<primitive object=\{hiddenAsset\} visible=\{false\} \/>/)
  assert.match(world, /life-map-weathered-memory-outcrop-/)
  assert.match(world, /life-map-v237-continuous-illuminated-memory-geography/)
  assert.match(world, /life-map-v237-root-system-/)
  assert.doesNotMatch(world, /function MemorySeed\(|life-map-v215-rooted-strata-memory|function memoryLedgerGeometry\(/)
})

test('Life Map selection routing cannot let stale overview state cancel the journey', () => {
  assert.match(scene, /selectionRoutePending\.current = true/)
  assert.match(scene, /if \(selectionRoutePending\.current\) return/)
  assert.match(scene, /setPhase\("approach"\)/)
})

test('Focus formation stays grounded in the authored chamber and current connected CLOSED memory fissure while Replay preserves readable organic-edged media', () => {
  assert.match(focus, /V250 convergence authority: the selected living-memory manifestation owns the/)
  assert.match(focus, /function FocusSanctuaryGround\(/)
  assert.match(focus, /focus-v251-grounded-living-memory-manifestation/)
  assert.match(focus, /focus-authored-living-memory-fold-/)
  assert.match(focus, /v272-single-connected-living-memory-fold/)
  assert.match(geology, /focusMemoryRole = 'v272-single-connected-living-memory-fold'/)
  assert.match(geology, /focusSilhouetteRule = 'one-closed-ground-owned-fissure-no-split-pair-no-portable-outline'/)
  assert.match(geology, /focusMemoryTopology = 'v295-closed-ground-fused-scar-volume-with-buried-closure'/)
  assert.match(geology, /focusVisualAuthority = 'v295-sanctuary-memory-scar-volume'/)
  assert.match(geology, /focusLiteralPixelSuccessorV301 = 'v301-crack-scale-dark-incision-intermittent-mineral-crust-no-raised-strip'/)
  assert.match(geology, /focusLiteralPixelSuccessorV302 = 'v302-grade-flush-hairline-incision-fragmented-low-crust-ground-owned-silhouette'/)
  assert.match(geology, /focusLiteralPixelSuccessorV303 = 'v303-shared-world-exact-grade-dark-crack-buried-closure-no-viewport-lift'/)
  assert.match(geology, /focusLiteralPixelSuccessorV304 = 'v304-buried-closed-body-coplanar-ground-incision-no-object-edge'/)
  assert.match(geology, /focusLiteralPixelSuccessorV311 = 'v311-near-black-asymmetric-pressure-voids-sparse-ground-blended-rims-no-raised-strip'/)
  assert.match(geology, /focusIncisionAuthority = 'v311-three-near-black-asymmetric-pressure-voids-sparse-ground-blended-rims-hairline-connector'/)
  assert.match(geology, /focusCurrentVisualAuthority = 'v311-ground-owned-near-black-pressure-void-fissure-buried-closed-body'/)
  assert.doesNotMatch(focus, /focus-authored-fractured-stratum-/)
  assert.doesNotMatch(geology, /v269-living-luminous-memory-lamella|v271-interlocked-volumetric-memory-facet/)
  assert.match(focus, /focus-retired-procedural-vault/)
  assert.match(focus, /<group visible=\{false\} name="focus-retired-procedural-vault"/)
  assert.match(focus, /focus-v216-continuous-weathered-vault/)
  assert.doesNotMatch(focus, /function focusMemoryBranches\(|new THREE\.TubeGeometry|v250-living-memory-tree-manifestation|focus-v249-memory-root-cradle/)
  assert.match(replay, /new THREE\.PlaneGeometry\(13\.8, 7\.4/)
  assert.match(replay, /texture2D\(uMap,vUv\)/)
  assert.match(replay, /function replayMemoryWallGeometry\(\)/)
  assert.match(replay, /replay-v216-embedded-memory-cove/)
  assert.doesNotMatch(replay, /sampleUv|p\.z\+=sin/)
})

test('the companion has an authored memory glyph and an unclipped accessible control', () => {
  assert.match(companion, /width: 64px/)
  assert.match(companion, /height: 64px/)
  assert.doesNotMatch(companion, /clip-path/)
  assert.match(companion, /outline: 3px/)
  const markup = read('src/spatial/world/PersistentWorldCompanion.tsx')
  assert.match(markup, /<svg viewBox="0 0 48 48" aria-hidden="true" focusable="false">/)
  assert.match(markup, /strokeLinecap="round"/)
})