import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (relativePath) => fs.readFileSync(new URL(`../${relativePath}`, import.meta.url), 'utf8')
const boundary = read('src/components/lifemap/LifeMapRouteBoundary.tsx')
const scene = read('src/components/lifemap/CosmicComposedLifeMapScene.tsx')
const navigator = read('src/components/lifemap/LifeMapSemanticNavigator.tsx')
const selectionBroker = read('src/components/lifemap/lifeMapSelection.ts')

test('canonical Life Map mounts one cosmic stellar owner plus the semantic navigator', () => {
  assert.match(boundary, /import ComposedLifeMapScene from ['"]\.\/CosmicComposedLifeMapScene['"]/)
  assert.match(boundary, /<ComposedLifeMapScene \/>/)
  assert.match(boundary, /<LifeMapSemanticNavigator \/>/)
  assert.doesNotMatch(boundary, /from ['"]\.\/ComposedLifeMapScene['"]|from ['"]\.\/AdaptiveLifeMapScene['"]/)
  assert.equal((scene.match(/<Canvas\b/g) || []).length, 1)
  assert.match(scene, /data-life-map-production-world="true"/)
  assert.match(scene, /data-life-map-ground="none"/)
})

test('semantic search and visible Memory Stars converge on the same authoritative selection transaction', () => {
  assert.match(navigator, /requestLifeMapSelection\(node\.id, source\)/)
  assert.match(selectionBroker, /window\.dispatchEvent\(new CustomEvent<LifeMapSelectionDetail>/)
  assert.match(scene, /window\.addEventListener\(LIFE_MAP_SELECTION_EVENT, handler\)/)
  assert.match(scene, /const detail = readLifeMapSelection\(event\)/)
  assert.match(scene, /const node = nodes\.find\(\(candidate\) => candidate\.id === detail\.nodeId\)/)
  assert.match(scene, /if \(node\) selectNode\(node\)/)
  assert.match(scene, /name=\{`life-map-memory-star-\$\{node\.id\}`\}/)
  assert.match(scene, /onClick=\{\(event\) => \{ event\.stopPropagation\(\); onSelect\(node\); \}\}/)
  assert.doesNotMatch(navigator, /life-map-world-label|owner\.click\(\)|activateWorldLabel/)
})

test('AAA overview composition is a layered galaxy with data-derived regions instead of a flat graph or terrain owner', () => {
  assert.match(scene, /function StellarDepthField/)
  assert.match(scene, /depthSpan=\{30\} zOffset=\{-2\}/)
  assert.match(scene, /depthSpan=\{58\} zOffset=\{-24\}/)
  assert.match(scene, /depthSpan=\{88\} zOffset=\{-58\}/)
  assert.match(scene, /<LivingGalaxyField tier=\{tier\}/)
  assert.match(scene, /function OverviewRegions/)
  assert.match(scene, /visualRole: "data-derived-personal-universe-geography"/)
  assert.match(scene, /pointWallpaper: false, graphEdges: false/)
  assert.match(scene, /function PortraitOverviewDepth/)
  assert.match(scene, /portraitAuthority: portrait \? "v285-vertical-territory-composition" : "desktop-v284-archipelago-composition"/)
  assert.match(scene, /function Constellations\(\) \{ return <group name="life-map-constellations" visible=\{false\}/)
  assert.doesNotMatch(scene, /LivingMemoryGeography|memoryValley|ChapterTerritories|lifeMapTerrainHeight|life-map-anchored-paths/)
})

test('Memory Stars remain stellar and interaction geometry remains visually invisible', () => {
  assert.match(scene, /function MemoryStar/)
  assert.match(scene, /visualAuthority: "stellar-memory-not-node-graph"/)
  assert.match(scene, /stellarMorphology: "point-photosphere-layered-corona-no-visible-sphere"/)
  assert.match(scene, /const photosphere = useMemo\(\(\) => makeDiscTexture\(5\.4, true\), \[\]\)/)
  assert.match(scene, /<sprite scale=\{\[outer \* 1\.24, outer, 1\]\}>/)
  assert.match(scene, /<sprite scale=\{\[mid \* 1\.10, mid, 1\]\}>/)
  assert.match(scene, /<sprite scale=\{\[hot, hot, 1\]\}>/)
  assert.match(scene, /<sphereGeometry args=\{\[\.30, 8, 6\]\} \/>/)
  assert.match(scene, /<meshBasicMaterial transparent opacity=\{0\} depthWrite=\{false\} colorWrite=\{false\} \/>/)
  assert.doesNotMatch(scene, /function MemoryLens|weathered-memory-outcrop|grounded-semantic-outcrops/)
})

test('selected travel keeps real volumetric depth through departure travel approach and arrival', () => {
  assert.match(scene, /const PHASE_MS = \{ departure: 900, travel: 1500, approach: 2200 \}/)
  assert.match(scene, /setPhase\("departure"\)/)
  assert.match(scene, /setPhase\("travel"\)/)
  assert.match(scene, /setPhase\("approach"\)/)
  assert.match(scene, /setPhase\("arrival"\)/)
  assert.match(scene, /function SelectedTravelWeather/)
  assert.match(scene, /life-map-departure-selected-memory-volumetric-bridge/)
  assert.match(scene, /visualRole: "departure-selected-memory-volumetric-bridge", pointWallpaper: false, journeyPhase: "departure"/)
  for (const seed of ['11.37', '12.11', '12.83', '13.47']) assert.match(scene, new RegExp(`seed=\\{${seed.replace('.', '\\.') }\\}`))
  assert.match(scene, /function SelectedMemoryFormation/)
  assert.match(scene, /function SelectedMemoryDust/)
  assert.match(scene, /const distance = phase === "departure" \? 21 : phase === "travel" \? 16\.5 : phase === "approach" \? 11\.2/)
})

test('responsive and recovery behavior preserve the same journey without hiding truth', () => {
  assert.match(scene, /const portrait = size\.height > size\.width/)
  assert.match(scene, /if \(reducedMotion\) \{ camera\.position\.copy\(position\); look\.current\.copy\(target\); \}/)
  assert.match(scene, /@media\(max-width:700px\)/)
  assert.match(scene, /@media\(prefers-reduced-motion:reduce\)/)
  assert.match(scene, /@media\(forced-colors:active\)/)
  assert.match(scene, /webglcontextlost/)
  assert.match(scene, /webglcontextrestored/)
  assert.match(scene, /Your selected memory, privacy state, and return position remain preserved\./)
  assert.match(scene, /Open semantic overview/)
})
