import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = process.cwd()
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

const legacyControls = read('src/spatial/lifemap/LifeMapDeepLinkControls.tsx')
const canonical = read('src/spatial/lifemap/SpatialLifeMapCanonical.tsx')
const adaptive = read('src/components/lifemap/AdaptiveLifeMapScene.tsx')
const shell = read('src/spatial/world/UraiWorldShell.tsx')
const selectedCinematic = read('src/spatial/world/lifeMapSelectedCinematic.css')
const proof = read('../scripts/capture-continuous-spatial-proof.mjs')

test('canonical Life Map has one selected-memory owner in the route DOM overlay', () => {
  assert.match(canonical, /<LifeMapRouteBoundary \/>/)
  assert.match(canonical, /<Suspense/)
  assert.match(canonical, /data-selected-memory-owner="spatial-lens-only"/)
  assert.doesNotMatch(canonical, /LifeMapDeepLinkControls|urai-lifemap-deep-link-controls/)
  assert.match(adaptive, /className="life-map-memory-portals"/)
  assert.match(adaptive, /data-life-map-selected-actions-owner="route-dom-overlay"/)
  assert.match(adaptive, /onClick=\{\(\) => enterFocus\(selectedNode\)\}/)
  assert.match(adaptive, /onClick=\{\(\) => enterReplay\(selectedNode\)\}/)
  assert.doesNotMatch(adaptive, /<Html distanceFactor=\{8\.2\}/)
})

test('selected-memory identity and Focus Replay destinations remain owned by the spatial scene', () => {
  assert.match(adaptive, /function safeToken/)
  assert.match(adaptive, /slice\(0, 120\)/)
  assert.match(adaptive, /const queryNodeId = safeToken\(params\.get\("node"\) \|\| params\.get\("nodeId"\) \|\| params\.get\("memoryId"\)\)/)
  assert.match(adaptive, /const manifestId = safeToken\(params\.get\("manifestId"\), DEFAULT_MANIFEST_ID\)/)
  assert.match(adaptive, /next\.set\("memoryId", node\.id\)/)
  assert.match(adaptive, /next\.set\("manifestId", manifestId\)/)
  assert.match(adaptive, /next\.set\("node", node\.id\)/)
  assert.match(adaptive, /next\.set\("returnNode", node\.id\)/)
  assert.match(adaptive, /next\.set\("lifeMapOrigin"/)
  assert.match(adaptive, /return `\/\$\{route\}\?\$\{next\.toString\(\)\}`/)
  assert.match(adaptive, />Enter Focus<\/button>/)
  assert.match(adaptive, />Replay<\/button>/)
})

test('Overview preserves identity while suppressing selected spatial portals', () => {
  assert.match(adaptive, /const overviewRequested = params\.get\("overview"\) === "1"/)
  assert.match(adaptive, /overviewRequested \? null : queryNodeId/)
  assert.match(adaptive, /\{selectedNode \? \(/)
  assert.match(adaptive, /className="life-map-memory-portals"/)
})

test('legacy selected-memory card remains unmounted and cannot compete visually', () => {
  assert.match(legacyControls, /data-testid="urai-lifemap-selected-memory-controls"/)
  assert.match(legacyControls, /Continue directly into this memory/)
  assert.doesNotMatch(canonical, /<LifeMapDeepLinkControls \/>/)
  assert.doesNotMatch(canonical, /import LifeMapDeepLinkControls/)
})

test('selected mode raises the spatial realm and keeps one route-owned action surface inside desktop and mobile viewports', () => {
  assert.match(shell, /import '\.\/lifeMapSelectedCinematic\.css'/)
  assert.match(selectedCinematic, /data-life-map-mode='selected'/)
  assert.match(selectedCinematic, /> \.life-map-independent-realm/)
  assert.match(selectedCinematic, /z-index: 70/)
  assert.match(selectedCinematic, /data-life-map-authored-universe='primary'/)
  assert.match(selectedCinematic, /opacity: \.04 !important/)
  assert.match(adaptive, /data-life-map-selected-actions-owner="route-dom-overlay"/)
  assert.doesNotMatch(adaptive, /<Html distanceFactor=\{8\.2\}/)
  assert.match(selectedCinematic, /\.life-map-memory-portals/)
  assert.match(selectedCinematic, /z-index: 2147482000/)
  assert.match(selectedCinematic, /isolation: isolate/)
  assert.match(selectedCinematic, /pointer-events: auto !important/)
  assert.match(selectedCinematic, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
  assert.match(selectedCinematic, /position: fixed/)
  assert.match(selectedCinematic, /left: max\(20px, env\(safe-area-inset-left\)\)/)
  assert.match(selectedCinematic, /right: max\(20px, env\(safe-area-inset-right\)\)/)
  assert.match(selectedCinematic, /top: clamp\(450px, 62svh, 660px\)/)
  assert.match(selectedCinematic, /width: auto/)
  assert.match(selectedCinematic, /max-width: 560px/)
  assert.match(selectedCinematic, /transform: none/)
  assert.match(selectedCinematic, /min-height: 52px/)
  assert.match(selectedCinematic, /@media \(max-width: 760px\)[\s\S]*left: max\(12px, env\(safe-area-inset-left\)\)/)
  assert.match(selectedCinematic, /@media \(max-width: 760px\)[\s\S]*right: max\(12px, env\(safe-area-inset-right\)\)/)
  assert.match(selectedCinematic, /@media \(max-width: 760px\)[\s\S]*top: clamp\(400px, 62svh, 590px\)/)
  assert.match(selectedCinematic, /@media \(max-width: 760px\)[\s\S]*min-width: 48px/)
  assert.match(selectedCinematic, /@media \(max-width: 760px\)[\s\S]*min-height: 52px !important/)
  assert.match(selectedCinematic, /@media \(max-width: 760px\)[\s\S]*pointer-events: auto !important/)
  assert.match(selectedCinematic, /@media \(max-width: 760px\)[\s\S]*touch-action: manipulation/)
  assert.match(adaptive, /data-life-map-overview-list="true"/)
  assert.match(adaptive, /data-life-map-selected-actions="true"/)
  assert.match(adaptive, /data-life-map-route-actions="true"/)
  assert.match(selectedCinematic, /data-life-map-mode='selected'[\s\S]*data-life-map-overview-list='true'[\s\S]*display: none !important/)
  assert.doesNotMatch(selectedCinematic, /data-life-map-mode='selected'[\s\S]*\.life-map-accessibility-menu > div[\s\S]*display: none !important/)
})

test('schema-7 selected route requires visible spatial Focus and Replay portals', () => {
  assert.match(proof, /id: 'life-map-selected'/)
  assert.match(proof, /getByRole\('button', \{ name: 'Enter Focus' \}\)/)
  assert.match(proof, /getByRole\('button', \{ name: 'Replay' \}\)/)
  assert.match(proof, /selectedMemoryControlsVisible/)
  assert.match(proof, /replayControlVisible/)
})
