import assert from 'node:assert/strict'
import { test } from 'node:test'
import fs from 'node:fs'

const page = fs.readFileSync(new URL('../src/app/life-map/page.tsx', import.meta.url), 'utf8')
const canonical = fs.readFileSync(new URL('../src/spatial/lifemap/SpatialLifeMapCanonical.tsx', import.meta.url), 'utf8')
const boundary = fs.readFileSync(new URL('../src/components/lifemap/LifeMapRouteBoundary.tsx', import.meta.url), 'utf8')
const source = fs.readFileSync(new URL('../src/components/lifemap/AdaptiveLifeMapScene.tsx', import.meta.url), 'utf8')
const convergenceCss = fs.readFileSync(new URL('../src/spatial/world/lifeMapConvergence.css', import.meta.url), 'utf8')
const interactionCss = fs.readFileSync(new URL('../src/spatial/world/lifeMapIndependentInteraction.css', import.meta.url), 'utf8')
const eventSource = fs.readFileSync(new URL('../src/components/lifemap/useLifeMapEvents.ts', import.meta.url), 'utf8')

test('LifeMap route uses the final canonical adaptive scene chain', () => {
  assert.match(page, /SpatialLifeMapCanonical/, 'Life Map route must render SpatialLifeMapCanonical.')
  assert.doesNotMatch(page, /RealLifeMapGalaxy|LifeMapScene/, 'Life Map route must not revert to retired direct owners.')
  assert.match(canonical, /LifeMapRouteBoundary/, 'Canonical owner must keep the route boundary.')
  assert.match(boundary, /AdaptiveLifeMapScene/, 'Route boundary must render the adaptive R3F scene.')
})

test('AdaptiveLifeMapScene preserves authored memory artifacts and selected-memory camera travel', () => {
  assert.ok(source.includes('useLifeMapEvents()'), 'Life Map must load private or explicit sample-backed memory nodes.')
  assert.ok(source.includes('selectedId, setSelectedId'), 'Life Map must preserve selected memory state.')
  assert.ok(source.includes('cameraForNode(node)'), 'Life Map must preserve selected-memory camera intent.')
  assert.ok(source.includes('<MemoryArtifact'), 'Life Map must render interactive authored memory artifacts.')
  assert.ok(source.includes('createMemorySurface'), 'Memory artifacts must carry meaningful deterministic visual surfaces.')
  assert.ok(source.includes('setCameraIntent(cameraForNode(node))'), 'Selecting a memory must move the camera toward it.')
  assert.ok(source.includes('THREE.MathUtils.smootherstep'), 'Camera travel must use authored easing rather than an abrupt fixed jump.')
  assert.ok(source.includes('lifeMapOrigin'), 'Focus and Replay must preserve the camera origin for return.')
})

test('LifeMap memory surfaces scale by quality and state without leaking replaced textures', () => {
  assert.ok(source.includes('function createMemorySurface(node: LifeMapNode, resolution: number)'), 'Memory surfaces must accept an explicit allocation size.')
  assert.ok(source.includes('const designScale = resolution / 768'), 'Scaled surfaces must preserve the authored 768-coordinate drawing system.')
  assert.ok(source.includes('ctx.scale(designScale, designScale)'), 'The 2D drawing context must be scaled rather than rewriting art coordinates.')
  assert.match(source, /selected\s*\?\s*profile\.tier === "high"\s*\?\s*512\s*:\s*384/, 'Only selected memories may receive the high-resolution profile allocation.')
  assert.match(source, /overview\s*\?\s*profile\.tier === "high"\s*\?\s*128\s*:\s*96/, 'Overview memories must use small textures.')
  assert.match(source, /related\s*\?\s*profile\.tier === "high"\s*\?\s*224\s*:\s*160/, 'Related memories must use medium textures.')
  assert.match(source, /:\s*80;\s*const \[texture, setTexture\] = useState<THREE\.CanvasTexture \| null>\(null\)/, 'Non-related memories must use the smallest allocation before commit-phase texture state.')
  assert.ok(source.includes('const nextTexture = createMemorySurface(node, textureResolution)'), 'Texture creation must occur inside the committed effect lifecycle.')
  assert.ok(source.includes('setTexture(nextTexture)'), 'Committed textures must enter React state only after creation.')
  assert.ok(source.includes('return () => nextTexture?.dispose()'), 'Every replaced or unmounted CanvasTexture must be disposed.')
  assert.doesNotMatch(source, /useMemo\(\(\) => createMemorySurface/, 'CanvasTexture allocation must never occur during render.')
  assert.doesNotMatch(source, /canvas\.width\s*=\s*768|canvas\.height\s*=\s*768/, 'The active owner must not eagerly allocate 768px textures for every memory.')
})

test('LifeMap temporal paths use declarative R3F geometry ownership', () => {
  assert.ok(source.includes('<tubeGeometry args={[curve, 72, active ? 0.012 : 0.005, 6, false]} />'), 'Temporal path geometry must be declarative so R3F owns disposal.')
  assert.doesNotMatch(source, /new THREE\.TubeGeometry/, 'TubeGeometry must not be allocated during React render.')
  assert.doesNotMatch(source, /tube\.dispose\(\)/, 'Manual disposal must not compete with declarative R3F ownership.')
})

test('LifeMap memories route into Focus and Replay with selected identity', () => {
  assert.ok(source.includes('identityHref("focus", selectedNode)'), 'Life Map must expose Focus entry.')
  assert.ok(source.includes('identityHref("replay", selectedNode)'), 'Life Map must expose Replay entry.')
  assert.ok(source.includes('next.set("memoryId", node.id)'), 'Focus and Replay must carry selected memory identity.')
  assert.ok(source.includes('next.set("manifestId", manifestId)'), 'Focus and Replay must carry manifest identity.')
  assert.ok(source.includes('next.set("node", node.id)'), 'Focus and Replay must preserve node identity.')
  assert.ok(source.includes('next.set("returnNode", node.id)'), 'Focus and Replay must preserve the exact return node.')
  assert.ok(source.includes('router.replace(`/life-map?${next.toString()}`'), 'Selection must remain inside Life Map before explicit navigation.')
})

test('LifeMap visual language is layered, adaptive, mobile-safe, and not primitive-only', () => {
  assert.ok(canonical.includes('lifeMapAssets.primary'), 'Life Map must use the registered primary asset stack.')
  assert.ok(canonical.includes('assetCssStack'), 'Life Map must render the canonical asset stack.')
  assert.ok(source.includes('<Canvas'), 'Life Map must keep the true R3F canvas.')
  assert.ok(source.includes('useAdaptiveSpatialQuality'), 'Life Map must adapt rendering quality and reduced motion.')
  assert.ok(source.includes('<ContinuityNexus'), 'Life Map must use an asymmetric continuity structure rather than the Home Orb.')
  assert.ok(source.includes('<ChapterRegions'), 'Life Map must render chapter or era regions.')
  assert.ok(source.includes('<GoalMonuments'), 'Life Map must establish far-field future structures.')
  assert.ok(source.includes('<PrivateVaults'), 'Life Map must represent private protected regions.')
  assert.ok(source.includes('<EmotionalWeather'), 'Life Map must represent emotional atmosphere spatially.')
  assert.ok(source.includes('<ForegroundDepthCrossings'), 'Life Map must establish foreground parallax and scale.')
  assert.ok(source.includes('life-map-parallax-layer'), 'Life Map must establish multiple depth fields.')
  assert.ok(source.includes('node.type === "relationship"'), 'Relationship memories must have a distinct internal visual language.')
  assert.ok(source.includes('node.type === "ritual"'), 'Ritual memories must have a distinct internal visual language.')
  assert.ok(source.includes('node.type === "recovery"'), 'Recovery memories must have a distinct internal visual language.')
  assert.doesNotMatch(source, /function LifeCore|<icosahedronGeometry|function NodeGeometry/, 'Retired white life-core and primitive-only node grammar must not return.')
  assert.match(convergenceCss, /100svh/, 'Life Map must own the full viewport.')
  assert.match(convergenceCss, /@media \(max-width: 430px\)/, 'Life Map must preserve an explicit narrow-phone composition.')
  assert.match(convergenceCss, /prefers-reduced-motion: reduce/, 'Life Map must preserve a reduced-motion equivalent.')
})

test('LifeMap wheel input, independent controls, and WebGL lifecycle remain production-safe', () => {
  const canvasOpeningTag = source.match(/<Canvas\b[\s\S]*?>/)?.[0] ?? ''
  assert.ok(canvasOpeningTag, 'Life Map must expose one stable Canvas opening tag.')
  assert.ok(source.includes('addEventListener("wheel", onWheel, { passive: false })'), 'Wheel zoom must use an explicit non-passive native listener.')
  assert.ok(source.includes('isLifeMapUiTarget(event.target)'), 'Camera handlers must exempt semantic Life Map controls.')
  assert.ok(source.includes('.life-map-accessibility-menu, .life-map-recovery, .life-map-memory-portals'), 'All scrollable and actionable overlays must be outside camera gesture ownership.')
  assert.doesNotMatch(source, /onWheel=\{onWheel\}/, 'React passive wheel ownership must not return.')
  assert.doesNotMatch(canvasOpeningTag, /key=\{/, 'Adaptive quality must not recreate the Canvas through a React key.')
  assert.ok(source.includes('webglcontextlost'), 'Life Map must handle WebGL context loss.')
  assert.ok(source.includes('webglcontextrestored'), 'Life Map must handle WebGL context restoration.')
  assert.ok(source.includes('data-webgl-state={webglState}'), 'Life Map must expose recovery state for browser proof.')
  assert.ok(source.includes('Life Map protected mode'), 'Context loss must preserve an operable semantic experience.')
  assert.match(interactionCss, /\.life-map-canvas[\s\S]*touch-action:\s*none/, 'Camera gestures must stay on the visual field.')
  assert.match(interactionCss, /\.life-map-accessibility-menu[\s\S]*touch-action:\s*pan-y/, 'The non-Orb controls layer must remain independently scrollable.')
  assert.match(interactionCss, /life-map-whisper[\s\S]*display:\s*block\s*!important/, 'Life Map narration must override obsolete route-level suppression.')
  assert.ok(source.includes('data-life-map-whisper="true"'), 'Narration must expose the exact override marker and live-region owner.')
  assert.ok(source.includes('event.stopImmediatePropagation()'), 'Life Map Escape must stop the shell listener on the same event.')
  assert.ok(source.includes('addEventListener("keydown", onKeyDown, true)'), 'Life Map Escape must capture before the shell bubble listener.')
})

test('LifeMap never lets sample data impersonate private memory', () => {
  assert.ok(source.includes('data-life-map-source={usingSeedData ? "explicit-sample" : "private"}'))
  assert.ok(source.includes('Sample constellation · not your memories'))
  assert.ok(source.includes('error ? usingSeedData ? "Protected sample field" : "Private constellation unavailable"'), 'Unavailable private data must never be described as sample data.')
  assert.ok(eventSource.includes('explicitDemoEnabled'))
  assert.ok(eventSource.includes('sourceMode: LifeMapSourceMode'))
  assert.ok(eventSource.includes('"explicit-demo"'))
  assert.ok(eventSource.includes('"signed-out"'))
  assert.ok(eventSource.includes('"private"'))
})
