import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const cosmic = fs.readFileSync(new URL('../src/components/lifemap/CosmicComposedLifeMapScene.tsx', import.meta.url), 'utf8')
const boundary = fs.readFileSync(new URL('../src/components/lifemap/LifeMapRouteBoundary.tsx', import.meta.url), 'utf8')

test('canonical Life Map overview is framed as a deep stellar personal universe rather than terrain or graph grammar', () => {
  assert.match(boundary, /CosmicComposedLifeMapScene/)
  assert.match(cosmic, /data-life-map-visual-authority="v260-deep-stellar-personal-universe"/)
  assert.match(cosmic, /data-life-map-art-revision="v279-departure-volumetric-bridge"/)
  assert.match(cosmic, /data-life-map-overview-authority="v280-data-derived-personal-universe-regions"/)
  assert.match(cosmic, /data-life-map-overview-polish="v281-literal-pixel-authored-geography"/)
  assert.match(cosmic, /data-life-map-landmark-revision="v282-authored-celestial-landmarks"/)
  assert.match(cosmic, /data-life-map-landmark-polish="v283-volumetric-celestial-islands"/)
  assert.match(cosmic, /data-life-map-landmark-acceptance="v284-stellar-memory-archipelagos"/)
  assert.match(cosmic, /data-life-map-portrait-overview="v285-vertical-territory-composition"/)
  assert.match(cosmic, /life-map-overview-personal-universe-regions/)
  assert.match(cosmic, /data-derived-personal-universe-geography/)
  assert.match(cosmic, /node\.eraId \|\| node\.clusterId \|\| node\.type/)
  assert.match(cosmic, /data-life-map-ground="none"/)
  assert.match(cosmic, /life-map-deep-space/)
  assert.match(cosmic, /life-map-deep-stellar-field/)
  assert.match(cosmic, /life-map-memory-stars/)
  assert.match(cosmic, /life-map-constellations/)
  assert.match(cosmic, /life-map-nebula-veil-/)
  assert.match(cosmic, /life-map-portrait-overview-depth/)
  assert.match(cosmic, /portrait-only-asymmetric-volumetric-depth/)
  assert.match(cosmic, /pointWallpaper: false/)
  assert.match(cosmic, /graphEdges: false/)
  assert.match(cosmic, /v260-no-explicit-graph-edges/)
  assert.match(cosmic, /stellar-memory-not-node-graph/)
  assert.match(cosmic, /spriteMaterial/)
  assert.doesNotMatch(cosmic, /Sparkles/)
  assert.doesNotMatch(cosmic, /LivingMemoryGeography|ChapterTerritories|lifeMapTerrainHeight|lifeMapSpatialLayout|weathered-valley-floor|worn-lineage-path/)
  assert.doesNotMatch(cosmic, /<Line\b|lineSegments|dodecahedronGeometry|icosahedronGeometry/)
  assert.doesNotMatch(cosmic, /scale=\{active \? 10\.8|scale=\{active \? 5\.4/)
})

test('V281 overview camera is tighter and independent from selected-memory travel origin', () => {
  assert.match(cosmic, /const portrait = size\.height > size\.width/)
  assert.match(cosmic, /const overview = new THREE\.Vector3\(0, portrait \? \.65 : 1\.55, portrait \? 18\.5 : 19\.5\)/)
  assert.match(cosmic, /targetOverview = new THREE\.Vector3\(0, portrait \? -\.45 : \.10, portrait \? -26 : -25\)/)
  assert.match(cosmic, /fov: portrait \? 42 : 44/)
  assert.match(cosmic, /travelOrigin\s*=\s*new THREE\.Vector3\(0, portrait \? 1\.2 : 2\.7, portrait \? 29 : 25\.5\)/)
  assert.match(cosmic, /dir = travelOrigin\.clone\(\)\.sub\(target\)\.normalize\(\)/)
  assert.match(cosmic, /pointer\.x \* 1\.1/)
  assert.match(cosmic, /pointer\.y \* \.45/)
})

test('V284 overview memory destinations remain stellar archipelagos with volumetric authored hierarchy', () => {
  assert.match(cosmic, /const overviewBoost = overview \? 1\.48 : 1/)
  assert.match(cosmic, /const outer = \(active \? 1\.08 : related \? \.82 : \.74\) \* overviewBoost/)
  assert.match(cosmic, /const mid = \(active \? \.52 : related \? \.40 : \.36\) \* overviewBoost/)
  assert.match(cosmic, /const hot = \(active \? \.20 : related \? \.17 : \.16\) \* \(overview \? 1\.24 : 1\)/)
  assert.match(cosmic, /active \? \.20 : related \? \.19 : overview \? \.25 : \.17/)
  assert.match(cosmic, /active \? \.50 : related \? \.44 : overview \? \.48 : \.40/)
  assert.match(cosmic, /active \? \.94 : related \? \.91 : overview \? \.94 : \.90/)
  assert.match(cosmic, /active \? \.24 : related \? \.07 : overview \? \.036 : \.024/)
  assert.match(cosmic, /overviewWeather = phase === "overview" \? \.32 : \.055/)
  assert.match(cosmic, /const approachBoost = active && !overview \? 5\.1 : 1/)
  assert.match(cosmic, /scale=\{\[1\.28, 1\.28, 1\.28\]\}/)
  assert.match(cosmic, /life-map-v283-celestial-island-/)
  assert.match(cosmic, /data-derived-volumetric-celestial-island/)
  assert.match(cosmic, /v284-stellar-memory-archipelago/)
  assert.match(cosmic, /life-map-v284-archipelago-fragment-/)
  assert.match(cosmic, /life-map-v284-territory-stars-/)
  assert.match(cosmic, /data-derived-stellar-territory/)
  assert.match(cosmic, /interactionOwner: false/)
  assert.match(cosmic, /raycast=\{\(\) => null\}/)
  assert.match(cosmic, /buildCelestialCanopyGeometry/)
  assert.match(cosmic, /computeVertexNormals\(\)/)
  assert.match(cosmic, /fog attach="fog" args=\{\["#020611", 78, 170\]\}/)
  assert.doesNotMatch(cosmic, /phase === "arrival" \? 6\.1/)
})

test('V285 portrait overview expands data-derived territory hierarchy vertically without returning to wallpaper or monolithic blobs', () => {
  assert.match(cosmic, /const \{ size \} = useThree\(\);\n  const portrait = size\.height > size\.width;/)
  assert.match(cosmic, /const portraitBand = portrait \? \(index - 2\.5\) \* 2\.65/)
  assert.match(cosmic, /rawCenter\[0\] \* \(portrait \? \.34 : \.54\)/)
  assert.match(cosmic, /rawCenter\[1\] \* \(portrait \? \.72 : \.52\)/)
  assert.match(cosmic, /portraitAuthority: portrait \? "v285-vertical-territory-composition"/)
  assert.match(cosmic, /const count = 132/)
  assert.match(cosmic, /Math\.min\(\.28, strength \* \.16\)/)
  assert.match(cosmic, /opacity=\{\.90\}/)
  assert.match(cosmic, /spread=\{region\.spread \* \(portrait \? 1\.48 : 1\.30\)\}/)
  assert.match(cosmic, /data-life-map-galaxy-polish="v290-recognizable-spiral-living-galaxy-no-shards"/)
  const overview = cosmic.slice(cosmic.indexOf('function OverviewRegions'), cosmic.indexOf('function SelectedTravelWeather'))
  assert.doesNotMatch(overview, /<CelestialRegionCanopy/, 'rejected faceted canopy forms must not own the overview')
  assert.match(cosmic, /life-map-v290-living-galaxy-overview/)
  assert.doesNotMatch(cosmic, /const count = 500|const count = 1000/)
})

test('selected-memory travel remains spatial, volumetric, and celestial until Focus or Replay', () => {
  assert.match(cosmic, /phase === "departure" \? 21/)
  assert.match(cosmic, /phase === "travel" \? 16\.5/)
  assert.match(cosmic, /phase === "approach" \? 11\.2/)
  assert.match(cosmic, /portrait \? 8\.6 : 7\.2/)
  assert.match(cosmic, /portrait \? phase === "arrival" \? 50 : 56 : phase === "arrival" \? 40 : 49/)
  assert.match(cosmic, /Approaching memory/)
  assert.match(cosmic, /Memory selected/)
  assert.match(cosmic, /life-map-selected-memory-dust/)
  assert.match(cosmic, /life-map-selected-travel-weather/)
  assert.match(cosmic, /selected-memory-asymmetric-volumetric-depth/)
  assert.match(cosmic, /journeyPhase: phase/)
  assert.match(cosmic, /phase === "departure" \? \.34 : phase === "travel" \? \.32 : phase === "approach" \? \.28 : \.22/)
  assert.match(cosmic, /life-map-v287-selected-memory-stellar-weather/)
  assert.match(cosmic, /v287-selected-memory-star-no-glass-shards/)
  assert.match(cosmic, /const scale = phase === "arrival" \? 1\.58 : phase === "approach" \? 1\.42 : phase === "travel" \? 1\.24 : 1\.06;/)
  assert.match(cosmic, /life-map-selected-memory-corona/)
  assert.match(cosmic, /life-map-selected-memory-inner-corona/)
  assert.match(cosmic, /life-map-selected-memory-photosphere/)
  assert.match(cosmic, /data-life-map-reference-depth="v292-bounded-selected-memory-star-preserved-galaxy-depth"/)
  assert.match(cosmic, /scale=\{\[96, 54\]\}/)
  assert.doesNotMatch(cosmic, /ArrivalSanctuary|IntimateMemoryChamber|memory chamber/)
})

test('portrait/mobile launch UI preserves the celestial viewport instead of recreating a terrain envelope', () => {
  assert.match(cosmic, /@media\(max-width:700px\)/)
  assert.match(cosmic, /\.life-map-thresholds\{bottom:max\(10px,env\(safe-area-inset-bottom\)\)!important/)
  assert.match(cosmic, /\.life-map-status\{top:max\(12px,env\(safe-area-inset-top\)\);right:12px\}/)
  assert.match(cosmic, /\.life-map-status small\{display:none\}/)
  assert.match(cosmic, /height:100svh/)
})

test('framing keeps reduced-motion, exact-head render proof, and semantic thresholds fail closed', () => {
  assert.match(cosmic, /prefers-reduced-motion:reduce/)
  assert.match(cosmic, /data-life-map-render-ready="false"/)
  assert.match(cosmic, /data-life-map-visible-anchors="0"/)
  assert.match(cosmic, /lifeMapRenderReady/)
  assert.match(cosmic, /lifeMapVisibleAnchors/)
  assert.match(cosmic, /gl\.info\.render\.calls > 0 && objects > 20 && anchors >= 8/)
  assert.match(cosmic, /className="life-map-thresholds"/)
  assert.match(cosmic, />Enter Focus</)
  assert.match(cosmic, />Replay</)
  assert.match(cosmic, /flex-direction:row!important/)
})
