import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const app = join(root, 'urai-tier1')
const page = readFileSync(join(app, 'src/app/location-map/page.tsx'), 'utf8')
const scene = readFileSync(join(app, 'src/spatial/places/LocationMapScene.tsx'), 'utf8')
const spatialWorld = readFileSync(join(app, 'src/spatial/places/LocationMapSpatialWorld.tsx'), 'utf8')
const wheelBridge = readFileSync(join(app, 'src/spatial/places/LocationMapNativeWheelBridge.tsx'), 'utf8')
const layer = readFileSync(join(app, 'src/app/UraiAutonomousV1Layer.tsx'), 'utf8')
const shell = readFileSync(join(app, 'src/spatial/world/UraiWorldShell.tsx'), 'utf8')
const css = readFileSync(join(app, 'src/spatial/places/location-map-scene.css'), 'utf8')
const depthCss = readFileSync(join(app, 'src/spatial/places/location-map-release-depth.css'), 'utf8')
const finalCss = readFileSync(join(app, 'src/spatial/places/location-map-r3f-final.css'), 'utf8')

assert.doesNotMatch(layer, /pathname\.startsWith\(["']\/location-map["']\)/, 'Legacy autonomous layer must not own Location Map.')
assert.match(shell, /world\.destination !== 'location-map'/, 'The shared persistent Orb must not compete with the route-owned Location Map world.')
assert.match(page, /listMemoryPlaces\(\{ source: 'demo' \}\)/, 'The static route must request only disclosed demo places.')
assert.match(page, /place\.privacyLevel === 'demo'/, 'The server boundary must reject non-demo places before serialization.')
assert.match(page, /location-map-r3f-final\.css/, 'The route must load the final R3F visual-owner convergence styles.')
assert.doesNotMatch(wheelBridge, /addEventListener\(['"]touch|addEventListener\(['"]pointer/, 'The native wheel bridge must not own touch camera state.')
assert.match(wheelBridge, /Touch drag and pinch are intentionally owned\s*only by LocationMapScene/, 'Touch ownership must remain explicit and single-owner.')
assert.match(scene, /data-location-map-owner="canonical-route"/, 'Location Map must identify its canonical route owner.')
assert.match(scene, /data-location-map-renderer="react-three-fiber-spatial-atlas"/, 'Location Map must identify the R3F terrain world as its canonical visual renderer.')
assert.match(scene, /LocationMapSpatialWorld/, 'Location Map must mount the route-owned true 3D atlas world.')
assert.match(scene, /data-spatial-fallback="retired"/, 'Legacy layered camera geometry must be explicitly retired from visual ownership.')
assert.match(scene, /privacyMode/, 'Private-mode query state must be preserved.')
assert.match(scene, /entryPortal/, 'Entry portal query state must be preserved.')
assert.match(scene, /cameraCheckpoint/, 'Camera checkpoint query state must be preserved.')
assert.match(scene, /placeId/, 'Selected place identity must be durable in route state.')
assert.match(scene, /setActiveIndex\(index\)/, 'URL-restored place selection must synchronize keyboard navigation state.')
assert.match(scene, /event\.stopPropagation\(\)/, 'Beacon arrow navigation must not bubble into atlas camera controls.')
assert.match(scene, /Disclosed sample places/, 'Fallback demo data must be explicitly disclosed.')
assert.match(scene, /no personal location history is displayed/i, 'Selected demo places must retain a truthful disclosure.')
assert.match(scene, /data-private-memory-mounted="false"/, 'Signed-out threshold must certify that private memory data is not mounted.')
assert.match(scene, /Open disclosed sample/, 'Demo places must require an explicit sample action.')
assert.match(scene, /USER_KEY/, 'Private atlas access must have an explicit authenticated-user boundary.')
assert.match(scene, /role="application"/, 'The visual atlas must expose a keyboard-operable interaction surface.')
assert.match(scene, /Escape/, 'Escape return behavior must remain documented and implemented.')
assert.match(scene, /aria-live="polite"/, 'Selection changes must be announced to assistive technology.')
assert.match(scene, /prefers-reduced-motion/, 'Reduced-motion mode must be detected.')
assert.match(css, /@media\s*\(prefers-reduced-motion:\s*reduce\)/, 'Reduced-motion styling must be present.')
assert.match(css, /\.locationAtlasBeacon/, 'Grounded semantic place controls must remain route-owned.')
assert.match(css, /@media\s*\(max-width:\s*620px\)/, 'Mobile composition must be intentional rather than desktop scaling.')
assert.match(spatialWorld, /@react-three\/fiber/, 'The final atlas world must use the canonical R3F runtime.')
assert.match(spatialWorld, /location-map-spatial-terrain/, 'The final atlas must own true three-dimensional terrain.')
assert.match(spatialWorld, /AtlasCameraRig/, 'Pan, focus and zoom state must drive a real 3D camera.')
assert.match(spatialWorld, /location-map-memory-route-thread/, 'Memory places must be embedded into the 3D geography with a route thread.')
assert.match(spatialWorld, /grounded-emotional-place-field/, 'Place markers must exist as world-space emotional fields, not poster pins.')
assert.match(finalCss, /locationAtlasWorldCanvas/, 'The R3F canvas must be the visible world layer.')
assert.match(finalCss, /locationAtlasStage::before[\s\S]*display:\s*none\s*!important/, 'Legacy CSS terrain planes must not compete with the true 3D world.')
assert.match(finalCss, /\.locationAtlasArt[\s\S]*opacity:\s*\.055/, 'Provider artwork may remain only as faint atmospheric support.')
assert.match(depthCss, /Route-owned terrain world/, 'Historical layered terrain remains documented as superseded fallback evidence.')

console.log('URAI canonical Location Map true 3D world contract passed.')
