import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const app = join(root, 'urai-tier1')
const page = readFileSync(join(app, 'src/app/location-map/page.tsx'), 'utf8')
const scene = readFileSync(join(app, 'src/spatial/places/LocationMapScene.tsx'), 'utf8')
const spatialWorld = readFileSync(join(app, 'src/spatial/places/LocationMapSpatialWorld.tsx'), 'utf8')
const wheelBridge = readFileSync(join(app, 'src/spatial/places/LocationMapNativeWheelBridge.tsx'), 'utf8')
const layer = readFileSync(join(app, 'src/app/UraiAutonomousV1Layer.tsx'), 'utf8')
const shell = readFileSync(join(app, 'src/spatial/world/UraiWorldShell.tsx'), 'utf8')
const css = readFileSync(join(app, 'src/spatial/places/location-map-scene.css'), 'utf8')
const depthCss = readFileSync(join(app, 'src/spatial/places/location-map-release-depth.css'), 'utf8')
const finalCss = readFileSync(join(app, 'src/spatial/places/location-map-r3f-final.css'), 'utf8')
const geographicBridgeCss = readFileSync(join(app, 'src/app/location-map/geographic-route-bridge.css'), 'utf8')
const verificationWorkflow = readFileSync(join(root, '.github/workflows/location-map-canonical-world-verify.yml'), 'utf8')
const browserAcceptance = readFileSync(join(root, 'tests/location-map-browser-acceptance-v2.spec.ts'), 'utf8')

assert.match(verificationWorkflow, /pull_request:\s*\n\s*branches:\s*\[main, repair\/release-closure-integration-20261007\]/, 'Canonical browser proof must run for donors to the sole controller as well as main.')
assert.doesNotMatch(verificationWorkflow.split('\njobs:')[0], /\bpaths(?:-ignore)?:/, 'Browser proof must not omit controller donors because of changed-path filters.')
assert.match(verificationWorkflow, /permissions:\s*\n\s*contents: read/, 'Browser verification must retain read-only repository authority.')
assert.doesNotMatch(verificationWorkflow, /contents: write|actions: write|id-token: write|\bsecrets\.|environment: production|firebase(?:-tools)?[^\n]*\bdeploy\b|gcloud[^\n]*\bdeploy\b/, 'Browser verification must not acquire credentials or deployment authority.')
assert.ok(verificationWorkflow.includes('EXACT_HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}'), 'Browser proof must bind the actual PR head rather than the merge ref.')
assert.equal(verificationWorkflow.match(/ref: \$\{\{ env\.EXACT_HEAD_SHA \}\}/g)?.length, 2, 'Both build and browser jobs must checkout the exact source head.')
assert.equal(verificationWorkflow.match(/test "\$\(git rev-parse HEAD\)" = "\$EXACT_HEAD_SHA"/g)?.length, 2, 'Both jobs must assert the checked-out source identity.')
assert.equal(verificationWorkflow.match(/persist-credentials: false/g)?.length, 2, 'Both jobs must discard checkout credentials.')
assert.equal(verificationWorkflow.match(/pnpm install --frozen-lockfile/g)?.length, 2, 'Both jobs must install frozen dependencies.')
assert.ok(verificationWorkflow.includes('pnpm exec playwright test tests/location-map-browser-acceptance-v2.spec.ts --fail-on-flaky-tests --config=playwright.config.ts --timeout=120000'), 'Browser proof must retain the strict actual acceptance command.')
assert.ok(verificationWorkflow.includes('name: location-map-browser-acceptance-${{ env.EXACT_HEAD_SHA }}'), 'Retained browser evidence must name the exact source head.')
for (const strictAssertion of [
  'expect(unexpectedConsoleErrors).toEqual([])',
  'expect(unexpectedPageErrors).toEqual([])',
  'expect(errors.consoleErrors).toEqual([])',
  'expect(errors.pageErrors).toEqual([])',
]) assert.ok(browserAcceptance.includes(strictAssertion), `Desktop and mobile browser proof must reject runtime errors: ${strictAssertion}`)

assert.doesNotMatch(layer, /pathname\.startsWith\(["']\/location-map["']\)/, 'Legacy autonomous layer must not own Location Map.')
assert.match(shell, /world\.destination !== 'location-map'/, 'The shared persistent Orb must not compete with the route-owned Location Map world.')
assert.match(page, /listMemoryPlaces\(\{ source: 'demo' \}\)/, 'The static route must request only disclosed demo places.')
assert.match(page, /place\.privacyLevel === 'demo'/, 'The server boundary must reject non-demo places before serialization.')
assert.match(page, /location-map-r3f-final\.css/, 'The route must load the final R3F visual-owner convergence styles.')
assert.doesNotMatch(wheelBridge, /addEventListener\(['"]touch|addEventListener\(['"]pointer/, 'The native wheel bridge must not own touch camera state.')
assert.match(wheelBridge, /Touch drag and pinch are intentionally owned\s*only by LocationMapScene/, 'Touch ownership must remain explicit and single-owner.')
assert.match(scene, /data-location-map-owner="canonical-route"/, 'Location Map must identify its canonical route owner.')
assert.match(scene, /data-location-map-renderer="react-three-fiber-spatial-atlas"/, 'Location Map must identify the R3F terrain world as its canonical visual renderer.')
assert.match(scene, /LocationMapSpatialWorld/, 'Location Map must mount the route-owned true 3D atlas world.')
assert.match(scene, /data-spatial-fallback="retired"/, 'Legacy layered camera geometry must be explicitly retired from visual ownership.')
assert.match(scene, /privacyMode/, 'Private-mode query state must be preserved.')
assert.match(scene, /entryPortal/, 'Entry portal query state must be preserved.')
assert.match(scene, /cameraCheckpoint/, 'Camera checkpoint query state must be preserved.')
assert.match(scene, /placeId/, 'Selected place identity must be durable in route state.')
assert.match(scene, /setActiveIndex\(index\)/, 'URL-restored place selection must synchronize keyboard navigation state.')
assert.match(scene, /event\.stopPropagation\(\)/, 'Beacon arrow navigation must not bubble into atlas camera controls.')
assert.match(scene, /Disclosed sample places/, 'Fallback demo data must be explicitly disclosed.')
assert.match(scene, /no personal location history is displayed/i, 'Selected demo places must retain a truthful disclosure.')
assert.match(scene, /data-private-memory-mounted="false"/, 'Signed-out threshold must certify that private memory data is not mounted.')
assert.match(scene, /Open disclosed sample/, 'Demo places must require an explicit sample action.')
assert.match(scene, /onAuthStateChanged\(getAuth\(app\)/, 'Private atlas access must have an explicit Firebase authenticated-user boundary.')
assert.match(scene, /setAccess\(user \? 'private' : 'threshold'\)/, 'Private atlas access must fail closed when no authenticated user exists.')
assert.match(scene, /role="application"/, 'The visual atlas must expose a keyboard-operable interaction surface.')
assert.match(scene, /Escape/, 'Escape return behavior must remain documented and implemented.')
assert.match(scene, /aria-live="polite"/, 'Selection changes must be announced to assistive technology.')
assert.match(scene, /prefers-reduced-motion/, 'Reduced-motion mode must be detected.')
assert.match(css, /@media\s*\(prefers-reduced-motion:\s*reduce\)/, 'Reduced-motion styling must be present.')
assert.match(css, /\.locationAtlasBeacon/, 'Grounded semantic place controls must remain route-owned.')
assert.match(css, /\.locationAtlasBeacon\[data-selected="true"\] \.locationAtlasBeaconLabel\s*\{[\s\S]*?opacity:\s*0;/, 'The selected beacon duplicate label must stay hidden so the canonical detail panel owns the selected-place title without viewport clipping.')
assert.match(geographicBridgeCss, /left:\s*50%;[\s\S]*?right:\s*auto;[\s\S]*?transform:\s*translateX\(-50%\)/, 'The optional geographic bridge must occupy the desktop center lane instead of overlapping the selected-place panel.')
assert.match(geographicBridgeCss, /@media \(max-width: 760px\)[\s\S]*?left:\s*auto;[\s\S]*?right:\s*0\.75rem;[\s\S]*?transform:\s*none;/, 'Mobile geographic bridge positioning must remain independently bounded.')
assert.match(css, /@media\s*\(max-width:\s*620px\)/, 'Mobile composition must be intentional rather than desktop scaling.')
assert.match(spatialWorld, /@react-three\/fiber/, 'The final atlas world must use the canonical R3F runtime.')
assert.match(spatialWorld, /location-map-spatial-terrain/, 'The final atlas must own true three-dimensional terrain.')
assert.match(spatialWorld, /AtlasCameraRig/, 'Pan, focus and zoom state must drive a real 3D camera.')
assert.match(spatialWorld, /location-map-memory-route-thread/, 'Memory places must be embedded into the 3D geography with a route thread.')
assert.match(spatialWorld, /grounded-emotional-place-field/, 'Place markers must exist as world-space emotional fields, not poster pins.')
assert.match(finalCss, /locationAtlasWorldCanvas/, 'The R3F canvas must be the visible world layer.')
assert.match(finalCss, /locationAtlasStage::before[\s\S]*display:\s*none\s*!important/, 'Legacy CSS terrain planes must not compete with the true 3D world.')
assert.match(finalCss, /\.locationAtlasArt[\s\S]*opacity:\s*\.055/, 'Provider artwork may remain only as faint atmospheric support.')
assert.match(depthCss, /Route-owned terrain world/, 'Historical layered terrain remains documented as superseded fallback evidence.')

console.log('URAI canonical Location Map true 3D world contract passed.')
