const assert = require('node:assert/strict')
const fs = require('node:fs')
const vm = require('node:vm')
const ts = require('typescript')
const source = fs.readFileSync(require('node:path').join(__dirname, '../src/spatial/world/worldEvents.ts'), 'utf8')
const fragment = source.slice(source.indexOf('function destinationRouteOwnerReady'), source.indexOf('function shouldBeginHomeAscent'))
const code = ts.transpileModule(fragment, { compilerOptions: { target: ts.ScriptTarget.ES2022 } }).outputText
let owners = []
const context = vm.createContext({ document: { querySelectorAll: () => owners }, window: { getComputedStyle: owner => owner.style } })
vm.runInContext(code, context)
const ready = () => context.destinationRouteOwnerReady({ destination: 'passport' })
const owner = (rects, visibility = 'visible', isConnected = true) => ({ isConnected, getClientRects: () => Array(rects).fill({}), style: { display: 'block', visibility } })
assert.equal(ready(), false)
owners = [owner(0)]; assert.equal(ready(), false)
owners = [owner(1, 'hidden')]; assert.equal(ready(), false)
owners = [owner(1, 'collapse')]; assert.equal(ready(), false)
owners = [owner(1, 'visible', false)]; assert.equal(ready(), false)
owners = [owner(0), owner(1)]; assert.equal(ready(), true)
assert.equal(context.destinationRouteOwnerReady({ destination: 'ground' }), true)
console.log('PASS: absent, hidden-layout, hidden-style, collapsed, detached, streamed-plus-visible, and unaffected other destination (7 cases).')
