import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(path, 'utf8')

test('persistent world navigation preserves canonical ownership and separate hit targets', () => {
  const gateway = read('src/spatial/world/GroundGateway.tsx')
  const controller = read('src/spatial/world/WorldTransitionController.tsx')
  const shell = read('src/spatial/world/UraiWorldShell.tsx')
  const home = read('src/app/HomeSpatialRuntimeLayer.tsx')
  const companion = read('src/spatial/world/PersistentWorldCompanion.tsx')
  const companionCss = read('src/spatial/world/persistentWorldCompanion.css')
  const worldNavigation = read('src/spatial/world/worldNavigation.css')
  const finalCss = read('src/app/native-doorway-final-fix.css')
  const ground = read('src/app/GroundSpatialWorldClean.tsx')
  const lifeMap = read('src/components/lifemap/AdaptiveLifeMapScene.tsx')
  const layout = read('src/app/layout.tsx')
  const visualAudit = read('../scripts/run-live-visual-audit-current.mjs')

  assert.match(controller, /beginTravelRef\.current\(request\)/)
  assert.doesNotMatch(controller, /\[beginTravel, clearTimer, router\]/)
  assert.match(controller, /import \{ useCallback, useEffect, useLayoutEffect, useRef \} from 'react'/)
  assert.match(controller, /useLayoutEffect\(\(\) => \{\n\s*const onTravel =/)
  assert.doesNotMatch(controller, /useEffect\(\(\) => \{\n\s*const onTravel =/)
  assert.match(controller, /event\.defaultPrevented/)
  assert.match(controller, /currentWorld\.destination === 'life-map'/)
  assert.match(controller, /Life Map owns its two-stage Escape contract/)
  assert.match(gateway, /requestUraiWorldTravel\(/)
  assert.match(gateway, /destination: 'infrastructure-hub'/)
  assert.doesNotMatch(gateway, /router\.push\(['"]\/ground/)
  assert.doesNotMatch(gateway, /fallbackTimer/)

  assert.match(home, /onOrbOpen=\{requestUraiWorldOrbOpen\}/)
  assert.doesNotMatch(home, /urai-home-spatial-orb-trigger/)
  assert.doesNotMatch(home, /urai-home-spatial-runtime-orb/)
  assert.match(companion, /SECONDARY_DESTINATIONS/)
  assert.match(companion, /aria-label="Return through the world"/)
  assert.match(companionCss, /\.urai-world-companion__orb \{[\s\S]*width: 64px;[\s\S]*height: 64px;/)
  assert.match(companionCss, /bottom: max\(14px, env\(safe-area-inset-bottom\)\)/)
  assert.match(shell, /world\.destination !== 'life-map'/)
  assert.match(shell, /showWorldCompanion \? <PersistentWorldCompanion \/> : null/)

  assert.match(finalCss, /\.urai-ground-gateway \{[\s\S]*z-index: 11 !important;[\s\S]*height: 80px !important/)
  assert.match(finalCss, /\.urai-home-spatial-runtime-layer \{[\s\S]*z-index: 9/)
  assert.match(finalCss, /height: 96px !important/)
  assert.match(worldNavigation, /@media \(max-width: 700px\)[\s\S]*\.urai-ground-gateway__surface[\s\S]*bottom: max\(72px, calc\(env\(safe-area-inset-bottom\) \+ 64px\)\)/)
  assert.doesNotMatch(ground, /padding-inline:12px 210px;scroll-padding-inline:12px 210px/)
  assert.match(ground, /padding-inline:max\(14px,env\(safe-area-inset-left\)\) max\(14px,env\(safe-area-inset-right\)\)/)
  assert.match(ground, /scroll-padding-inline-start:max\(14px,env\(safe-area-inset-left\)\)/)
  assert.match(ground, /scroll-padding-inline-end:max\(14px,env\(safe-area-inset-right\)\)/)

  assert.match(lifeMap, /identityHref\("focus", selectedNode\)/)
  assert.match(lifeMap, /identityHref\("replay", selectedNode\)/)
  assert.match(lifeMap, /data-home-companion-owned="false"/)
  assert.doesNotMatch(lifeMap, /Orb companion|PersistentWorldCompanion/)
  assert.doesNotMatch(layout, /LifeMapPersistentDoorways/)
  assert.doesNotMatch(layout, /data-urai-audit-action="life-map-focus"/)
  assert.doesNotMatch(layout, /data-urai-audit-action="life-map-replay"/)

  assert.match(visualAudit, /data-world-target=\\"focus\\"/)
  assert.match(visualAudit, /check\.name === 'life-map-to-focus'/)
  assert.match(visualAudit, /\.life-map-accessibility-menu/)
  assert.match(visualAudit, /The Quiet Reset/)
  assert.match(visualAudit, /focusTouchTarget/)
  assert.match(visualAudit, /semanticListHidden/)
  assert.match(visualAudit, /firstVisible\(page, check\.selectors\)/)
  assert.match(visualAudit, /Open Orb travel controls/)
  assert.match(visualAudit, /clickOrFollowHref\(page, found\.locator\)/)
  assert.match(visualAudit, /waitForURL\(\(url\) => url\.toString\(\)\.includes\(check\.expected\), \{ timeout: 7000 \}\)/)
})
