import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const boundary = read('../src/lib/server/provider-boundary.ts')
const openaiRoute = read('../src/app/api/urai/orb/openai/route.ts')
const openaiClient = read('../src/spatial/orb/openaiClient.ts')
const orbPanel = read('../src/spatial/orb/OrbConversationPanel.tsx')
const elevenlabs = read('../src/lib/server/elevenlabs-synthesis.ts')
const narratorClient = read('../src/spatial/narrator/elevenlabsClient.ts')
const narratorPlayback = read('../src/spatial/narrator/narratorPlayback.ts')
const narratorRoute = read('../src/app/api/urai/narrator/elevenlabs/route.ts')
const voiceRoute = read('../src/app/api/voice/elevenlabs/route.ts')

function compact(value) {
  return value.replace(/\s+/g, ' ')
}

test('provider boundary requires saved, fully enforced model consent and durable throttling', () => {
  assert.match(boundary, /explicitConsent/)
  assert.match(boundary, /users\/\$\{input\.uid\}\/privacyPolicy\/current/)
  assert.match(boundary, /mode !== 'granted'/)
  assert.match(boundary, /models\.modelContext !== true/)
  assert.match(boundary, /fully-enforced/)
  assert.match(boundary, /providerConnections\/\$\{input\.provider\}/)
  assert.match(boundary, /PROVIDER_PROCESSING_REVOKED/)
  assert.match(boundary, /runTransaction/)
  assert.match(boundary, /providerRateLimits/)
  assert.match(boundary, /providerTelemetry/)
  assert.doesNotMatch(boundary, /prompt:/i)
  assert.doesNotMatch(boundary, /generatedText/i)
})

test('OpenAI Orb is server-only, authenticated, moderated, non-stored, structured and cancellation-bounded', () => {
  assert.match(openaiRoute, /verifyFirebaseUser/)
  assert.match(openaiRoute, /authorizeExternalProviderRequest/)
  assert.match(openaiRoute, /consumeProviderRateLimit/)
  assert.match(openaiRoute, /process\.env\.OPENAI_API_KEY/)
  assert.match(openaiRoute, /https:\/\/api\.openai\.com\/v1\/moderations/)
  assert.match(openaiRoute, /omni-moderation-latest/)
  assert.match(openaiRoute, /https:\/\/api\.openai\.com\/v1\/responses/)
  assert.match(openaiRoute, /store: false/)
  assert.match(openaiRoute, /stream: true/)
  assert.match(openaiRoute, /safety_identifier/)
  assert.match(openaiRoute, /type: 'json_schema'/)
  assert.match(openaiRoute, /strict: true/)
  assert.match(openaiRoute, /response\.output_text\.delta/)
  assert.match(openaiRoute, /boundedAbortSignal/)
  assert.match(openaiRoute, /Cache-Control': 'private, no-store/)
  assert.doesNotMatch(openaiRoute, /console\.(log|info|error|warn)\([^)]*(message|context)/)
})

test('Orb client and UI keep provider consent off, preserve text equivalence, stop, mute, replay and truthful fallback', () => {
  assert.match(openaiClient, /getAuth\(app\)\.currentUser/)
  assert.match(openaiClient, /Authorization/)
  assert.match(openaiClient, /aiProcessingConsent: true/)
  assert.match(openaiClient, /deterministicOrbFallback/)
  assert.match(openaiClient, /buildOrbCompanionResponse/)
  assert.match(orbPanel, /useState\(false\)/)
  assert.match(orbPanel, /Allow this message and bounded recent context to be processed by OpenAI/)
  assert.match(orbPanel, /role="status"/)
  assert.match(orbPanel, /aria-live="polite"/)
  assert.match(orbPanel, /Voice muted/)
  assert.match(orbPanel, />Stop</)
  assert.match(orbPanel, /\bReplay\b/)
  assert.match(openaiClient, /caption/)
})

test('ElevenLabs uses one shared server-only consent, rights, duration, cost and cleanup boundary', () => {
  assert.match(narratorRoute, /handleElevenLabsSynthesis\(request, 'narrator'\)/)
  assert.match(voiceRoute, /handleElevenLabsSynthesis\(request, 'voice'\)/)
  assert.match(elevenlabs, /verifyFirebaseUser/)
  assert.match(elevenlabs, /authorizeExternalProviderRequest/)
  assert.match(elevenlabs, /consumeProviderRateLimit/)
  assert.match(elevenlabs, /ELEVENLABS_ALLOWED_VOICE_IDS/)
  assert.match(elevenlabs, /VOICE_NOT_AUTHORIZED/)
  assert.match(elevenlabs, /MAX_ESTIMATED_DURATION_SECONDS/)
  assert.match(elevenlabs, /ELEVENLABS_MAX_CHARACTERS_PER_REQUEST/)
  assert.match(elevenlabs, /MAX_PROVIDER_ATTEMPTS = 1/)
  assert.match(elevenlabs, /\/stream`/)
  assert.match(elevenlabs, /enable_logging/)
  assert.match(elevenlabs, /boundedAbortSignal/)
  assert.match(elevenlabs, /character-cost/)
  assert.match(elevenlabs, /private, no-store, max-age=0/)
  assert.doesNotMatch(elevenlabs, /NEXT_PUBLIC_ELEVENLABS/)
})

test('Narrator consent is session-only, off by default, immediately revocable and cache-bounded', () => {
  const playback = compact(narratorPlayback)
  assert.match(narratorClient, /externalProcessingConsent = false/)
  assert.match(narratorClient, /MAX_MEMORY_CACHE_ENTRIES = 12/)
  assert.match(narratorClient, /cache: "no-store"/)
  assert.doesNotMatch(narratorClient, /for \(let attempt/)
  assert.match(playback, /private externalVoiceConsent = false/)
  assert.match(playback, /setExternalVoiceConsent\(allowed: boolean\)/)
  assert.match(playback, /if \(!this\.externalVoiceConsent && this\.aborter\) this\.aborter\.abort\(\)/)
  assert.match(playback, /this\.externalVoiceConsent/)
  assert.match(orbPanel, /setExternalVoiceConsent\(false\)/)
})
