import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const readRoot = (path) => fs.readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8')
const contract = read('src/spatial/memory/selectedMemoryContract.ts')
const hook = read('src/spatial/memory/useSelectedMemory.ts')
const focus = read('src/app/focus/FocusChamberClient.tsx')
const geology = read('src/app/focus/focusMemoryGeology.ts')
const replay = read('src/app/replay/CinematicReplayClient.tsx')
const demoPage = read('src/app/demo/page.tsx')
const demoFilm = read('src/app/demo/replay-film/page.tsx')
const visualAudit = readRoot('scripts/run-live-visual-audit-current.mjs')
const aaaProof = readRoot('scripts/aaa-launch-proof.mjs')

test('production memory loading never silently substitutes demo or seed content', () => {
  assert.doesNotMatch(hook, /lifeMapNodes|seed|quiet-reset|replay-recovery-thread|seed-memory-bloom/)
  assert.match(hook, /firebasePublicEnvReady/)
  assert.match(hook, /Sign in to open this private memory/)
  assert.match(hook, /Selected memory could not be loaded/)
})

test('demo memory is explicit, disclosed, and retained through Life Map camera travel', () => {
  assert.match(contract, /params\.get\('demo'\) === '1'/)
  assert.match(contract, /startsWith\('demo:'\)/)
  assert.match(contract, /This is not personal data/)
  assert.match(hook, /params\.get\('from'\) !== 'life-map-camera'/)
  assert.match(hook, /NEXT_PUBLIC_URAI_EXPLICIT_DEMO/)
  assert.match(hook, /urai:lifeMapDemoMode/)
  assert.match(hook, /`demo:\$\{memoryId\}`/)
  assert.match(hook, /requestedDemoMemoryId/)
  assert.match(hook, /demoContinuationMemoryId/)
  assert.match(hook, /params\.get\('demo'\) === '1' && params\.get\('from'\) === 'life-map'/)
  assert.match(hook, /const continuedDemoMemoryId = demoContinuationMemoryId\(params, memoryId\)/)
  assert.match(hook, /buildNamedExplicitDemoMemory\(requestedDemoMemoryId\)/)
  assert.doesNotMatch(hook, /window\.history\.replaceState/)
  assert.doesNotMatch(hook, /next\.set\('memoryId', demoMemoryId\)/)
  assert.match(focus, /DEMO FIXTURE · NOT PERSONAL DATA/)
  assert.match(replay, /DEMO FIXTURE · NOT PERSONAL DATA/)
})

test('Focus is an explorable authored selected-memory world rather than a static composited page', () => {
  const cameraRig = focus.match(/function FocusCameraRig[\s\S]*?\n}\n\nfunction cloneAuthoredFocusModel/)?.[0]
  assert.ok(cameraRig, 'FocusCameraRig must remain a mounted camera controller')

  assert.match(focus, /from '@react-three\/fiber'/)
  assert.match(focus, /import \* as THREE from 'three'/)
  assert.match(focus, /FOCUS_CHAMBER_MODEL = '\/assets\/urai\/generated\/models\/focus-memory-chamber-v1\.glb'/)
  assert.match(focus, /function cloneAuthoredFocusModel/)
  assert.match(focus, /function AuthoredFocusChamber/)
  assert.match(focus, /useGLTF\(FOCUS_CHAMBER_MODEL\)/)
  assert.match(focus, /object\.castShadow = true/)
  assert.match(focus, /object\.receiveShadow = true/)
  assert.match(focus, /function FocusScene/)
  assert.match(focus, /function ChamberArchitecture/)
  assert.match(focus, /function MemoryTraces/)
  assert.match(focus, /function MemoryAperture/)
  assert.match(focus, /<Canvas[\s\S]*?<FocusScene/)
  assert.match(focus, /<AuthoredFocusChamber \/>/)
  assert.match(focus, /<OrbitControls/)
  assert.match(focus, /data-focus-composition=/)
  assert.match(focus, /focus-v249-authored-depth-observatory-light/)
  assert.match(focus, /v249-no-focus-ring-cage-or-repeated-runes/)
  assert.match(focus, /createFocusStrata, createFocusSurfaceMaps/)
  assert.match(focus, /focus-v251-grounded-living-memory-manifestation/)
  assert.match(geology, /V272 established one connected living-memory phenomenon/)
  assert.match(geology, /v272-single-connected-living-memory-fold/)
  assert.match(geology, /v295-closed-ground-fused-scar-volume-with-buried-closure/)
  assert.match(geology, /v272-no-crystal-crown-no-card-stack/)
  assert.match(geology, /one-closed-ground-owned-scar-no-split-pair-no-portable-outline/)
  assert.match(geology, /v295-sanctuary-memory-scar-volume/)
  assert.match(geology, /v297-off-axis-continuous-ground-held-memory-rupture/)
  assert.doesNotMatch(geology, /v269-living-luminous-memory-lamella|v271-interlocked-volumetric-memory-facet/)
  assert.doesNotMatch(focus.match(/function MemoryAperture[\s\S]*?\n}\n\nfunction FocusScene/)?.[0] ?? '', /map=\{maps\[0\]\}|normalMap=\{maps\[1\]\}|roughnessMap=\{maps\[2\]\}/)
  assert.doesNotMatch(focus, /new THREE\.IcosahedronGeometry\(/)
  assert.doesNotMatch(focus, /new THREE\.SphereGeometry\(1, 72, 48\)/)
  assert.doesNotMatch(focus, /focus-v217-single-connected-memory-manifestation/)
  assert.doesNotMatch(focus, /const sections = 72/)
  assert.doesNotMatch(focus, /const sides = 32/)
  assert.doesNotMatch(focus, /const centerX = -1\.32 \+ t \* 2\.64/)
  assert.doesNotMatch(focus, /const centerY = -0\.66 \+ Math\.sin\(t \* Math\.PI\) \* 0\.72/)
  assert.match(focus, /focus-v216-continuous-weathered-vault/)
  assert.doesNotMatch(focus, /focus-v249-memory-root-cradle/)
  assert.match(focus, /data-focus-visual-revision=/)
  assert.match(focus, /alpha: false/)
  assert.match(focus, /<color attach="background"/)
  assert.match(focus, /\.focusBackdrop\{display:none\}/)
  assert.match(focus, /focus-grounded-memory-traces[^\n]*visible=\{false\}/)
  assert.doesNotMatch(focus, /<torusGeometry|<ringGeometry|wireframe/)
})

test('Replay remains evidence-led and demo-only film surfaces stay explicit', () => {
  assert.match(replay, /This reconstruction is based on the available memory evidence/)
  assert.match(replay, /DEMO FIXTURE · NOT PERSONAL DATA/)
  assert.match(demoPage, /Demo/)
  assert.match(demoFilm, /Demo/)
  assert.match(visualAudit, /replay/)
  assert.match(aaaProof, /replay/)
})
