import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
const readRoot = (path) => fs.readFileSync(new URL(`../../${path}`, import.meta.url), 'utf8')
const contract = read('src/spatial/memory/selectedMemoryContract.ts')
const hook = read('src/spatial/memory/useSelectedMemory.ts')
const focus = read('src/app/focus/FocusChamberClient.tsx')
const replay = read('src/app/replay/CinematicReplayClient.tsx')
const demoPage = read('src/app/demo/page.tsx')
const demoFilm = read('src/app/demo/replay-film/page.tsx')
const visualAudit = readRoot('scripts/run-live-visual-audit-current.mjs')
const aaaProof = readRoot('scripts/aaa-launch-proof.mjs')

test('production memory loading never silently substitutes demo or seed content', () => {
  assert.doesNotMatch(hook, /lifeMapNodes|seed|quiet-reset|replay-recovery-thread|seed-memory-bloom/)
  assert.match(hook, /firebasePublicEnvReady/)
  assert.match(hook, /Sign in to open this private memory/)
  assert.match(hook, /Selected memory could not be loaded/)
})

test('demo memory is explicit, disclosed, and retained through Life Map camera travel', () => {
  assert.match(contract, /params\.get\('demo'\) === '1'/)
  assert.match(contract, /startsWith\('demo:'\)/)
  assert.match(contract, /This is not personal data/)
  assert.match(hook, /params\.get\('from'\) !== 'life-map-camera'/)
  assert.match(hook, /NEXT_PUBLIC_URAI_EXPLICIT_DEMO/)
  assert.match(hook, /urai:lifeMapDemoMode/)
  assert.match(hook, /`demo:\$\{memoryId\}`/)
  assert.match(hook, /requestedDemoMemoryId/)
  assert.match(hook, /demoContinuationMemoryId/)
  assert.match(hook, /params\.get\('demo'\) === '1' && params\.get\('from'\) === 'life-map'/)
  assert.match(hook, /const continuedDemoMemoryId = demoContinuationMemoryId\(params, memoryId\)/)
  assert.match(hook, /buildNamedExplicitDemoMemory\(requestedDemoMemoryId\)/)
  assert.doesNotMatch(hook, /window\.history\.replaceState/)
  assert.doesNotMatch(hook, /next\.set\('memoryId', demoMemoryId\)/)
  assert.match(focus, /DEMO FIXTURE · NOT PERSONAL DATA/)
  assert.match(replay, /DEMO FIXTURE · NOT PERSONAL DATA/)
})

test('Focus is an explorable authored living memory chamber rather than a static composited page', () => {
  const cameraRig = focus.match(/function FocusCameraRig[\s\S]*?\n}\n\nfunction cloneAuthoredFocusModel/)?.[0]
  assert.ok(cameraRig, 'FocusCameraRig must remain a mounted camera controller')

  assert.match(focus, /from '@react-three\/fiber'/)
  assert.match(focus, /import \* as THREE from 'three'/)
  assert.match(focus, /FOCUS_CHAMBER_MODEL = '\/assets\/urai\/generated\/models\/focus-memory-chamber-v1\.glb'/)
  assert.match(focus, /function cloneAuthoredFocusModel/)
  assert.match(focus, /function AuthoredFocusChamber/)
  assert.match(focus, /useGLTF\(FOCUS_CHAMBER_MODEL\)/)
  assert.match(focus, /object\.castShadow = true/)
  assert.match(focus, /object\.receiveShadow = true/)
  assert.match(focus, /function FocusScene/)
  assert.match(focus, /function ChamberArchitecture/)
  assert.match(focus, /function MemoryTraces/)
  assert.match(focus, /function MemoryAperture/)
  assert.match(focus, /<Canvas[\s\S]*?<FocusScene/)
  assert.match(focus, /<AuthoredFocusChamber \/>/)
  assert.match(focus, /<OrbitControls/)
  assert.match(focus, /data-focus-composition="authored-floor-with-filled-memory-field-no-ring-cage"/)
  assert.match(focus, /focus-v153-authored-depth-observatory-light/)
  assert.match(focus, /v149-no-focus-ring-cage-or-repeated-runes/)
  assert.match(focus, /new THREE\.SphereGeometry\(0\.24, 32, 22\)/)
  assert.match(focus, /data-focus-visual-revision="v153-opaque-chamber-dense-field-small-dark-seed-no-arcs"/)
  assert.match(focus, /alpha: false/)
  assert.match(focus, /<color attach="background"/)
  assert.match(focus, /\.focusBackdrop\{display:none\}/)
  assert.match(focus, /focus-grounded-memory-traces[^\n]*visible=\{false\}/)
  assert.doesNotMatch(focus, /<torusGeometry|<ringGeometry|wireframe/)
  assert.doesNotMatch(focus, /<primitive object=\{model\}[^>]*visible=\{false\}/)
  assert.match(focus, /data-focus-physical-asset=\{FOCUS_CHAMBER_MODEL\}/)
  assert.match(focus, /data-focus-spatial="explorable-observatory"/)
  assert.match(focus, /data-focus-movement="walk-keyboard-orbit-touch"/)
  assert.match(focus, /data-focus-pointer-lock="false"/)

  assert.match(cameraRig, /useFrame\(\(_, delta\) =>/)
  for (const key of ['KeyW', 'KeyA', 'KeyS', 'KeyD', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight']) {
    assert.match(cameraRig, new RegExp(`'${key}'`), `Focus camera travel must retain ${key}`)
  }
  assert.doesNotMatch(cameraRig, /reducedMotion/, 'explicit keyboard travel must not be disabled by reduced-motion preference')
  assert.match(cameraRig, /camera\.position\.add\(movementVector\)/)
  assert.match(cameraRig, /THREE\.MathUtils\.clamp\(camera\.position\.x, -CAMERA_LIMIT, CAMERA_LIMIT\)/)
  assert.match(cameraRig, /THREE\.MathUtils\.clamp\(camera\.position\.z, -0\.4, 12\)/)
  assert.match(cameraRig, /camera\.position\.set\(\.\.\.DEFAULT_CAMERA\)/)
  assert.match(cameraRig, /controls\.current\?\.target\.set\(\.\.\.DEFAULT_TARGET\)/)
  assert.match(cameraRig, /recenterSignal/)

  assert.match(focus, /data-focus-camera-x="0\.000"/)
  assert.match(focus, /data-focus-camera-y="1\.450"/)
  assert.match(focus, /data-focus-camera-z="8\.200"/)
  assert.match(focus, /data-focus-distance="0\.000"/)
  assert.match(focus, /shell\.dataset\.focusCameraX = camera\.position\.x\.toFixed\(3\)/)
  assert.match(focus, /shell\.dataset\.focusDistance = camera\.position\.distanceTo\(defaultCamera\)\.toFixed\(3\)/)
  assert.match(focus, /shell\.dataset\.focusMoving = moving \? 'true' : 'false'/)

  assert.match(focus, /if \(!memory \|\| !replayHref \|\| committed\) return/)
  assert.match(focus, /requestUraiWorldTravel\(\{ destination: 'replay'/)
  assert.match(focus, /entryPortal: 'focus-memory-aperture'/)
  assert.match(focus, /cameraCheckpoint: `focus:\$\{memory\.star\.id\}`/)
  assert.match(focus, /replayManifestId: memory\.replayManifest\.id/)
  assert.match(focus, /requestUraiWorldReturn\(\)/)
  assert.match(focus, /data-memory-id=\{memory\?\.id\}/)
  assert.match(focus, /data-manifest-id=\{memory\?\.replayManifest\.id\}/)
  assert.match(focus, /data-star-id=\{memory\?\.star\.id\}/)
  assert.match(focus, /data-node=\{memory\?\.star\.id\}/)

  assert.match(focus, /aria-label="Focus chamber controls"/)
  assert.match(focus, /<button type="button" onClick=\{\(\) => setRecenterSignal/)
  assert.match(focus, /aria-label=\{`Open Replay for \$\{memory\.title\}`\}/)
  assert.match(focus, /<details className="focusHelp">/)
  assert.match(focus, /data-focus-fallback="semantic"/)
  assert.match(focus, /Spatial view unavailable/)
  assert.match(focus, /No personal memory is displayed in this neutral observatory/)
  assert.match(focus, /Held in context\. Nothing leaves this chamber\./)
  assert.match(focus, /prefers-reduced-motion:reduce/)
  assert.match(focus, /@media\(max-width:\d+px\)/)

  assert.doesNotMatch(focus, /className="artifactImage"/, 'the retired static artifact-image owner must not return')
  assert.doesNotMatch(focus, /\.artifactImage\{/, 'the retired static artifact-image CSS owner must not return')
})

test('direct Focus entry remains a truthful neutral observatory and never mounts fake personal data', () => {
  assert.match(focus, /Focus Observatory/)
  assert.match(focus, /No personal memory is displayed in this neutral observatory/)
  assert.match(focus, /Choose a star in Life Map/)
  assert.match(focus, /Open Life Map/)
  assert.match(focus, /Awaiting a selected star/)
  assert.doesNotMatch(focus, /buildExplicitDemoMemory|buildNamedExplicitDemoMemory|URAI_SPATIAL_DEMO_DATA/)
})

test('Focus retains adaptive quality, reduced motion, visibility pausing, and WebGL fallback', () => {
  assert.match(focus, /useAdaptiveSpatialQuality/)
  assert.match(focus, /profile\.pixelRatioMax/)
  assert.match(focus, /profile\.documentVisible \? 'demand' : 'never'/)
  assert.match(focus, /function FocusRenderCadence/)
  assert.match(focus, /setFrameloop\('always'\)/)
  assert.match(focus, /setFrameloop\('never'\)/)
  assert.match(focus, /useWebGLAvailable/)
  assert.match(focus, /Spatial view unavailable/)
  assert.match(focus, /profile\.reducedMotion/)
  assert.match(focus, /markFirstSpatialFrame\('\/focus'/)
  assert.match(focus, /webglcontextlost/)
  assert.match(focus, /webglcontextrestored/)
  assert.match(focus, /data-webgl-state=\{webglState\}/)
})

test('public demo is disclosed by default and retains an explicit production kill switch', () => {
  assert.match(demoPage, /import CutOneReplayFilmPage from '\.\/replay-film\/page'/)
  assert.match(demoPage, /return <CutOneReplayFilmPage \/>/)
  assert.match(demoPage, /publicDemoRouteExplicitlyDisabled/)
  assert.match(demoPage, /NEXT_PUBLIC_ALLOW_PUBLIC_DEMO_ROUTES === 'false'/)
  assert.match(demoPage, /URAI_ALLOW_PUBLIC_DEMO_ROUTES === 'false'/)
  assert.match(demoPage, /if \(publicDemoRouteExplicitlyDisabled\(\)\) notFound\(\)/)
  assert.match(demoFilm, /data-demo-disclosure="not-personal-data"/)
  assert.match(demoFilm, /Demo fixture · not personal data/)
  assert.match(demoFilm, /NEXT_PUBLIC_ALLOW_PUBLIC_DEMO_ROUTES === 'false'/)
  assert.match(demoFilm, /URAI_ALLOW_PUBLIC_DEMO_ROUTES === 'false'/)
  assert.doesNotMatch(demoPage, /ALLOW_PUBLIC_DEMO_ROUTES === 'true'/)
  assert.doesNotMatch(demoFilm, /ALLOW_PUBLIC_DEMO_ROUTES === 'true'/)
})

test('public proof rail never links its Focus or Replay scenes to identity-free routes', () => {
  assert.match(demoFilm, /const demoMemoryQuery = 'memoryId=demo%3Aquiet-reset&manifestId=replay-recovery-thread&node=quiet-reset&demo=1'/)
  assert.match(demoFilm, /const demoFocusHref = `\/focus\?\$\{demoMemoryQuery\}`/)
  assert.match(demoFilm, /const demoReplayHref = `\/replay\?\$\{demoMemoryQuery\}`/)
  assert.match(demoFilm, /href: '\/life-map\?demo=1'/)
  assert.match(demoFilm, /href: demoFocusHref/)
  assert.match(demoFilm, /href: demoReplayHref/)
  assert.doesNotMatch(demoFilm, /href: '\/focus',/)
  assert.doesNotMatch(demoFilm, /href: '\/replay',/)
})

test('visual proof rejects URL-only Life Map to Focus success', () => {
  assert.match(visualAudit, /getAttribute\('data-memory-status'\) === 'demo'/)
  assert.match(visualAudit, /getAttribute\('data-memory-id'\)\?\.startsWith\('demo:'\)/)
  assert.match(visualAudit, /document\.body\.textContent\?\.includes\('Memory unavailable'\)/)
  assert.match(visualAudit, /destinationUrl\.searchParams\.get\('demo'\) !== '1'/)
  assert.match(visualAudit, /Life Map did not preserve truthful explicit-demo identity into Focus/)
})

test('AAA receipt records disclosed demo routes and current semantic markers', () => {
  assert.match(aaaProof, /const demoMemoryQuery = 'memoryId=demo%3Aquiet-reset&manifestId=replay-recovery-thread&node=quiet-reset&demo=1'/)
  assert.match(aaaProof, /route: `\/focus\?\$\{demoMemoryQuery\}`/)
  assert.match(aaaProof, /route: `\/replay\?\$\{demoMemoryQuery\}`/)
  assert.match(aaaProof, /markers: \['The Quiet Reset', 'Selected memory', 'Enter Replay'\]/)
  assert.match(aaaProof, /markers: \['Your life is a world\.', 'Demo fixture', 'Play the proof rail'\]/)
  assert.doesNotMatch(aaaProof, /route: '\/focus\?memoryId=quiet-reset'/)
  assert.doesNotMatch(aaaProof, /markers: \['URAI'\]/)
})

test('privacy-safe denied, deleted, unavailable, and corrupt states exist', () => {
  for (const state of ['unavailable', 'deleted', 'unauthorized', 'corrupt']) assert.match(contract, new RegExp(`'${state}'`))
  assert.match(contract, /ownerId !== expectedOwnerId/)
  assert.match(contract, /raw\.deleted === true/)
  assert.match(contract, /replay manifest is incomplete/i)
})

test('Focus and Replay share exact selected memory and manifest identity', () => {
  assert.match(focus, /useSelectedMemory/)
  assert.match(replay, /useSelectedMemory/)
  assert.match(focus, /data-star-id=\{memory\?\.star\.id\}/)
  assert.match(replay, /data-star-id=\{memory\.star\.id\}/)
  assert.match(focus, /memory\.replayManifest\.id/)
  assert.match(replay, /memory\?\.replayManifest\.segments/)
  assert.doesNotMatch(focus, /quiet-reset|replay-recovery-thread|The pressure became permission/)
  assert.doesNotMatch(replay, /quiet-reset|seed-memory-bloom|Evening Pattern/)
})
