'use client'
import {useMemo,useRef} from 'react'
import {useTexture} from '@react-three/drei'
import {useFrame,type ThreeEvent} from '@react-three/fiber'
import * as THREE from 'three'
import type {OrbState} from '@/app/home/orbStateController'
export const T=['/assets/urai/home-production/cc0/rock-tile-floor/rock-tile-floor-diff-1k.webp','/assets/urai/home-production/cc0/rock-tile-floor/rock-tile-floor-normal-gl-1k.webp','/assets/urai/home-production/cc0/rock-tile-floor/rock-tile-floor-arm-1k.webp'] as const
export const SPAWN=new THREE.Vector3(0,.04,4.6),ORB=new THREE.Vector3(-.58,1.2,-7.9),GROUND=new THREE.Vector3(-4.85,0,-8.25),LIFE_MAP=new THREE.Vector3(4.85,0,-8.25),BOUNDS={minX:-7.5,maxX:7.5,minZ:-14.4,maxZ:6.8}
function maps(){const[c,n,a]=useTexture(T as unknown as string[]);return useMemo(()=>[c,n,a].map((s,i)=>{const q=s.clone();q.wrapS=q.wrapT=THREE.RepeatWrapping;q.repeat.set(2.6,5.2);q.anisotropy=8;q.colorSpace=i?THREE.NoColorSpace:THREE.SRGBColorSpace;q.needsUpdate=true;return q}),[a,c,n])}
function feature(x:number,z:number,p:THREE.Vector3,kind:'ground'|'life-map'){const dx=x-p.x,dz=z-p.z,r=Math.hypot(dx,dz);if(r>4)return 0;const fade=1-THREE.MathUtils.smoothstep(r,2.35,4);if(kind==='ground')return(-.78*Math.exp(-(dx*dx*.26+dz*dz*.14))+.7*Math.exp(-((dx+1.25)**2*.48+(dz+1.6)**2*.44))+.18*Math.sin((dx-dz*.3)*2.5)*Math.exp(-r*r*.1))*fade;const trunk=Math.exp(-Math.pow(dx-.2*Math.sin(dz*1.15),2)*3.7)*THREE.MathUtils.clamp((-dz+2.6)/5.2,0,1),fork=Math.exp(-Math.pow(dx-1.05-.28*dz,2)*4.3)*THREE.MathUtils.clamp((-dz+1.7)/4.2,0,1);return(trunk*1.1+fork*.68-.16*Math.exp(-(dx*dx*.2+(dz-1.4)**2*.44)))*fade}
export function height(x:number,z:number){const d=THREE.MathUtils.clamp((6.5-z)/30,0,1),center=Math.sin((z+1.5)*.15)*.8+Math.sin(z*.05)*.4,dx=x-center,lat=Math.abs(dx)/12.6;return-.95-.35*Math.exp(-Math.pow(dx/3.25,4))+Math.pow(lat,1.55)*(.25+d*4.8)+Math.pow(d,3.8)*2.35+.3*Math.sin((Math.abs(dx)*.58-d*2.2)*Math.PI)*THREE.MathUtils.smoothstep(Math.abs(dx),3,10.5)-.48*Math.exp(-Math.pow((x+6+Math.sin(z*.23)*.9)/.72,2))*THREE.MathUtils.smoothstep(d,.1,.85)-.4*Math.exp(-Math.pow((x-6.4+Math.sin(z*.19)*.72)/.72,2))*THREE.MathUtils.smoothstep(d,.18,.88)+(Math.sin(x*.62+z*.31)*.18+Math.sin(x*1.37-z*.59)*.1+Math.cos(x*2.75+z*.23)*.055)*(.25+lat*1.15)+feature(x,z,GROUND,'ground')+feature(x,z,LIFE_MAP,'life-map')}
function rockColor(x:number,y:number,z:number){const a=new THREE.Color('#3d4034'),b=new THREE.Color('#68725c'),c=new THREE.Color('#9a7d59'),d=new THREE.Color('#b6a47f'),band=.5+.5*Math.sin(y*7.4+z*.36+x*.14),age=THREE.MathUtils.clamp((6-z)/33,0,1);return a.lerp(b,.34+band*.32).lerp(c,Math.abs(x)/48+age*.15).lerp(d,Math.max(0,band-.76)*.28)}
function terrainGeometry(){const xs=112,zs=164,p:number[]=[],uv:number[]=[],c:number[]=[],idx:number[]=[];for(let iz=0;iz<=zs;iz++){const vz=iz/zs,z=7.2-vz*34.5;for(let ix=0;ix<=xs;ix++){const vx=ix/xs,x=-13.8+vx*27.6,y=height(x,z),q=rockColor(x,y,z);p.push(x,y,z);uv.push(vx*10,vz*14);c.push(q.r,q.g,q.b)}}for(let iz=0;iz<zs;iz++)for(let ix=0;ix<xs;ix++){const a=iz*(xs+1)+ix,b=a+1,d=a+xs+1,e=d+1;(ix+iz)&1?idx.push(a,b,e,a,e,d):idx.push(a,b,d,b,e,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setAttribute('color',new THREE.Float32BufferAttribute(c,3));g.setIndex(idx);g.computeVertexNormals();return g}
export function Terrain({walk,onGround,onLifeMap}:{walk:(e:ThreeEvent<MouseEvent>)=>void;onGround:()=>void;onLifeMap:()=>void}){const m=maps(),g=useMemo(terrainGeometry,[]);return <mesh name="home-v223-continuous-stratified-weathered-sanctuary" geometry={g} receiveShadow onClick={e=>{e.stopPropagation();const dg=Math.hypot(e.point.x-GROUND.x,e.point.z-GROUND.z),dl=Math.hypot(e.point.x-LIFE_MAP.x,e.point.z-LIFE_MAP.z);dg<2.45?onGround():dl<2.45?onLifeMap():walk(e)}}><meshStandardMaterial vertexColors map={m[0]} normalMap={m[1]} normalScale={new THREE.Vector2(1.05,1.05)} roughnessMap={m[2]} roughness={.97} metalness={.002}/></mesh>}
function escarpment(side:-1|1){const zs=72,ls=6,p:number[]=[],uv:number[]=[],c:number[]=[],idx:number[]=[];for(let iz=0;iz<=zs;iz++){const vz=iz/zs,z=4.8-vz*30.5,d=THREE.MathUtils.clamp((5-z)/31,0,1),inner=4.6+d*1.35+.32*Math.sin(z*.2+side);for(let l=0;l<ls;l++){const t=l/(ls-1),x=side*(inner+t*(4.6+d*1.6)+.24*Math.sin(z*.37+l*1.2+side)),base=height(x,z),y=base+t*(.72+d*3.1)+.1*Math.sin(z*.4+l*1.6),q=rockColor(x,y,z);p.push(x,y,z);uv.push(vz*8,t*3);c.push(q.r,q.g,q.b)}}for(let iz=0;iz<zs;iz++)for(let l=0;l<ls-1;l++){const a=iz*ls+l,b=a+1,d=(iz+1)*ls+l,e=d+1;side<0?idx.push(a,b,d,b,e,d):idx.push(a,d,b,b,d,e)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setAttribute('color',new THREE.Float32BufferAttribute(c,3));g.setIndex(idx);g.computeVertexNormals();return g}
export function Escarpment({side}:{side:-1|1}){const m=maps(),g=useMemo(()=>escarpment(side),[side]);return <mesh name={side<0?'home-v223-port-eroded-escarpment':'home-v223-starboard-eroded-escarpment'} geometry={g} castShadow receiveShadow><meshStandardMaterial vertexColors map={m[0]} normalMap={m[1]} normalScale={new THREE.Vector2(.82,.82)} roughnessMap={m[2]} roughness={.98} side={THREE.DoubleSide}/></mesh>}
function rootedCurve(points:[number,number,number][],radius=.14){return new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(([x,y,z])=>new THREE.Vector3(x,y,z))),36,radius,8,false)}
function RockRib({points,radius=.14,glow}:{points:[number,number,number][];radius?:number;glow?:string}){const m=maps(),g=useMemo(()=>rootedCurve(points,radius),[]);return <mesh geometry={g} castShadow receiveShadow><meshStandardMaterial map={m[0]} normalMap={m[1]} normalScale={new THREE.Vector2(.9,.9)} roughnessMap={m[2]} roughness={.98} color="#77715f" emissive={glow??'#000000'} emissiveIntensity={glow?.14:0}/></mesh>}
function GroundPlace(){const y=height(GROUND.x,GROUND.z)+.08;return <group name="home-v223-rooted-ground-gathering-basin"><RockRib radius={.2} points={[[GROUND.x-1.8,y+.18,GROUND.z+1.05],[GROUND.x-1.15,y+.08,GROUND.z+.25],[GROUND.x-.15,y,GROUND.z-.2],[GROUND.x+.95,y+.06,GROUND.z+.25],[GROUND.x+1.65,y+.2,GROUND.z+1.05]]}/><RockRib radius={.13} points={[[GROUND.x-1.25,y+.05,GROUND.z-.65],[GROUND.x-.7,y-.05,GROUND.z-.92],[GROUND.x,y-.12,GROUND.z-1.02],[GROUND.x+.78,y-.02,GROUND.z-.82],[GROUND.x+1.28,y+.08,GROUND.z-.46]]}/><RockRib radius={.055} glow="#a9582f" points={[[GROUND.x-1.0,y+.03,GROUND.z+.2],[GROUND.x-.45,y-.02,GROUND.z-.05],[GROUND.x+.08,y-.04,GROUND.z-.18],[GROUND.x+.72,y+.01,GROUND.z+.08]]}/><pointLight position={[GROUND.x,y+.35,GROUND.z]} color="#d77d47" intensity={2.1} distance={4.8} decay={2}/></group>}
function LifeMapPlace(){const y=height(LIFE_MAP.x,LIFE_MAP.z)+.1;return <group name="home-v223-rooted-life-map-branch-place"><RockRib radius={.17} points={[[LIFE_MAP.x,y,LIFE_MAP.z+1.65],[LIFE_MAP.x-.12,y+.12,LIFE_MAP.z+.75],[LIFE_MAP.x+.05,y+.24,LIFE_MAP.z-.1],[LIFE_MAP.x+.2,y+.42,LIFE_MAP.z-1.15],[LIFE_MAP.x+.1,y+.58,LIFE_MAP.z-2.0]]}/><RockRib radius={.11} points={[[LIFE_MAP.x+.05,y+.25,LIFE_MAP.z-.1],[LIFE_MAP.x+.72,y+.38,LIFE_MAP.z-.62],[LIFE_MAP.x+1.35,y+.54,LIFE_MAP.z-1.2],[LIFE_MAP.x+1.85,y+.7,LIFE_MAP.z-1.7]]}/><RockRib radius={.095} points={[[LIFE_MAP.x+.02,y+.23,LIFE_MAP.z-.2],[LIFE_MAP.x-.58,y+.34,LIFE_MAP.z-.74],[LIFE_MAP.x-1.12,y+.5,LIFE_MAP.z-1.35]]}/><RockRib radius={.045} glow="#4c9b82" points={[[LIFE_MAP.x,y+.18,LIFE_MAP.z+1.35],[LIFE_MAP.x-.05,y+.27,LIFE_MAP.z+.48],[LIFE_MAP.x+.08,y+.39,LIFE_MAP.z-.3],[LIFE_MAP.x+.25,y+.55,LIFE_MAP.z-1.25]]}/><pointLight position={[LIFE_MAP.x,y+.65,LIFE_MAP.z-.55]} color="#78cbb0" intensity={1.75} distance={4.8} decay={2}/><pointLight position={[LIFE_MAP.x+1.15,y+.82,LIFE_MAP.z-1.2]} color="#a68acb" intensity={.9} distance={3.2} decay={2}/></group>}
export function DestinationLights(){return <><GroundPlace/><LifeMapPlace/></>}
function orbVertex(v:THREE.Vector3,inner=false){const n=v.clone().normalize(),th=Math.atan2(n.z,n.x),ph=Math.acos(THREE.MathUtils.clamp(n.y,-1,1)),sp=Math.sin(ph),ang=(a:number)=>Math.atan2(Math.sin(th-a),Math.cos(th-a)),primary=.34*Math.exp(-Math.pow(ang(.45)/.34,2))*Math.exp(-Math.pow((ph-1.48)/.55,2)),secondary=.16*Math.exp(-Math.pow(ang(-2.15)/.5,2))*Math.exp(-Math.pow((ph-1.7)/.72,2)),bulge=.24*Math.exp(-Math.pow(ang(-.95)/.62,2))*Math.exp(-Math.pow((ph-1.08)/.7,2)),fold=.075*Math.sin(th*3.1+ph*2.2)+.042*Math.sin(th*6.2-ph*1.8)+.026*Math.cos(th*9.5+ph*3.2),r=(inner?.57:.86)*Math.max(.48,1+fold*sp-primary-secondary+bulge),lean=.16*sp*sp*Math.max(0,Math.cos(th+.65));return new THREE.Vector3(r*sp*Math.cos(th)*1.2+lean-.08*Math.sin(ph*2.2),r*Math.cos(ph)*.88+.09*Math.sin(ph*2.4+th*.65),r*sp*Math.sin(th)*.93+.07*Math.sin(th*2.1)*sp*sp)}
function orbGeometry(inner=false,cut=false){const src=new THREE.IcosahedronGeometry(1,inner?4:5).toNonIndexed(),a=src.getAttribute('position') as THREE.BufferAttribute,p:number[]=[],c:number[]=[],deep=new THREE.Color(inner?'#17322b':'#30483e'),moss=new THREE.Color(inner?'#3e725e':'#78917a'),warm=new THREE.Color(inner?'#b7774f':'#b69a72');for(let i=0;i<a.count;i+=3){const raw=[0,1,2].map(k=>new THREE.Vector3(a.getX(i+k),a.getY(i+k),a.getZ(i+k))),cent=raw[0].clone().add(raw[1]).add(raw[2]).normalize(),th=Math.atan2(cent.z,cent.x),ph=Math.acos(THREE.MathUtils.clamp(cent.y,-1,1)),aa=Math.abs(Math.atan2(Math.sin(th-.44),Math.cos(th-.44))),hole=cut&&aa<.17&&Math.abs(ph-1.48)<.34&&Math.sin(th*8.7+ph*12.1)>.05;if(hole)continue;for(const rv of raw){const q=orbVertex(rv,inner),nn=rv.clone().normalize(),t=Math.atan2(nn.z,nn.x),f=Math.acos(THREE.MathUtils.clamp(nn.y,-1,1)),band=.5+.5*Math.sin(f*10.5+t*2.8),heat=Math.max(0,Math.cos(t-.55))*Math.sin(f)**2,col=deep.clone().lerp(moss,.32+band*.38).lerp(warm,heat*(inner?.34:.16));p.push(q.x,q.y,q.z);c.push(col.r,col.g,col.b)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('color',new THREE.Float32BufferAttribute(c,3));g.computeVertexNormals();return g}
type Posture={s:[number,number,number];r:[number,number,number];speed:number;inner:number};const P:Record<OrbState,Posture>={dormant:{s:[.74,.66,.8],r:[.2,-.5,-.12],speed:.1,inner:-.2},idle:{s:[1.1,.88,.95],r:[-.12,.3,-.08],speed:.36,inner:.08},attention:{s:[1.32,.92,.76],r:[-.26,.58,.2],speed:.72,inner:.52},listening:{s:[.88,1.18,.88],r:[.3,-.44,-.17],speed:.27,inner:-.58},thinking:{s:[1.32,.76,1.08],r:[-.36,.82,.26],speed:.22,inner:.9},speaking:{s:[1.42,.88,.68],r:[.14,.32,-.31],speed:1.04,inner:1.1},guiding:{s:[.84,1.24,.8],r:[-.42,-.22,.28],speed:.5,inner:-.78},reflecting:{s:[.88,.8,1.24],r:[.35,.88,-.23],speed:.16,inner:.4},calming:{s:[1.2,.72,1.02],r:[-.05,-.35,.08],speed:.14,inner:-.3},privacy:{s:[.68,.74,.66],r:[.46,.98,.33],speed:.08,inner:1},warning:{s:[1.45,.9,.6],r:[-.46,-.62,-.34],speed:1.3,inner:-1.18},transition:{s:[.76,1.3,.72],r:[-.52,.44,.36],speed:.86,inner:.68}}
export function Orb({state,reducedMotion,onOpen}:{state:OrbState;reducedMotion:boolean;onOpen:()=>void}){const group=useRef<THREE.Group>(null),inside=useRef<THREE.Mesh>(null),outer=useMemo(()=>orbGeometry(false,true),[]),inner=useMemo(()=>orbGeometry(true,false),[]),p=P[state];useFrame(({clock})=>{if(!group.current)return;const t=clock.elapsedTime*p.speed,b=reducedMotion?1:1+Math.sin(t*.8)*.024;group.current.scale.set(p.s[0]*b,p.s[1]*b,p.s[2]*b);group.current.rotation.set(p.r[0],p.r[1]+(reducedMotion?0:Math.sin(t*.92)*.13),p.r[2]);if(inside.current&&!reducedMotion)inside.current.rotation.y=p.inner+Math.sin(t*1.7)*.34});return <group ref={group} name="home-v223-connected-open-cleft-living-memory-presence" position={ORB} onClick={e=>{e.stopPropagation();onOpen()}}><mesh geometry={outer} castShadow receiveShadow><meshStandardMaterial vertexColors roughness={.8} metalness={0} emissive={state==='warning'?'#59231c':'#102c24'} emissiveIntensity={state==='warning'?.24:.075}/></mesh><mesh ref={inside} geometry={inner} scale={[.69,.69,.69]} rotation={[.12,p.inner,-.08]}><meshStandardMaterial vertexColors roughness={.72} metalness={0} emissive="#2b8067" emissiveIntensity={state==='dormant'?.08:.48}/></mesh><pointLight color={state==='warning'?'#c45b42':'#76b797'} intensity={state==='dormant'?.18:1.05} distance={3.5} decay={2}/></group>}
