'use client'
import {useMemo,useRef} from 'react'
import {useTexture} from '@react-three/drei'
import {useFrame,type ThreeEvent} from '@react-three/fiber'
import * as THREE from 'three'
import type {OrbState} from '@/app/home/orbStateController'
export const T=['/assets/urai/home-production/cc0/rock-tile-floor/rock-tile-floor-diff-1k.webp','/assets/urai/home-production/cc0/rock-tile-floor/rock-tile-floor-normal-gl-1k.webp','/assets/urai/home-production/cc0/rock-tile-floor/rock-tile-floor-arm-1k.webp'] as const
export const SPAWN=new THREE.Vector3(0,.04,4.6),ORB=new THREE.Vector3(-.58,1.2,-7.9),GROUND=new THREE.Vector3(-4.85,0,-8.25),LIFE_MAP=new THREE.Vector3(4.85,0,-8.25),BOUNDS={minX:-7.5,maxX:7.5,minZ:-14.4,maxZ:6.8}
function maps(){const[c,n,a]=useTexture(T as unknown as string[]);return useMemo(()=>[c,n,a].map((s,i)=>{const q=s.clone();q.wrapS=q.wrapT=THREE.RepeatWrapping;q.repeat.set(8,12);q.anisotropy=8;q.colorSpace=i?THREE.NoColorSpace:THREE.SRGBColorSpace;q.needsUpdate=true;return q}),[a,c,n])}
function feature(x:number,z:number,p:THREE.Vector3,kind:'ground'|'life-map'){const dx=x-p.x,dz=z-p.z,r=Math.hypot(dx,dz);if(r>4)return 0;const fade=1-THREE.MathUtils.smoothstep(r,2.35,4);if(kind==='ground')return(-.78*Math.exp(-(dx*dx*.26+dz*dz*.14))+.7*Math.exp(-((dx+1.25)**2*.48+(dz+1.6)**2*.44))+.18*Math.sin((dx-dz*.3)*2.5)*Math.exp(-r*r*.1))*fade;const trunk=Math.exp(-Math.pow(dx-.2*Math.sin(dz*1.15),2)*3.7)*THREE.MathUtils.clamp((-dz+2.6)/5.2,0,1),fork=Math.exp(-Math.pow(dx-1.05-.28*dz,2)*4.3)*THREE.MathUtils.clamp((-dz+1.7)/4.2,0,1);return(trunk*1.1+fork*.68-.16*Math.exp(-(dx*dx*.2+(dz-1.4)**2*.44)))*fade}
export function height(x:number,z:number){const d=THREE.MathUtils.clamp((6.5-z)/30,0,1),center=Math.sin((z+1.5)*.15)*.8+Math.sin(z*.05)*.4,dx=x-center,lat=Math.abs(dx)/12.6;return-.95-.35*Math.exp(-Math.pow(dx/3.25,4))+Math.pow(lat,1.55)*(.25+d*4.8)+Math.pow(d,3.8)*2.35+.3*Math.sin((Math.abs(dx)*.58-d*2.2)*Math.PI)*THREE.MathUtils.smoothstep(Math.abs(dx),3,10.5)-.48*Math.exp(-Math.pow((x+6+Math.sin(z*.23)*.9)/.72,2))*THREE.MathUtils.smoothstep(d,.1,.85)-.4*Math.exp(-Math.pow((x-6.4+Math.sin(z*.19)*.72)/.72,2))*THREE.MathUtils.smoothstep(d,.18,.88)+(Math.sin(x*.62+z*.31)*.18+Math.sin(x*1.37-z*.59)*.1+Math.cos(x*2.75+z*.23)*.055)*(.25+lat*1.15)+feature(x,z,GROUND,'ground')+feature(x,z,LIFE_MAP,'life-map')}
function rockColor(x:number,y:number,z:number){const a=new THREE.Color('#3d4034'),b=new THREE.Color('#68725c'),c=new THREE.Color('#9a7d59'),d=new THREE.Color('#b6a47f'),band=.5+.5*Math.sin(y*7.4+z*.36+x*.14),age=THREE.MathUtils.clamp((6-z)/33,0,1);return a.lerp(b,.34+band*.32).lerp(c,Math.abs(x)/48+age*.15).lerp(d,Math.max(0,band-.76)*.28)}
function terrainGeometry(){const xs=112,zs=164,p:number[]=[],uv:number[]=[],c:number[]=[],idx:number[]=[];for(let iz=0;iz<=zs;iz++){const vz=iz/zs,z=7.2-vz*34.5;for(let ix=0;ix<=xs;ix++){const vx=ix/xs,x=-13.8+vx*27.6,y=height(x,z),q=rockColor(x,y,z);p.push(x,y,z);uv.push(vx*10,vz*14);c.push(q.r,q.g,q.b)}}for(let iz=0;iz<zs;iz++)for(let ix=0;ix<xs;ix++){const a=iz*(xs+1)+ix,b=a+1,d=a+xs+1,e=d+1;(ix+iz)&1?idx.push(a,b,e,a,e,d):idx.push(a,b,d,b,e,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setAttribute('color',new THREE.Float32BufferAttribute(c,3));g.setIndex(idx);g.computeVertexNormals();return g}
export function Terrain({walk,onGround,onLifeMap}:{walk:(e:ThreeEvent<MouseEvent>)=>void;onGround:()=>void;onLifeMap:()=>void}){const m=maps(),g=useMemo(terrainGeometry,[]);return <mesh name="home-v223-continuous-stratified-weathered-sanctuary" geometry={g} receiveShadow onClick={e=>{e.stopPropagation();const dg=Math.hypot(e.point.x-GROUND.x,e.point.z-GROUND.z),dl=Math.hypot(e.point.x-LIFE_MAP.x,e.point.z-LIFE_MAP.z);dg<2.45?onGround():dl<2.45?onLifeMap():walk(e)}}><meshStandardMaterial vertexColors map={m[0]} normalMap={m[1]} normalScale={new THREE.Vector2(.62,.62)} roughnessMap={m[2]} roughness={.97} metalness={.002}/></mesh>}
function escarpment(side:-1|1){const zs=72,ls=6,p:number[]=[],uv:number[]=[],c:number[]=[],idx:number[]=[];for(let iz=0;iz<=zs;iz++){const vz=iz/zs,z=4.8-vz*30.5,d=THREE.MathUtils.clamp((5-z)/31,0,1),inner=4.6+d*1.35+.32*Math.sin(z*.2+side);for(let l=0;l<ls;l++){const t=l/(ls-1),x=side*(inner+t*(4.6+d*1.6)+.24*Math.sin(z*.37+l*1.2+side)),base=height(x,z),y=base+t*(.72+d*3.1)+.1*Math.sin(z*.4+l*1.6),q=rockColor(x,y,z);p.push(x,y,z);uv.push(vz*8,t*3);c.push(q.r,q.g,q.b)}}for(let iz=0;iz<zs;iz++)for(let l=0;l<ls-1;l++){const a=iz*ls+l,b=a+1,d=(iz+1)*ls+l,e=d+1;side<0?idx.push(a,b,d,b,e,d):idx.push(a,d,b,b,d,e)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setAttribute('color',new THREE.Float32BufferAttribute(c,3));g.setIndex(idx);g.computeVertexNormals();return g}
export function Escarpment({side}:{side:-1|1}){const m=maps(),g=useMemo(()=>escarpment(side),[side]);return <mesh name={side<0?'home-v223-port-eroded-escarpment':'home-v223-starboard-eroded-escarpment'} geometry={g} castShadow receiveShadow><meshStandardMaterial vertexColors map={m[0]} normalMap={m[1]} normalScale={new THREE.Vector2(.45,.45)} roughnessMap={m[2]} roughness={.98} side={THREE.DoubleSide}/></mesh>}
export function DestinationLights(){return <><pointLight position={[GROUND.x,height(GROUND.x,GROUND.z)+.45,GROUND.z]} color="#db9b61" intensity={2} distance={4.3} decay={2}/><pointLight position={[LIFE_MAP.x,height(LIFE_MAP.x,LIFE_MAP.z)+.65,LIFE_MAP.z]} color="#8fcdb3" intensity={1.75} distance={4.3} decay={2}/><pointLight position={[LIFE_MAP.x+1,height(LIFE_MAP.x,LIFE_MAP.z)+.5,LIFE_MAP.z-1]} color="#b5a0d8" intensity={.75} distance={3} decay={2}/></>}
function orbVertex(v:THREE.Vector3,inner=false){const n=v.clone().normalize(),th=Math.atan2(n.z,n.x),ph=Math.acos(THREE.MathUtils.clamp(n.y,-1,1)),s=Math.sin(ph),cleft=.55*Math.exp(-Math.pow(Math.atan2(Math.sin(th-.42),Math.cos(th-.42))/.38,2))*Math.exp(-Math.pow((ph-1.5)/.62,2)),cleft2=.32*Math.exp(-Math.pow(Math.atan2(Math.sin(th+2.1),Math.cos(th+2.1))/.46,2))*Math.exp(-Math.pow((ph-1.65)/.7,2)),bulge=.4*Math.exp(-Math.pow(Math.atan2(Math.sin(th+1.05),Math.cos(th+1.05))/.48,2))*Math.exp(-Math.pow((ph-1.05)/.58,2)),noise=.16*Math.sin(th*3.2+ph*1.7)+.08*Math.sin(th*6.7-ph*2.3)+.05*Math.cos(th*11.3+ph*4.1),r=(inner?.58:.86)*Math.max(.3,1+noise*s-cleft-cleft2+bulge);return new THREE.Vector3(r*s*Math.cos(th)*1.22+.22*s*s*Math.max(0,Math.cos(th+.72))-.12*Math.sin(ph*2.1),r*Math.cos(ph)*.8+.13*Math.sin(ph*2.8+th*.8),r*s*Math.sin(th)*.88+.1*Math.sin(th*2.4)*s*s)}
function orbGeometry(inner=false,cut=false){const src=new THREE.IcosahedronGeometry(1,inner?3:4).toNonIndexed(),a=src.getAttribute('position') as THREE.BufferAttribute,p:number[]=[],c:number[]=[],deep=new THREE.Color(inner?'#102720':'#293d31'),moss=new THREE.Color(inner?'#315b49':'#71816a'),warm=new THREE.Color(inner?'#654a37':'#b89469');for(let i=0;i<a.count;i+=3){const raw=[0,1,2].map(k=>new THREE.Vector3(a.getX(i+k),a.getY(i+k),a.getZ(i+k))),cent=raw[0].clone().add(raw[1]).add(raw[2]).normalize(),th=Math.atan2(cent.z,cent.x),ph=Math.acos(THREE.MathUtils.clamp(cent.y,-1,1)),hole=cut&&Math.abs(Math.atan2(Math.sin(th-.36),Math.cos(th-.36)))<.43&&Math.abs(ph-1.52)<.48&&Math.sin(th*13+ph*9)>.05;if(hole)continue;for(const rv of raw){const q=orbVertex(rv,inner),nn=rv.clone().normalize(),t=Math.atan2(nn.z,nn.x),f=Math.acos(THREE.MathUtils.clamp(nn.y,-1,1)),band=.5+.5*Math.sin(f*16+t*3.5),heat=Math.max(0,Math.cos(t-.7))*Math.sin(f)**2.4,col=deep.clone().lerp(moss,.22+band*.52).lerp(warm,heat*(inner?.12:.28));p.push(q.x,q.y,q.z);c.push(col.r,col.g,col.b)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('color',new THREE.Float32BufferAttribute(c,3));g.computeVertexNormals();return g}
type Posture={s:[number,number,number];r:[number,number,number];speed:number;inner:number};const P:Record<OrbState,Posture>={dormant:{s:[.74,.66,.8],r:[.2,-.5,-.12],speed:.1,inner:-.2},idle:{s:[1.1,.88,.95],r:[-.12,.3,-.08],speed:.36,inner:.08},attention:{s:[1.32,.92,.76],r:[-.26,.58,.2],speed:.72,inner:.52},listening:{s:[.88,1.18,.88],r:[.3,-.44,-.17],speed:.27,inner:-.58},thinking:{s:[1.32,.76,1.08],r:[-.36,.82,.26],speed:.22,inner:.9},speaking:{s:[1.42,.88,.68],r:[.14,.32,-.31],speed:1.04,inner:1.1},guiding:{s:[.84,1.24,.8],r:[-.42,-.22,.28],speed:.5,inner:-.78},reflecting:{s:[.88,.8,1.24],r:[.35,.88,-.23],speed:.16,inner:.4},calming:{s:[1.2,.72,1.02],r:[-.05,-.35,.08],speed:.14,inner:-.3},privacy:{s:[.68,.74,.66],r:[.46,.98,.33],speed:.08,inner:1},warning:{s:[1.45,.9,.6],r:[-.46,-.62,-.34],speed:1.3,inner:-1.18},transition:{s:[.76,1.3,.72],r:[-.52,.44,.36],speed:.86,inner:.68}}
export function Orb({state,reducedMotion,onOpen}:{state:OrbState;reducedMotion:boolean;onOpen:()=>void}){const group=useRef<THREE.Group>(null),inside=useRef<THREE.Mesh>(null),outer=useMemo(()=>orbGeometry(false,true),[]),inner=useMemo(()=>orbGeometry(true,false),[]),p=P[state];useFrame(({clock})=>{if(!group.current)return;const t=clock.elapsedTime*p.speed,b=reducedMotion?1:1+Math.sin(t*.8)*.024;group.current.scale.set(p.s[0]*b,p.s[1]*b,p.s[2]*b);group.current.rotation.set(p.r[0],p.r[1]+(reducedMotion?0:Math.sin(t*.92)*.13),p.r[2]);if(inside.current&&!reducedMotion)inside.current.rotation.y=p.inner+Math.sin(t*1.7)*.34});return <group ref={group} name="home-v223-connected-open-cleft-living-memory-presence" position={ORB} onClick={e=>{e.stopPropagation();onOpen()}}><mesh geometry={outer} castShadow receiveShadow><meshStandardMaterial vertexColors roughness={.96} metalness={0} flatShading emissive={state==='warning'?'#59231c':'#102c24'} emissiveIntensity={state==='warning'?.2:.04}/></mesh><mesh ref={inside} geometry={inner} scale={[.69,.69,.69]} rotation={[.12,p.inner,-.08]}><meshStandardMaterial vertexColors roughness={.92} metalness={0} flatShading emissive="#17483a" emissiveIntensity={state==='dormant'?.03:.14}/></mesh><pointLight color={state==='warning'?'#c45b42':'#76b797'} intensity={state==='dormant'?.15:.7} distance={3.5} decay={2}/></group>}
