import { lifeMapNodes, type LifeMapNode } from "./lifeMapData";

export const quietResetDemoNode: LifeMapNode = {
  id: "quiet-reset",
  title: "The Quiet Reset",
  subtitle: "A private return through the memory field",
  type: "recovery",
  position: [0.2, 0.35, 1.3],
  intensity: 0.94,
  aura: "#8adfff",
  dateLabel: "May 9, 2026",
  replayAvailable: true,
  summary:
    "A calm recovery memory where pressure softened, perspective returned, and the next step became visible without exposing raw private content.",
  connectedTo: ["memory-thread", "recovery-bloom", "threshold-moment", "voice-note-home"],
  occurredAt: "2026-05-09T12:00:00.000Z",
  sourceType: "manual_seed",
  clusterId: "quiet-reset",
  eraId: "threshold-return",
  narratorHint: "This was the moment the noise lowered enough for you to return.",
  privacyLevel: "private",
  tags: ["sample", "recovery", "quiet-reset", "grounding", "calm-reflection", "confirmed"],
};

const authoredDemoNodes: LifeMapNode[] = [
  {
    id: "voice-note-home",
    title: "Voice Note at Home",
    subtitle: "A remembered tone before the words settled",
    type: "memory",
    position: [-3.55, 0.25, -0.65],
    intensity: 0.73,
    aura: "#82dcff",
    dateLabel: "Recent",
    replayAvailable: true,
    summary: "A privacy-safe sample of a voice memory represented through rhythm, tone, and timing rather than exposed transcript content.",
    connectedTo: ["quiet-reset", "home-place-fragment"],
    occurredAt: "2026-05-07T18:12:00.000Z",
    sourceType: "audio",
    clusterId: "recent-home",
    eraId: "spring-becoming",
    privacyLevel: "private",
    tags: ["sample", "audio", "voice", "confirmed"],
  },
  {
    id: "home-place-fragment",
    title: "The Room That Held",
    subtitle: "A place memory with quiet spatial gravity",
    type: "memory",
    position: [-4.85, -0.6, -2.45],
    intensity: 0.64,
    aura: "#7cc7df",
    dateLabel: "This Spring",
    replayAvailable: true,
    summary: "A sample place memory showing how environment, routine, and emotional safety can remain connected without exposing an address.",
    connectedTo: ["voice-note-home", "memory-thread"],
    occurredAt: "2026-04-26T20:10:00.000Z",
    sourceType: "manual_seed",
    clusterId: "recent-home",
    eraId: "spring-becoming",
    privacyLevel: "private",
    tags: ["sample", "place", "home", "confirmed"],
  },
  {
    id: "relationship-repair-orbit",
    title: "Repair in Motion",
    subtitle: "A relationship changing through small returns",
    type: "relationship",
    position: [4.45, 0.82, -3.1],
    intensity: 0.82,
    aura: "#d9efff",
    dateLabel: "Shared Orbit",
    replayAvailable: true,
    summary: "A disclosed relationship sample that represents repair, distance, and renewed trust without exposing a real person's identity.",
    connectedTo: ["relationship-echo", "quiet-reset", "future-bridge"],
    occurredAt: "2026-04-12T16:30:00.000Z",
    sourceType: "relationship",
    clusterId: "relationship-repair",
    eraId: "relationship-orbit",
    privacyLevel: "private",
    tags: ["sample", "relationship", "friendship", "repair", "confirmed"],
  },
  {
    id: "recurring-pressure-loop",
    title: "Pressure Loop",
    subtitle: "A repeated pattern becoming visible",
    type: "ritual",
    position: [1.95, -1.5, -1.55],
    intensity: 0.78,
    aura: "#be8cff",
    dateLabel: "Recurring",
    replayAvailable: false,
    summary: "A sample recurring pattern rendered as a loop that can be confirmed, corrected, or rejected rather than treated as fixed truth.",
    connectedTo: ["threshold-moment", "quiet-reset", "active-goal-structure"],
    occurredAt: "2026-03-18T12:00:00.000Z",
    sourceType: "system_generated",
    clusterId: "pressure-loop",
    eraId: "threshold-return",
    privacyLevel: "private",
    tags: ["sample", "pattern", "recurring", "inferred"],
  },
  {
    id: "earned-ground-monument",
    title: "Ground Reclaimed",
    subtitle: "A major achievement integrated into the story",
    type: "threshold",
    position: [-6.15, -1.15, -5.6],
    intensity: 0.98,
    aura: "#f2d18a",
    dateLabel: "Milestone",
    replayAvailable: true,
    summary: "A sample achievement that appears as a durable monument rather than a temporary badge or celebration card.",
    connectedTo: ["legacy-thread", "active-goal-structure"],
    occurredAt: "2026-01-14T12:00:00.000Z",
    sourceType: "manual_seed",
    clusterId: "earned-ground",
    eraId: "spring-becoming",
    privacyLevel: "shareable",
    tags: ["sample", "achievement", "milestone", "earned", "confirmed"],
  },
  {
    id: "active-goal-structure",
    title: "Build the Next Room",
    subtitle: "An active goal with visible scaffolding",
    type: "forecast",
    position: [5.7, 1.45, -8.65],
    intensity: 0.88,
    aura: "#f4d698",
    dateLabel: "In Progress",
    replayAvailable: false,
    summary: "A sample active goal whose structure becomes more complete as evidence, commitments, and next actions become clearer.",
    connectedTo: ["earned-ground-monument", "future-bridge", "recurring-pressure-loop"],
    occurredAt: "2026-05-20T12:00:00.000Z",
    sourceType: "forecast",
    clusterId: "future-build",
    eraId: "forward-weather",
    privacyLevel: "private",
    tags: ["sample", "goal", "active-goal", "commitment", "confirmed"],
  },
  {
    id: "future-bridge",
    title: "Possible Future",
    subtitle: "A path that remains open rather than predicted",
    type: "forecast",
    position: [1.1, 3.35, -12.4],
    intensity: 0.6,
    aura: "#e4c59c",
    dateLabel: "Possible",
    replayAvailable: false,
    locked: true,
    summary: "A disclosed future possibility rendered as evolving architecture and explicitly not presented as destiny or prediction.",
    connectedTo: ["active-goal-structure", "relationship-repair-orbit"],
    occurredAt: "2026-06-01T12:00:00.000Z",
    sourceType: "forecast",
    clusterId: "future-build",
    eraId: "forward-weather",
    privacyLevel: "hidden",
    tags: ["sample", "future", "possibility", "protected"],
  },
  {
    id: "sealed-private-chapter",
    title: "Protected Chapter",
    subtitle: "Content remains sealed until the owner opens it",
    type: "legacy",
    position: [-5.65, 0.2, -10.8],
    intensity: 0.84,
    aura: "#8d74ad",
    dateLabel: "Private",
    replayAvailable: false,
    locked: true,
    summary: "This sample proves the protected state without exposing a title, person, evidence, thumbnail, transcript, or inferred private detail in the rendered world.",
    connectedTo: ["legacy-thread"],
    occurredAt: "2025-09-11T12:00:00.000Z",
    sourceType: "legacy",
    clusterId: "sealed-chapter",
    eraId: "forward-weather",
    privacyLevel: "hidden",
    tags: ["sample", "protected", "sealed", "private-vault"],
  },
];

const enrichedBaseNodes = lifeMapNodes.map((node) => {
  if (node.id === "memory-thread") return { ...node, tags: [...(node.tags || []), "photo", "visual", "confirmed"] };
  if (node.id === "relationship-echo") return { ...node, tags: [...(node.tags || []), "relationship", "inferred"] };
  if (node.id === "legacy-thread") return { ...node, tags: [...(node.tags || []), "archive", "deep-time", "confirmed"] };
  if (node.id === "threshold-moment") return { ...node, tags: [...(node.tags || []), "emotion", "turning-point", "confirmed"] };
  if (node.id === "recovery-bloom") return { ...node, tags: [...(node.tags || []), "emotion", "repair", "confirmed"] };
  if (node.id === "ritual-marker") return { ...node, tags: [...(node.tags || []), "pattern", "habit", "confirmed"] };
  return node;
});

export const canonicalLifeMapDemoNodes: LifeMapNode[] = [
  quietResetDemoNode,
  ...enrichedBaseNodes.filter((node) => node.id !== quietResetDemoNode.id),
  ...authoredDemoNodes,
];
