export const MEMORY_WORLD_ONTOLOGY_VERSION = 'urai-memory-world-ontology-1' as const

export type MemoryWorldSceneDomain = 'residential' | 'childhood' | 'education' | 'work' | 'healthcare' | 'spiritual' | 'communityCivicRetail' | 'transportation' | 'foodHospitality' | 'sportRecreation' | 'artsEntertainment' | 'nature' | 'agricultureRural' | 'industryInfrastructure' | 'militaryPublicSafety' | 'migrationDiaspora' | 'lifeEvents' | 'agingGrief' | 'everydayTransitional' | 'historicalHeritage' | 'disasterRecovery' | 'justiceInstitutional' | 'travel'

export type FoundationalSceneArchetype = {
  id: string
  domain: MemoryWorldSceneDomain
  variant: string
  status: 'ontology-only' | 'reference-ready' | 'production-ready' | 'gold' | 'gold-master'
}

const DOMAIN_VARIANTS = {
  "residential": [
    "detached-house",
    "attached-house",
    "row-house",
    "townhouse",
    "duplex",
    "courtyard-house",
    "apartment-lowrise",
    "apartment-highrise",
    "walk-up",
    "housing-estate",
    "compound",
    "farmhouse",
    "ranch-house",
    "cottage",
    "cabin",
    "mobile-home",
    "manufactured-home",
    "stilt-house",
    "houseboat",
    "communal-housing",
    "multigenerational-compound",
    "student-housing",
    "temporary-shelter",
    "informal-self-built-home",
    "villa",
    "mansion",
    "retirement-residence",
    "entrance",
    "hallway",
    "living-room",
    "family-room",
    "parlor",
    "kitchen",
    "dining-room",
    "pantry",
    "adult-bedroom",
    "child-bedroom",
    "shared-bedroom",
    "nursery",
    "bathroom",
    "laundry-room",
    "home-yard"
  ],
  "childhood": [
    "daycare",
    "preschool",
    "child-classroom",
    "school-hallway",
    "school-cafeteria",
    "playground",
    "school-bus",
    "childhood-bedroom",
    "grandparents-home",
    "backyard-play",
    "neighborhood-play",
    "treehouse",
    "blanket-fort",
    "creek-or-woods",
    "summer-camp",
    "arcade",
    "amusement-park",
    "sleepover"
  ],
  "education": [
    "elementary-classroom",
    "secondary-classroom",
    "lecture-hall",
    "science-lab",
    "computer-lab",
    "art-room",
    "music-room",
    "vocational-shop",
    "gymnasium",
    "school-library",
    "school-cafeteria",
    "administrative-office",
    "university-campus",
    "dormitory",
    "student-commons",
    "graduation-venue",
    "school-yard",
    "study-hall"
  ],
  "work": [
    "private-office",
    "open-office",
    "cubicle-office",
    "home-office",
    "reception",
    "conference-room",
    "retail-counter",
    "restaurant-kitchen",
    "warehouse",
    "factory-floor",
    "assembly-line",
    "auto-garage",
    "construction-site",
    "woodworking-shop",
    "welding-shop",
    "machine-shop",
    "farm-work",
    "ranch-work",
    "laboratory-work",
    "salon-or-barber",
    "caregiving-work",
    "street-vending"
  ],
  "healthcare": [
    "doctor-office",
    "clinic",
    "waiting-room",
    "exam-room",
    "emergency-department",
    "ambulance-interior",
    "hospital-ward",
    "hospital-room",
    "icu-context",
    "rehabilitation-room",
    "physical-therapy",
    "mental-health-consultation",
    "assisted-living",
    "hospice"
  ],
  "spiritual": [
    "congregational-worship",
    "private-prayer",
    "household-shrine",
    "temple-or-shrine",
    "meditation-space",
    "religious-procession",
    "pilgrimage-context",
    "religious-festival",
    "religious-feast",
    "cemetery-or-burial",
    "spiritual-landscape",
    "religious-education"
  ],
  "communityCivicRetail": [
    "neighborhood-street",
    "village-lane",
    "downtown-street",
    "plaza",
    "town-square",
    "open-market",
    "bazaar",
    "supermarket",
    "corner-shop",
    "convenience-store",
    "shopping-mall",
    "department-store",
    "barber-shop",
    "beauty-salon",
    "laundromat",
    "bank",
    "post-office",
    "public-library",
    "museum",
    "community-center",
    "courthouse",
    "public-office",
    "city-park",
    "fairground"
  ],
  "transportation": [
    "sedan-interior",
    "coupe-interior",
    "pickup-interior",
    "suv-interior",
    "van-interior",
    "minivan-interior",
    "motorcycle-context",
    "bicycle-context",
    "scooter-context",
    "school-bus-interior",
    "city-bus-interior",
    "intercity-coach",
    "subway-car",
    "metro-platform",
    "commuter-train",
    "long-distance-train",
    "tram",
    "ferry",
    "boat",
    "taxi-or-rideshare",
    "shared-minibus",
    "tuk-tuk-context",
    "aircraft-cabin",
    "train-station"
  ],
  "foodHospitality": [
    "home-meal",
    "cafe",
    "diner",
    "restaurant",
    "fast-food",
    "cafeteria",
    "bar-context",
    "food-stall",
    "market-food-area",
    "commercial-kitchen",
    "hotel-room",
    "hotel-lobby",
    "motel",
    "hostel",
    "temporary-lodging"
  ],
  "sportRecreation": [
    "sports-field",
    "court",
    "gym",
    "pool",
    "rink",
    "stadium",
    "arena",
    "fishing-location",
    "hunting-context",
    "hiking-trail",
    "camping-site",
    "recreation-center",
    "dance-space",
    "martial-arts-space"
  ],
  "artsEntertainment": [
    "cinema",
    "theater",
    "concert-venue",
    "festival-stage",
    "nightlife-event",
    "rehearsal-room",
    "recording-studio",
    "gallery",
    "art-studio",
    "performance-stage"
  ],
  "nature": [
    "temperate-forest",
    "tropical-forest",
    "boreal-forest",
    "woodland",
    "grassland",
    "savanna",
    "desert",
    "scrubland",
    "tundra",
    "mountain",
    "foothills",
    "valley",
    "river",
    "creek",
    "lake",
    "pond",
    "wetland",
    "coast",
    "beach",
    "island"
  ],
  "agricultureRural": [
    "crop-field",
    "pasture",
    "barn",
    "ranch-yard",
    "stable",
    "orchard",
    "vineyard",
    "greenhouse",
    "livestock-area",
    "rural-homestead"
  ],
  "industryInfrastructure": [
    "industrial-factory",
    "industrial-warehouse",
    "port",
    "construction-infrastructure",
    "utility-site",
    "machine-shop-industrial",
    "mine",
    "energy-site",
    "service-yard",
    "logistics-facility"
  ],
  "militaryPublicSafety": [
    "barracks",
    "base-housing",
    "training-environment",
    "motor-pool",
    "military-admin",
    "field-environment",
    "fire-station",
    "emergency-response-staging"
  ],
  "migrationDiaspora": [
    "departure-home",
    "migration-terminal",
    "border-transit",
    "temporary-accommodation",
    "arrival-neighborhood",
    "first-home-after-move",
    "family-reunion"
  ],
  "lifeEvents": [
    "birthday",
    "wedding",
    "engagement",
    "anniversary",
    "graduation",
    "birth-family-context",
    "family-reunion-event",
    "retirement",
    "holiday-meal",
    "festival-gathering",
    "first-day-school",
    "first-job",
    "moving-house",
    "vacation"
  ],
  "agingGrief": [
    "family-bedside",
    "assisted-living-memory",
    "memorial",
    "wake",
    "funeral-context",
    "cemetery-visit",
    "remembrance-gathering"
  ],
  "everydayTransitional": [
    "hallway-transition",
    "elevator",
    "stairwell",
    "generic-waiting-room",
    "sidewalk",
    "parking-lot",
    "porch",
    "bus-stop",
    "driveway",
    "break-room",
    "checkout-line",
    "back-seat-car"
  ],
  "historicalHeritage": [
    "historic-domestic-interior",
    "historic-street",
    "historic-school",
    "historic-workplace",
    "heritage-site",
    "period-transport"
  ],
  "disasterRecovery": [
    "evacuation-shelter",
    "storm-aftermath",
    "flood-recovery",
    "fire-recovery",
    "community-rebuilding"
  ],
  "justiceInstitutional": [
    "courtroom",
    "detention-visitation",
    "administrative-hearing",
    "institutional-corridor"
  ],
  "travel": [
    "airport-terminal",
    "ferry-terminal",
    "road-trip-stop",
    "vacation-rental",
    "resort",
    "campsite-travel",
    "rail-journey",
    "walking-tour-context"
  ]
} as const

export const FOUNDATIONAL_SCENE_ARCHETYPES: readonly FoundationalSceneArchetype[] = Object.entries(DOMAIN_VARIANTS)
  .flatMap(([domain, variants]) =>
    variants.map((variant) => ({
      id: `scene:${domain}:${variant}`,
      domain: domain as MemoryWorldSceneDomain,
      variant,
      status: 'ontology-only' as const,
    })),
  )

export const FOUNDATIONAL_ARCHETYPE_TARGET_RANGE = {
  minimum: 300,
  preferred: 320,
  maximum: 350,
} as const

export const FOUNDATIONAL_ARCHETYPE_COUNT = FOUNDATIONAL_SCENE_ARCHETYPES.length

export const MEMORY_WORLD_LIBRARY_TARGETS = {
  mvp: {
    sceneArchetypes: 25,
    residentialArchitectureFamilies: 12,
    publicBuildingFamilies: 8,
    streetUrbanFormFamilies: 8,
    biomeEnvironmentFamilies: 10,
    eraPacks: 6,
    semanticObjectArchetypes: 500,
    objectVariants: 1200,
    furnitureVariants: 180,
    applianceElectronicVariants: 120,
    transportationVariants: 80,
    vegetationAssets: 160,
    materialFamilies: 80,
    lightingPresets: 60,
    weatherAtmosphereConfigurations: 40,
    spatialSoundComponents: 120,
    eventActivityTemplates: 80,
  },
  phase2: {
    sceneArchetypes: 120,
    residentialArchitectureFamilies: 60,
    publicBuildingFamilies: 30,
    streetUrbanFormFamilies: 35,
    biomeEnvironmentFamilies: 25,
    eraPacks: 10,
    semanticObjectArchetypes: 3500,
    objectVariants: 9000,
    furnitureVariants: 800,
    applianceElectronicVariants: 450,
    transportationVariants: 350,
    vegetationAssets: 800,
    materialFamilies: 250,
    lightingPresets: 220,
    weatherAtmosphereConfigurations: 140,
    spatialSoundComponents: 450,
    eventActivityTemplates: 240,
  },
  mature: {
    sceneArchetypes: 324,
    residentialArchitectureFamilies: 150,
    publicBuildingFamilies: 60,
    streetUrbanFormFamilies: 80,
    biomeEnvironmentFamilies: 40,
    eraPacks: 14,
    semanticObjectArchetypes: 10000,
    objectVariants: 30000,
    furnitureVariants: 2000,
    applianceElectronicVariants: 1000,
    transportationVariants: 1000,
    vegetationAssets: 2000,
    materialFamilies: 500,
    lightingPresets: 500,
    weatherAtmosphereConfigurations: 300,
    spatialSoundComponents: 1000,
    eventActivityTemplates: 500,
  },
} as const

export function sceneArchetypesForDomain(domain: MemoryWorldSceneDomain) {
  return FOUNDATIONAL_SCENE_ARCHETYPES.filter((scene) => scene.domain === domain)
}

export function hasFoundationalArchetype(id: string) {
  return FOUNDATIONAL_SCENE_ARCHETYPES.some((scene) => scene.id === id)
}
