import type { SpatialFeatureId, UraiTier } from './types'

export type SafetyClass = 'baseline' | 'personal' | 'premium' | 'admin'

export interface FeatureMatrixEntry {
  featureId: SpatialFeatureId
  requiredTier: UraiTier
  requiredFeatureFlags: string[]
  requiredConsents: string[]
  requiresAuth: boolean
  requiresServerCheck: boolean
  safetyClass: SafetyClass
  fallbackFeature: SpatialFeatureId
  telemetryEvent: string
  defaultEnabledInStaging: boolean
  defaultEnabledInProduction: boolean
}

export const SPATIAL_FEATURE_MATRIX: Record<SpatialFeatureId, FeatureMatrixEntry> = {
  'spatial.home.sky': { featureId: 'spatial.home.sky', requiredTier: 'tier1', requiredFeatureFlags: ['spatial_home_sky'], requiredConsents: [], requiresAuth: false, requiresServerCheck: false, safetyClass: 'baseline', fallbackFeature: 'spatial.home.sky', telemetryEvent: 'spatial_home_sky_rendered', defaultEnabledInStaging: true, defaultEnabledInProduction: true },
  'spatial.weather.basic': { featureId: 'spatial.weather.basic', requiredTier: 'tier1', requiredFeatureFlags: ['spatial_weather_basic'], requiredConsents: [], requiresAuth: false, requiresServerCheck: false, safetyClass: 'baseline', fallbackFeature: 'spatial.home.sky', telemetryEvent: 'spatial_weather_basic_rendered', defaultEnabledInStaging: true, defaultEnabledInProduction: true },
  'spatial.starfield.preview': { featureId: 'spatial.starfield.preview', requiredTier: 'tier1', requiredFeatureFlags: ['spatial_starfield_preview'], requiredConsents: [], requiresAuth: false, requiresServerCheck: false, safetyClass: 'baseline', fallbackFeature: 'spatial.home.sky', telemetryEvent: 'spatial_starfield_preview_rendered', defaultEnabledInStaging: true, defaultEnabledInProduction: true },
  'spatial.lifeMap.personal': { featureId: 'spatial.lifeMap.personal', requiredTier: 'tier2', requiredFeatureFlags: ['spatial_lifemap_personal'], requiredConsents: ['privacy.core', 'spatial.personalization'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'personal', fallbackFeature: 'spatial.starfield.preview', telemetryEvent: 'spatial_lifemap_personal_rendered', defaultEnabledInStaging: true, defaultEnabledInProduction: false },
  'spatial.memoryStars.personal': { featureId: 'spatial.memoryStars.personal', requiredTier: 'tier2', requiredFeatureFlags: ['spatial_memory_stars_personal'], requiredConsents: ['privacy.core', 'spatial.personalization'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'personal', fallbackFeature: 'spatial.starfield.preview', telemetryEvent: 'spatial_memory_stars_rendered', defaultEnabledInStaging: true, defaultEnabledInProduction: false },
  'spatial.companion.visual': { featureId: 'spatial.companion.visual', requiredTier: 'tier2', requiredFeatureFlags: ['spatial_companion_visual'], requiredConsents: ['privacy.core', 'spatial.companion'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'personal', fallbackFeature: 'spatial.starfield.preview', telemetryEvent: 'spatial_companion_visual_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.ritual.preview': { featureId: 'spatial.ritual.preview', requiredTier: 'tier2', requiredFeatureFlags: ['spatial_ritual_preview'], requiredConsents: ['privacy.core'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'personal', fallbackFeature: 'spatial.starfield.preview', telemetryEvent: 'spatial_ritual_preview_rendered', defaultEnabledInStaging: true, defaultEnabledInProduction: false },
  'spatial.ritual.interactive': { featureId: 'spatial.ritual.interactive', requiredTier: 'tier3', requiredFeatureFlags: ['spatial_ritual_interactive'], requiredConsents: ['privacy.core', 'spatial.interactive'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'premium', fallbackFeature: 'spatial.ritual.preview', telemetryEvent: 'spatial_ritual_interactive_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.dreamPlanetarium': { featureId: 'spatial.dreamPlanetarium', requiredTier: 'tier3', requiredFeatureFlags: ['spatial_dream_planetarium'], requiredConsents: ['privacy.core', 'spatial.personalization'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'premium', fallbackFeature: 'spatial.lifeMap.personal', telemetryEvent: 'spatial_dream_planetarium_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.lifeMuseum': { featureId: 'spatial.lifeMuseum', requiredTier: 'tier3', requiredFeatureFlags: ['spatial_life_museum'], requiredConsents: ['privacy.core', 'spatial.personalization'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'premium', fallbackFeature: 'spatial.lifeMap.personal', telemetryEvent: 'spatial_life_museum_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.seasonTunnel': { featureId: 'spatial.seasonTunnel', requiredTier: 'tier3', requiredFeatureFlags: ['spatial_season_tunnel'], requiredConsents: ['privacy.core'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'premium', fallbackFeature: 'spatial.lifeMap.personal', telemetryEvent: 'spatial_season_tunnel_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.xr.roomMapping': { featureId: 'spatial.xr.roomMapping', requiredTier: 'tier3', requiredFeatureFlags: ['spatial_xr_room_mapping'], requiredConsents: ['privacy.core', 'spatial.xr'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'premium', fallbackFeature: 'spatial.home.sky', telemetryEvent: 'spatial_xr_room_mapping_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.vr.memoryRoom': { featureId: 'spatial.vr.memoryRoom', requiredTier: 'tier3', requiredFeatureFlags: ['spatial_vr_memory_room'], requiredConsents: ['privacy.core', 'spatial.xr'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'premium', fallbackFeature: 'spatial.home.sky', telemetryEvent: 'spatial_vr_memory_room_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.marketplace.freeAssets': { featureId: 'spatial.marketplace.freeAssets', requiredTier: 'tier2', requiredFeatureFlags: ['spatial_marketplace_free_assets'], requiredConsents: ['privacy.core'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'personal', fallbackFeature: 'spatial.home.sky', telemetryEvent: 'spatial_marketplace_free_assets_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.marketplace.paidAssets': { featureId: 'spatial.marketplace.paidAssets', requiredTier: 'tier3', requiredFeatureFlags: ['spatial_marketplace_paid_assets'], requiredConsents: ['privacy.core', 'commerce.terms'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'premium', fallbackFeature: 'spatial.marketplace.freeAssets', telemetryEvent: 'spatial_marketplace_paid_assets_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.exports.card': { featureId: 'spatial.exports.card', requiredTier: 'tier2', requiredFeatureFlags: ['spatial_exports_card'], requiredConsents: ['privacy.core'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'personal', fallbackFeature: 'spatial.home.sky', telemetryEvent: 'spatial_exports_card_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.exports.story': { featureId: 'spatial.exports.story', requiredTier: 'tier3', requiredFeatureFlags: ['spatial_exports_story'], requiredConsents: ['privacy.core'], requiresAuth: true, requiresServerCheck: true, safetyClass: 'premium', fallbackFeature: 'spatial.exports.card', telemetryEvent: 'spatial_exports_story_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
  'spatial.admin.inspectLocks': { featureId: 'spatial.admin.inspectLocks', requiredTier: 'tier3', requiredFeatureFlags: ['spatial_admin_inspect_locks'], requiredConsents: [], requiresAuth: true, requiresServerCheck: true, safetyClass: 'admin', fallbackFeature: 'spatial.home.sky', telemetryEvent: 'spatial_admin_inspect_locks_rendered', defaultEnabledInStaging: false, defaultEnabledInProduction: false },
}

export const TIER_ORDER: Record<UraiTier, number> = { tier1: 1, tier2: 2, tier3: 3 }
