import type { UraiLaunchLocale, UraiMessageDefinition } from './locales'

// English source copy is authoritative. The other nineteen rows are machine-prepared
// review material, available only through the existing explicit translation preview.
// This catalog does not admit a locale or translate private memory/provider output.
export const URAI_JOURNEY_MESSAGES = {
  'home.destinations': { id:'home.destinations', source:"Accessible Home destinations", sensitivity:'general', description:"Accessible destination navigation in Home" },
  'home.orbAction': { id:'home.orbAction', source:"Open URAI Orb companion", sensitivity:'general', description:"Open the anchored Orb companion" },
  'nav.ground': { id:'nav.ground', source:"Ground", sensitivity:'general', description:"Ground destination label" },
  'home.groundAction': { id:'home.groundAction', source:"Open Ground directly", sensitivity:'general', description:"Accessible Ground destination" },
  'home.webglUnavailable': { id:'home.webglUnavailable', source:"WebGL is unavailable. Accessible Home controls remain available.", sensitivity:'general', description:"Home WebGL fallback status" },
  'home.assetsUnavailable': { id:'home.assetsUnavailable', source:"Home assets could not load. Accessible Home controls remain available.", sensitivity:'general', description:"Home asset failure status" },
  'home.rendererUnavailable': { id:'home.rendererUnavailable', source:"The spatial renderer could not recover. Accessible Home controls remain available.", sensitivity:'general', description:"Home renderer failure status" },
  'home.retry': { id:'home.retry', source:"Retry loading Home", sensitivity:'general', description:"Retry Home assets without changing source authority" },
  'home.restoring': { id:'home.restoring', source:"Restoring the spatial Home renderer.", sensitivity:'general', description:"Bounded renderer recovery status" },
  'home.forming': { id:'home.forming', source:"Your private world is forming", sensitivity:'privacy', description:"Existing private-world loading heading; reviewed fallback applies even during preview" },
  'ascent.progress': { id:'ascent.progress', source:"Ascending through the sky", sensitivity:'general', description:"Canonical Home-to-Life-Map camera ascent context" },
  'home.groundProgress': { id:'home.groundProgress', source:"Descending into Ground", sensitivity:'general', description:"Canonical Ground descent context" },
  'home.orbNearby': { id:'home.orbNearby', source:"The Orb is here", sensitivity:'general', description:"Nearby Orb context" },
  'home.groundNearby': { id:'home.groundNearby', source:"The path descends", sensitivity:'general', description:"Nearby Ground path context" },
  'home.skyNearby': { id:'home.skyNearby', source:"Look to the sky", sensitivity:'general', description:"Nearby Life Map sky context" },
  'lifeMap.opening': { id:'lifeMap.opening', source:"Opening constellation…", sensitivity:'general', description:"Life Map search loading status" },
  'lifeMap.noResults': { id:'lifeMap.noResults', source:"No life objects match these filters.", sensitivity:'general', description:"Life Map search empty state" },
  'lifeMap.enterFocus': { id:'lifeMap.enterFocus', source:"Enter Focus", sensitivity:'general', description:"Life Map selected memory Focus action" },
  'lifeMap.searchHint': { id:'lifeMap.searchHint', source:"Search memories, people, places…", sensitivity:'general', description:"Life Map search placeholder" },
  'focus.heading': { id:'focus.heading', source:"Focus Memory Star", sensitivity:'general', description:"Direct Focus entry heading" },
  'focus.resting': { id:'focus.resting', source:"Memory star resting", sensitivity:'general', description:"Empty Focus heading" },
  'focus.chooseMemory': { id:'focus.chooseMemory', source:"Choose a star in Life Map to enter the stellar memory field where that memory is held.", sensitivity:'general', description:"Direct Focus entry instructions" },
  'focus.instructions': { id:'focus.instructions', source:"Drag to orbit. Scroll or pinch to move through depth. Use W A S D or arrow keys to travel. Recenter restores the arrival view. Escape returns to Life Map.", sensitivity:'general', description:"Focus input instructions" },
  'focus.preparing': { id:'focus.preparing', source:"Preparing stellar memory field…", sensitivity:'general', description:"Focus WebGL capability loading" },
  'focus.opening': { id:'focus.opening', source:"Opening stellar memory field…", sensitivity:'general', description:"Focus scene loading" },
  'common.spatialUnavailable': { id:'common.spatialUnavailable', source:"Spatial view unavailable", sensitivity:'general', description:"Accessible spatial failure heading" },
  'common.spatialAccessible': { id:'common.spatialAccessible', source:"The memory remains accessible through the controls and memory details.", sensitivity:'general', description:"Accessible controls and details fallback" },
  'focus.ready': { id:'focus.ready', source:"Stellar memory field ready", sensitivity:'general', description:"Ready Focus status" },
  'focus.neutral': { id:'focus.neutral', source:"Neutral stellar field", sensitivity:'general', description:"Neutral Focus status" },
  'focus.openingSelected': { id:'focus.openingSelected', source:"Opening selected memory", sensitivity:'general', description:"Selected memory loading status" },
  'replay.checkingSpatial': { id:'replay.checkingSpatial', source:"Checking spatial view…", sensitivity:'general', description:"Replay WebGL capability loading" },
  'replay.retrySpatial': { id:'replay.retrySpatial', source:"Retry spatial view", sensitivity:'general', description:"Replay spatial renderer retry" },
  'replay.pause': { id:'replay.pause', source:"Pause memory", sensitivity:'general', description:"Replay playback pause action" },
  'replay.continue': { id:'replay.continue', source:"Continue memory", sensitivity:'general', description:"Replay playback continue action" },
  'replay.horizon': { id:'replay.horizon', source:"Memory horizon", sensitivity:'general', description:"Replay neutral horizon heading" },
  'replay.opening': { id:'replay.opening', source:"Opening memory field", sensitivity:'general', description:"Replay neutral loading status" },
  'replay.comingIntoView': { id:'replay.comingIntoView', source:"A memory is coming into view.", sensitivity:'general', description:"Replay neutral loading heading" },
  'replay.choosePrompt': { id:'replay.choosePrompt', source:"Choose a memory to enter Replay.", sensitivity:'general', description:"Replay empty entry instructions" },
  'replay.chooseMemory': { id:'replay.chooseMemory', source:"Choose a memory", sensitivity:'general', description:"Replay Life Map selection action" },
  'common.offline': { id:'common.offline', source:"You are offline. Reconnect to load experiences that need the network.", sensitivity:'general', description:"Actual browser network state; not a provider or data-retention claim" },
  'focus.title': { id:'focus.title', source:"URAI Focus stellar memory field", sensitivity:'general', description:"Focus accessible route heading" },
  'home.label': { id:'home.label', source:"URAI living spatial Home", sensitivity:'general', description:"Canonical Home accessible scene label" },
  'focus.loading': { id:'focus.loading', source:'Loading', sensitivity:'general', description:'Existing short Focus loading label' },
  'replay.spatialUnavailable': { id:'replay.spatialUnavailable', source:'Spatial view unavailable. Memory details and controls remain accessible.', sensitivity:'general', description:'Existing Replay spatial fallback status' },
} as const satisfies Record<string, UraiMessageDefinition>

export type UraiJourneyMessageId = keyof typeof URAI_JOURNEY_MESSAGES
const ids = Object.keys(URAI_JOURNEY_MESSAGES) as UraiJourneyMessageId[]
const rows = {
  en: ids.map(id => URAI_JOURNEY_MESSAGES[id].source),
  'zh-Hans': ["可访问的首页目的地","打开 URAI Orb 伙伴","地面","直接打开地面","WebGL 不可用。首页的无障碍控件仍可使用。","首页资源无法加载。首页的无障碍控件仍可使用。","空间渲染器未能恢复。首页的无障碍控件仍可使用。","重新加载首页","正在恢复空间首页渲染器。","你的私人世界正在形成","穿过天空上升","向下进入地面","Orb 在这里","小径向下延伸","望向天空","正在打开星座…","没有生命对象符合这些筛选条件。","进入聚焦","搜索记忆、人物、地点…","聚焦记忆星","记忆星正在静候","在生命地图中选择一颗星，进入承载那段记忆的恒星记忆场。","拖动以环绕查看。滚动或捏合以改变深度。使用 W A S D 或方向键移动。重新居中可恢复到达时的视角。Escape 返回生命地图。","正在准备恒星记忆场…","正在打开恒星记忆场…","空间视图不可用","仍可通过控件和记忆详情访问这段记忆。","恒星记忆场已就绪","中性恒星场","正在打开所选记忆","正在检查空间视图…","重试空间视图","暂停记忆","继续记忆","记忆地平线","正在打开记忆场","一段记忆正逐渐呈现。","选择一段记忆以进入回放。","选择记忆","你处于离线状态。请重新连接以加载需要网络的体验。","URAI 聚焦恒星记忆场","URAI 鲜活空间首页","加载中","空间视图不可用。记忆详情和控件仍可访问。"],
  'hi': ["सुलभ होम गंतव्य","URAI Orb साथी खोलें","ग्राउंड","ग्राउंड सीधे खोलें","WebGL उपलब्ध नहीं है। होम के सुलभ नियंत्रण उपलब्ध हैं।","होम की एसेट लोड नहीं हो सकीं। होम के सुलभ नियंत्रण उपलब्ध हैं।","स्थानिक रेंडरर बहाल नहीं हो सका। होम के सुलभ नियंत्रण उपलब्ध हैं।","होम लोड करने का फिर प्रयास करें","स्थानिक होम रेंडरर बहाल हो रहा है।","आपका निजी संसार आकार ले रहा है","आकाश में ऊपर जा रहे हैं","ग्राउंड की ओर नीचे जा रहे हैं","Orb यहाँ है","पथ नीचे जाता है","आकाश की ओर देखें","तारामंडल खुल रहा है…","इन फ़िल्टर से कोई जीवन वस्तु मेल नहीं खाती।","फोकस में जाएँ","यादें, लोग, स्थान खोजें…","फोकस स्मृति तारा","स्मृति तारा विश्राम में है","जीवन मानचित्र में एक तारा चुनें और उस तारकीय स्मृति क्षेत्र में जाएँ जहाँ वह याद रखी गई है।","चारों ओर देखने के लिए खींचें। गहराई बदलने के लिए स्क्रॉल करें या पिंच करें। चलने के लिए W A S D या तीर कुंजियाँ इस्तेमाल करें। फिर से केंद्रित करें आगमन दृश्य को बहाल करता है। Escape से जीवन मानचित्र पर लौटें।","तारकीय स्मृति क्षेत्र तैयार हो रहा है…","तारकीय स्मृति क्षेत्र खुल रहा है…","स्थानिक दृश्य उपलब्ध नहीं है","नियंत्रण और स्मृति विवरण से याद अब भी उपलब्ध है।","तारकीय स्मृति क्षेत्र तैयार है","तटस्थ तारकीय क्षेत्र","चुनी गई याद खुल रही है","स्थानिक दृश्य की जाँच हो रही है…","स्थानिक दृश्य का फिर प्रयास करें","याद रोकें","याद जारी रखें","स्मृति क्षितिज","स्मृति क्षेत्र खुल रहा है","एक याद सामने आ रही है।","रीप्ले में जाने के लिए एक याद चुनें।","एक याद चुनें","आप ऑफ़लाइन हैं। नेटवर्क वाली अनुभवों को लोड करने के लिए फिर से जुड़ें।","URAI फोकस तारकीय स्मृति क्षेत्र","URAI जीवंत स्थानिक होम","लोड हो रहा है","स्थानिक दृश्य उपलब्ध नहीं है। स्मृति विवरण और नियंत्रण अब भी उपलब्ध हैं।"],
  'es': ["Destinos accesibles de Inicio","Abrir el compañero Orb de URAI","Suelo","Abrir Suelo directamente","WebGL no está disponible. Los controles accesibles de Inicio siguen disponibles.","No se pudieron cargar los recursos de Inicio. Los controles accesibles siguen disponibles.","El renderizador espacial no pudo recuperarse. Los controles accesibles de Inicio siguen disponibles.","Volver a cargar Inicio","Restaurando el renderizador espacial de Inicio.","Tu mundo privado está tomando forma","Ascendiendo por el cielo","Descendiendo a Suelo","El Orb está aquí","El camino desciende","Mira al cielo","Abriendo la constelación…","Ningún objeto de vida coincide con estos filtros.","Entrar en Enfoque","Buscar recuerdos, personas, lugares…","Estrella de memoria de Enfoque","Estrella de memoria en reposo","Elige una estrella en el Mapa de vida para entrar en el campo estelar que contiene ese recuerdo.","Arrastra para orbitar. Desplázate o pellizca para moverte en profundidad. Usa W A S D o las flechas para viajar. Centrar de nuevo restaura la vista de llegada. Escape vuelve al Mapa de vida.","Preparando el campo estelar de memoria…","Abriendo el campo estelar de memoria…","Vista espacial no disponible","El recuerdo sigue accesible mediante los controles y sus detalles.","Campo estelar de memoria listo","Campo estelar neutro","Abriendo el recuerdo seleccionado","Comprobando la vista espacial…","Reintentar la vista espacial","Pausar recuerdo","Continuar recuerdo","Horizonte de memoria","Abriendo el campo de memoria","Un recuerdo está apareciendo.","Elige un recuerdo para entrar en Repetición.","Elegir un recuerdo","No tienes conexión. Vuelve a conectarte para cargar experiencias que necesitan la red.","Campo estelar de memoria de Enfoque de URAI","Inicio espacial vivo de URAI","Cargando","Vista espacial no disponible. Los detalles del recuerdo y los controles siguen accesibles."],
  'fr': ["Destinations accessibles de l’accueil","Ouvrir le compagnon Orb d’URAI","Sol","Ouvrir directement le Sol","WebGL est indisponible. Les commandes accessibles de l’accueil restent disponibles.","Les ressources de l’accueil n’ont pas pu être chargées. Les commandes accessibles restent disponibles.","Le moteur spatial n’a pas pu reprendre. Les commandes accessibles de l’accueil restent disponibles.","Réessayer le chargement de l’accueil","Restauration du moteur spatial de l’accueil.","Votre monde privé prend forme","Ascension à travers le ciel","Descente vers le Sol","L’Orb est ici","Le chemin descend","Regardez vers le ciel","Ouverture de la constellation…","Aucun objet de vie ne correspond à ces filtres.","Entrer dans la concentration","Rechercher des souvenirs, des personnes, des lieux…","Étoile de mémoire de la concentration","Étoile de mémoire au repos","Choisissez une étoile dans la Carte de vie pour entrer dans le champ stellaire où ce souvenir est conservé.","Faites glisser pour orbiter. Faites défiler ou pincez pour vous déplacer en profondeur. Utilisez W A S D ou les flèches pour vous déplacer. Recentrer rétablit la vue d’arrivée. Échap revient à la Carte de vie.","Préparation du champ stellaire de mémoire…","Ouverture du champ stellaire de mémoire…","Vue spatiale indisponible","Le souvenir reste accessible par les commandes et ses détails.","Champ stellaire de mémoire prêt","Champ stellaire neutre","Ouverture du souvenir sélectionné","Vérification de la vue spatiale…","Réessayer la vue spatiale","Mettre le souvenir en pause","Continuer le souvenir","Horizon de mémoire","Ouverture du champ de mémoire","Un souvenir apparaît.","Choisissez un souvenir pour entrer dans la relecture.","Choisir un souvenir","Vous êtes hors ligne. Reconnectez-vous pour charger les expériences qui nécessitent le réseau.","Champ stellaire de mémoire de la concentration d’URAI","Accueil spatial vivant d’URAI","Chargement","Vue spatiale indisponible. Les détails du souvenir et les commandes restent accessibles."],
  'ar': ["وجهات الرئيسية الميسّرة","فتح رفيق URAI Orb","الأرض","فتح الأرض مباشرة","WebGL غير متاح. تظل عناصر تحكم الرئيسية الميسّرة متاحة.","تعذر تحميل موارد الرئيسية. تظل عناصر التحكم الميسّرة متاحة.","تعذر استعادة العارض المكاني. تظل عناصر تحكم الرئيسية الميسّرة متاحة.","إعادة محاولة تحميل الرئيسية","جارٍ استعادة العارض المكاني للرئيسية.","عالمك الخاص يتشكل","الصعود عبر السماء","النزول إلى الأرض","Orb هنا","المسار ينحدر","انظر إلى السماء","جارٍ فتح الكوكبة…","لا توجد عناصر حياة تطابق هذه المرشحات.","الدخول إلى التركيز","البحث عن ذكريات وأشخاص وأماكن…","نجمة ذاكرة التركيز","نجمة الذاكرة في سكون","اختر نجمة في خريطة الحياة للدخول إلى حقل الذاكرة النجمي الذي يحمل تلك الذكرى.","اسحب للدوران. مرّر أو ضمّ إصبعين للتحرك في العمق. استخدم W A S D أو مفاتيح الأسهم للتنقل. تعيد إعادة التوسيط منظر الوصول. يعيد Escape إلى خريطة الحياة.","جارٍ إعداد حقل الذاكرة النجمي…","جارٍ فتح حقل الذاكرة النجمي…","العرض المكاني غير متاح","تظل الذكرى متاحة من خلال عناصر التحكم وتفاصيل الذاكرة.","حقل الذاكرة النجمي جاهز","حقل نجمي محايد","جارٍ فتح الذكرى المحددة","جارٍ التحقق من العرض المكاني…","إعادة محاولة العرض المكاني","إيقاف الذكرى مؤقتًا","متابعة الذكرى","أفق الذاكرة","جارٍ فتح حقل الذاكرة","ذكرى تظهر تدريجيًا.","اختر ذكرى للدخول إلى إعادة التشغيل.","اختيار ذكرى","أنت غير متصل. أعد الاتصال لتحميل التجارب التي تحتاج إلى الشبكة.","حقل الذاكرة النجمي للتركيز في URAI","الرئيسية المكانية الحية في URAI","جارٍ التحميل","العرض المكاني غير متاح. تظل تفاصيل الذاكرة وعناصر التحكم متاحة."],
  'bn': ["সহজপ্রবেশযোগ্য হোম গন্তব্য","URAI Orb সঙ্গী খুলুন","গ্রাউন্ড","গ্রাউন্ড সরাসরি খুলুন","WebGL উপলভ্য নয়। হোমের সহজপ্রবেশযোগ্য নিয়ন্ত্রণগুলি উপলভ্য রয়েছে।","হোমের উপকরণ লোড করা যায়নি। সহজপ্রবেশযোগ্য নিয়ন্ত্রণগুলি উপলভ্য রয়েছে।","স্থানিক রেন্ডারার পুনরুদ্ধার করা যায়নি। হোমের সহজপ্রবেশযোগ্য নিয়ন্ত্রণগুলি উপলভ্য রয়েছে।","হোম লোড করতে আবার চেষ্টা করুন","স্থানিক হোম রেন্ডারার পুনরুদ্ধার হচ্ছে।","আপনার ব্যক্তিগত জগৎ গড়ে উঠছে","আকাশ দিয়ে ওপরে উঠছে","গ্রাউন্ডের দিকে নিচে নামছে","Orb এখানে আছে","পথটি নিচে নেমে যায়","আকাশের দিকে তাকান","নক্ষত্রমণ্ডল খুলছে…","এই ফিল্টারগুলির সঙ্গে কোনও জীবন বস্তু মেলে না।","ফোকাসে প্রবেশ করুন","স্মৃতি, মানুষ, স্থান খুঁজুন…","ফোকাস স্মৃতি তারা","স্মৃতি তারা বিশ্রামে আছে","জীবন মানচিত্রে একটি তারা বেছে সেই স্মৃতি ধারণ করা নাক্ষত্রিক স্মৃতি ক্ষেত্রে প্রবেশ করুন।","চারদিকে দেখতে টেনে নিন। গভীরতায় চলতে স্ক্রল করুন বা দুই আঙুল দিয়ে পিঞ্চ করুন। চলতে W A S D বা তীর চাবি ব্যবহার করুন। আবার কেন্দ্রে আনুন আগমনের দৃশ্য ফিরিয়ে আনে। Escape জীবন মানচিত্রে ফেরায়।","নাক্ষত্রিক স্মৃতি ক্ষেত্র প্রস্তুত হচ্ছে…","নাক্ষত্রিক স্মৃতি ক্ষেত্র খুলছে…","স্থানিক দৃশ্য উপলভ্য নয়","নিয়ন্ত্রণ এবং স্মৃতির বিবরণ দিয়ে স্মৃতি এখনও পাওয়া যায়।","নাক্ষত্রিক স্মৃতি ক্ষেত্র প্রস্তুত","নিরপেক্ষ নাক্ষত্রিক ক্ষেত্র","বেছে নেওয়া স্মৃতি খুলছে","স্থানিক দৃশ্য যাচাই হচ্ছে…","স্থানিক দৃশ্যের জন্য আবার চেষ্টা করুন","স্মৃতি বিরতি দিন","স্মৃতি চালিয়ে যান","স্মৃতির দিগন্ত","স্মৃতি ক্ষেত্র খুলছে","একটি স্মৃতি দৃশ্যমান হচ্ছে।","রিপ্লেতে প্রবেশ করতে একটি স্মৃতি বেছে নিন।","একটি স্মৃতি বেছে নিন","আপনি অফলাইনে আছেন। নেটওয়ার্ক দরকার এমন অভিজ্ঞতা লোড করতে আবার সংযোগ করুন।","URAI ফোকাস নাক্ষত্রিক স্মৃতি ক্ষেত্র","URAI জীবন্ত স্থানিক হোম","লোড হচ্ছে","স্থানিক দৃশ্য উপলভ্য নয়। স্মৃতির বিবরণ এবং নিয়ন্ত্রণগুলি এখনও পাওয়া যায়।"],
  'pt-BR': ["Destinos acessíveis do Início","Abrir o companheiro Orb da URAI","Solo","Abrir Solo diretamente","WebGL está indisponível. Os controles acessíveis do Início continuam disponíveis.","Não foi possível carregar os recursos do Início. Os controles acessíveis continuam disponíveis.","O renderizador espacial não pôde se recuperar. Os controles acessíveis do Início continuam disponíveis.","Tentar carregar o Início novamente","Restaurando o renderizador espacial do Início.","Seu mundo privado está tomando forma","Subindo pelo céu","Descendo para o Solo","O Orb está aqui","O caminho desce","Olhe para o céu","Abrindo a constelação…","Nenhum objeto de vida corresponde a estes filtros.","Entrar no Foco","Buscar memórias, pessoas, lugares…","Estrela de memória do Foco","Estrela de memória em repouso","Escolha uma estrela no Mapa da vida para entrar no campo estelar que guarda essa memória.","Arraste para orbitar. Role ou faça o gesto de pinça para mudar a profundidade. Use W A S D ou as setas para viajar. Centralizar novamente restaura a vista de chegada. Escape retorna ao Mapa da vida.","Preparando o campo estelar de memória…","Abrindo o campo estelar de memória…","Vista espacial indisponível","A memória continua acessível pelos controles e pelos detalhes da memória.","Campo estelar de memória pronto","Campo estelar neutro","Abrindo a memória selecionada","Verificando a vista espacial…","Tentar a vista espacial novamente","Pausar memória","Continuar memória","Horizonte de memória","Abrindo o campo de memória","Uma memória está surgindo.","Escolha uma memória para entrar na Reprodução.","Escolher uma memória","Você está offline. Reconecte-se para carregar experiências que precisam da rede.","Campo estelar de memória do Foco da URAI","Início espacial vivo da URAI","Carregando","Vista espacial indisponível. Os detalhes da memória e os controles continuam acessíveis."],
  'ru': ["Доступные направления Главной","Открыть спутника URAI Orb","Земля","Открыть Землю напрямую","WebGL недоступен. Доступные элементы управления Главной остаются доступны.","Не удалось загрузить ресурсы Главной. Доступные элементы управления остаются доступны.","Пространственный рендерер не удалось восстановить. Доступные элементы управления Главной остаются доступны.","Повторить загрузку Главной","Восстановление пространственного рендерера Главной.","Ваш личный мир обретает форму","Подъём сквозь небо","Спуск к Земле","Orb здесь","Путь спускается","Посмотрите на небо","Открытие созвездия…","Ни один объект жизни не соответствует этим фильтрам.","Войти в Фокус","Поиск воспоминаний, людей, мест…","Звезда памяти Фокуса","Звезда памяти покоится","Выберите звезду на Карте жизни, чтобы войти в звёздное поле, в котором хранится это воспоминание.","Перетаскивайте для вращения. Прокручивайте или сводите пальцы для движения в глубину. Используйте W A S D или стрелки для перемещения. Возврат в центр восстанавливает вид прибытия. Escape возвращает к Карте жизни.","Подготовка звёздного поля памяти…","Открытие звёздного поля памяти…","Пространственный вид недоступен","Воспоминание остаётся доступным через элементы управления и сведения о нём.","Звёздное поле памяти готово","Нейтральное звёздное поле","Открытие выбранного воспоминания","Проверка пространственного вида…","Повторить открытие пространственного вида","Приостановить воспоминание","Продолжить воспоминание","Горизонт памяти","Открытие поля памяти","Воспоминание появляется.","Выберите воспоминание для входа в Повтор.","Выбрать воспоминание","Вы не в сети. Подключитесь снова, чтобы загрузить возможности, которым нужна сеть.","Звёздное поле памяти Фокуса URAI","Живая пространственная Главная URAI","Загрузка","Пространственный вид недоступен. Сведения о воспоминании и элементы управления остаются доступными."],
  'ur': ["ہوم کی قابلِ رسائی منزلیں","URAI Orb ساتھی کھولیں","گراؤنڈ","گراؤنڈ براہ راست کھولیں","WebGL دستیاب نہیں ہے۔ ہوم کے قابلِ رسائی کنٹرول دستیاب ہیں۔","ہوم کے وسائل لوڈ نہیں ہو سکے۔ قابلِ رسائی کنٹرول دستیاب ہیں۔","مقامی رینڈرر بحال نہیں ہو سکا۔ ہوم کے قابلِ رسائی کنٹرول دستیاب ہیں۔","ہوم لوڈ کرنے کی دوبارہ کوشش کریں","مقامی ہوم رینڈرر بحال ہو رہا ہے۔","آپ کی نجی دنیا تشکیل پا رہی ہے","آسمان میں اوپر جا رہے ہیں","گراؤنڈ کی طرف نیچے جا رہے ہیں","Orb یہاں ہے","راستہ نیچے جاتا ہے","آسمان کی طرف دیکھیں","ستاروں کا جھرمٹ کھل رہا ہے…","ان فلٹرز سے کوئی زندگی کی شے میل نہیں کھاتی۔","فوکس میں داخل ہوں","یادیں، لوگ، جگہیں تلاش کریں…","فوکس کا یادداشت ستارہ","یادداشت ستارہ آرام میں ہے","زندگی کے نقشے میں ایک ستارہ چن کر اس ستاروں والے یادداشت میدان میں جائیں جہاں وہ یاد رکھی گئی ہے۔","گرد گھومنے کے لیے کھینچیں۔ گہرائی میں حرکت کے لیے اسکرول کریں یا انگلیوں سے پنچ کریں۔ چلنے کے لیے W A S D یا تیر والے بٹن استعمال کریں۔ دوبارہ مرکز میں لانے سے آمد کا منظر بحال ہوتا ہے۔ Escape زندگی کے نقشے پر واپس لاتا ہے۔","ستاروں والا یادداشت میدان تیار ہو رہا ہے…","ستاروں والا یادداشت میدان کھل رہا ہے…","مقامی منظر دستیاب نہیں","کنٹرول اور یادداشت کی تفصیلات سے یاد اب بھی دستیاب ہے۔","ستاروں والا یادداشت میدان تیار ہے","غیر جانب دار ستاروں والا میدان","منتخب یاد کھل رہی ہے","مقامی منظر کی جانچ ہو رہی ہے…","مقامی منظر کی دوبارہ کوشش کریں","یاد روکیں","یاد جاری رکھیں","یادداشت کا افق","یادداشت میدان کھل رہا ہے","ایک یاد سامنے آ رہی ہے۔","ری پلے میں داخل ہونے کے لیے ایک یاد چنیں۔","ایک یاد چنیں","آپ آف لائن ہیں۔ نیٹ ورک کی ضرورت والے تجربات لوڈ کرنے کے لیے دوبارہ جڑیں۔","URAI فوکس کا ستاروں والا یادداشت میدان","URAI کا جیتا جاگتا مقامی ہوم","لوڈ ہو رہا ہے","مقامی منظر دستیاب نہیں۔ یادداشت کی تفصیلات اور کنٹرول اب بھی دستیاب ہیں۔"],
  'id': ["Tujuan Beranda yang dapat diakses","Buka pendamping URAI Orb","Tanah","Buka Tanah langsung","WebGL tidak tersedia. Kontrol Beranda yang dapat diakses tetap tersedia.","Aset Beranda tidak dapat dimuat. Kontrol yang dapat diakses tetap tersedia.","Perender spasial tidak dapat dipulihkan. Kontrol Beranda yang dapat diakses tetap tersedia.","Coba muat Beranda lagi","Memulihkan perender spasial Beranda.","Dunia pribadi Anda sedang terbentuk","Naik melintasi langit","Turun ke Tanah","Orb ada di sini","Jalur menurun","Lihat ke langit","Membuka konstelasi…","Tidak ada objek kehidupan yang cocok dengan filter ini.","Masuk ke Fokus","Cari kenangan, orang, tempat…","Bintang Kenangan Fokus","Bintang kenangan beristirahat","Pilih bintang di Peta Kehidupan untuk memasuki medan kenangan bintang yang menyimpan kenangan itu.","Seret untuk mengorbit. Gulir atau cubit untuk bergerak dalam kedalaman. Gunakan W A S D atau tombol panah untuk bergerak. Pusatkan kembali memulihkan tampilan kedatangan. Escape kembali ke Peta Kehidupan.","Menyiapkan medan kenangan bintang…","Membuka medan kenangan bintang…","Tampilan spasial tidak tersedia","Kenangan tetap dapat diakses melalui kontrol dan detail kenangan.","Medan kenangan bintang siap","Medan bintang netral","Membuka kenangan terpilih","Memeriksa tampilan spasial…","Coba tampilan spasial lagi","Jeda kenangan","Lanjutkan kenangan","Cakrawala kenangan","Membuka medan kenangan","Sebuah kenangan mulai terlihat.","Pilih kenangan untuk masuk ke Putar Ulang.","Pilih kenangan","Anda sedang offline. Hubungkan kembali untuk memuat pengalaman yang membutuhkan jaringan.","Medan kenangan bintang Fokus URAI","Beranda spasial hidup URAI","Memuat","Tampilan spasial tidak tersedia. Detail kenangan dan kontrol tetap dapat diakses."],
  'de': ["Barrierefreie Ziele der Startseite","URAI Orb Begleiter öffnen","Boden","Boden direkt öffnen","WebGL ist nicht verfügbar. Die barrierefreien Steuerelemente der Startseite bleiben verfügbar.","Die Ressourcen der Startseite konnten nicht geladen werden. Barrierefreie Steuerelemente bleiben verfügbar.","Die räumliche Darstellung konnte nicht wiederhergestellt werden. Barrierefreie Steuerelemente der Startseite bleiben verfügbar.","Startseite erneut laden","Räumliche Darstellung der Startseite wird wiederhergestellt.","Deine private Welt nimmt Gestalt an","Aufstieg durch den Himmel","Abstieg zum Boden","Der Orb ist hier","Der Weg führt hinab","Schau zum Himmel","Sternbild wird geöffnet…","Keine Lebensobjekte entsprechen diesen Filtern.","Fokus betreten","Erinnerungen, Personen, Orte suchen…","Fokus-Erinnerungsstern","Erinnerungsstern ruht","Wähle einen Stern auf der Lebenskarte, um das stellare Erinnerungsfeld zu betreten, in dem diese Erinnerung liegt.","Zum Umkreisen ziehen. Zum Bewegen in der Tiefe scrollen oder mit zwei Fingern zoomen. Mit W A S D oder den Pfeiltasten bewegen. Neu zentrieren stellt die Ankunftsansicht wieder her. Escape führt zurück zur Lebenskarte.","Stellares Erinnerungsfeld wird vorbereitet…","Stellares Erinnerungsfeld wird geöffnet…","Räumliche Ansicht nicht verfügbar","Die Erinnerung bleibt über Steuerelemente und Erinnerungsdetails zugänglich.","Stellares Erinnerungsfeld bereit","Neutrales Sternenfeld","Ausgewählte Erinnerung wird geöffnet","Räumliche Ansicht wird geprüft…","Räumliche Ansicht erneut versuchen","Erinnerung pausieren","Erinnerung fortsetzen","Erinnerungshorizont","Erinnerungsfeld wird geöffnet","Eine Erinnerung kommt in Sicht.","Wähle eine Erinnerung, um die Wiedergabe zu öffnen.","Erinnerung auswählen","Du bist offline. Verbinde dich erneut, um Erlebnisse zu laden, die das Netzwerk benötigen.","Stellares Fokus-Erinnerungsfeld von URAI","Lebendige räumliche Startseite von URAI","Wird geladen","Räumliche Ansicht nicht verfügbar. Erinnerungsdetails und Steuerelemente bleiben zugänglich."],
  'ja': ["利用しやすいホームの移動先","URAI Orb コンパニオンを開く","グラウンド","グラウンドを直接開く","WebGL は利用できません。ホームのアクセシブルな操作は引き続き利用できます。","ホームのアセットを読み込めませんでした。アクセシブルな操作は引き続き利用できます。","空間レンダラーを復元できませんでした。ホームのアクセシブルな操作は引き続き利用できます。","ホームの読み込みを再試行","空間ホームレンダラーを復元しています。","あなたのプライベートな世界が形になっています","空を通って上昇中","グラウンドへ下降中","Orb はここにいます","道は下へ続きます","空を見上げてください","星座を開いています…","このフィルターに一致するライフオブジェクトはありません。","フォーカスに入る","記憶、人、場所を検索…","フォーカス記憶星","記憶星は休息中","ライフマップで星を選び、その記憶を包む恒星の記憶フィールドに入ってください。","ドラッグして周囲を見ます。スクロールまたはピンチで奥行き方向に移動します。W A S D または矢印キーで移動します。中央に戻すと到着時の視点が復元されます。Escape でライフマップに戻ります。","恒星の記憶フィールドを準備しています…","恒星の記憶フィールドを開いています…","空間ビューは利用できません","操作と記憶の詳細から引き続き記憶にアクセスできます。","恒星の記憶フィールドの準備ができました","中立の恒星フィールド","選択した記憶を開いています","空間ビューを確認しています…","空間ビューを再試行","記憶を一時停止","記憶を続ける","記憶の地平線","記憶フィールドを開いています","記憶が見えてきます。","リプレイに入る記憶を選んでください。","記憶を選ぶ","オフラインです。ネットワークが必要な体験を読み込むには再接続してください。","URAI フォーカス恒星記憶フィールド","URAI の生きた空間ホーム","読み込み中","空間ビューは利用できません。記憶の詳細と操作は引き続き利用できます。"],
  'sw': ["Maeneo ya Mwanzo yanayofikika","Fungua mwenzi URAI Orb","Ardhi","Fungua Ardhi moja kwa moja","WebGL haipatikani. Vidhibiti vinavyofikika vya Mwanzo bado vinapatikana.","Rasilimali za Mwanzo hazikuweza kupakiwa. Vidhibiti vinavyofikika bado vinapatikana.","Kionyeshi cha anga hakikuweza kurejeshwa. Vidhibiti vinavyofikika vya Mwanzo bado vinapatikana.","Jaribu kupakia Mwanzo tena","Inarejesha kionyeshi cha anga cha Mwanzo.","Ulimwengu wako binafsi unachukua umbo","Kupanda kupitia anga","Kushuka kwenda Ardhi","Orb iko hapa","Njia inashuka","Tazama angani","Inafungua kundi la nyota…","Hakuna vitu vya maisha vinavyolingana na vichujio hivi.","Ingia kwenye Lenga","Tafuta kumbukumbu, watu, maeneo…","Nyota ya Kumbukumbu ya Lenga","Nyota ya kumbukumbu inapumzika","Chagua nyota kwenye Ramani ya Maisha ili kuingia katika uga wa kumbukumbu za nyota unaoshikilia kumbukumbu hiyo.","Buruta kuzunguka. Sogeza au bana kwa vidole kubadili kina. Tumia W A S D au vitufe vya mishale kusafiri. Rudisha katikati hurejesha mwonekano wa kuwasili. Escape hurudisha kwenye Ramani ya Maisha.","Inaandaa uga wa kumbukumbu za nyota…","Inafungua uga wa kumbukumbu za nyota…","Mwonekano wa anga haupatikani","Kumbukumbu bado inafikika kupitia vidhibiti na maelezo yake.","Uga wa kumbukumbu za nyota uko tayari","Uga wa nyota usioegemea upande","Inafungua kumbukumbu iliyochaguliwa","Inakagua mwonekano wa anga…","Jaribu mwonekano wa anga tena","Sitisha kumbukumbu","Endelea na kumbukumbu","Upeo wa kumbukumbu","Inafungua uga wa kumbukumbu","Kumbukumbu inaanza kuonekana.","Chagua kumbukumbu ili kuingia kwenye Cheza Tena.","Chagua kumbukumbu","Uko nje ya mtandao. Unganisha tena ili kupakia hali zinazohitaji mtandao.","Uga wa kumbukumbu za nyota wa Lenga wa URAI","Mwanzo wa anga hai wa URAI","Inapakia","Mwonekano wa anga haupatikani. Maelezo ya kumbukumbu na vidhibiti bado vinafikika."],
  'tr': ["Erişilebilir Ana Sayfa hedefleri","URAI Orb yoldaşını aç","Zemin","Zemini doğrudan aç","WebGL kullanılamıyor. Ana Sayfanın erişilebilir kontrolleri kullanılabilir durumda.","Ana Sayfa varlıkları yüklenemedi. Erişilebilir kontroller kullanılabilir durumda.","Mekânsal görüntüleyici geri yüklenemedi. Ana Sayfanın erişilebilir kontrolleri kullanılabilir durumda.","Ana Sayfayı yüklemeyi yeniden dene","Mekânsal Ana Sayfa görüntüleyicisi geri yükleniyor.","Özel dünyanız şekilleniyor","Gökyüzünde yükseliyor","Zemine doğru iniyor","Orb burada","Yol aşağı iniyor","Gökyüzüne bakın","Takımyıldız açılıyor…","Bu filtrelerle eşleşen yaşam nesnesi yok.","Odağa gir","Anıları, kişileri, yerleri ara…","Odak Anı Yıldızı","Anı yıldızı dinleniyor","Yaşam Haritasında bir yıldız seçerek o anıyı barındıran yıldızsal anı alanına girin.","Yörüngede dönmek için sürükleyin. Derinlikte hareket etmek için kaydırın veya kıstırın. Hareket için W A S D ya da ok tuşlarını kullanın. Yeniden ortala varış görünümünü geri getirir. Escape Yaşam Haritasına döndürür.","Yıldızsal anı alanı hazırlanıyor…","Yıldızsal anı alanı açılıyor…","Mekânsal görünüm kullanılamıyor","Anıya kontroller ve anı ayrıntıları üzerinden erişilebilir.","Yıldızsal anı alanı hazır","Nötr yıldızsal alan","Seçilen anı açılıyor","Mekânsal görünüm kontrol ediliyor…","Mekânsal görünümü yeniden dene","Anıyı duraklat","Anıya devam et","Anı ufku","Anı alanı açılıyor","Bir anı görünmeye başlıyor.","Tekrar Oynata girmek için bir anı seçin.","Bir anı seç","Çevrimdışısınız. Ağ gerektiren deneyimleri yüklemek için yeniden bağlanın.","URAI Odak yıldızsal anı alanı","URAI canlı mekânsal Ana Sayfa","Yükleniyor","Mekânsal görünüm kullanılamıyor. Anı ayrıntıları ve kontroller erişilebilir durumda."],
  'vi': ["Các điểm đến Trang chủ có thể tiếp cận","Mở người bạn đồng hành URAI Orb","Mặt đất","Mở Mặt đất trực tiếp","WebGL không khả dụng. Các điều khiển hỗ trợ tiếp cận của Trang chủ vẫn khả dụng.","Không thể tải tài nguyên Trang chủ. Các điều khiển hỗ trợ tiếp cận vẫn khả dụng.","Không thể khôi phục trình kết xuất không gian. Các điều khiển hỗ trợ tiếp cận của Trang chủ vẫn khả dụng.","Thử tải lại Trang chủ","Đang khôi phục trình kết xuất không gian Trang chủ.","Thế giới riêng tư của bạn đang thành hình","Đang bay lên qua bầu trời","Đang đi xuống Mặt đất","Orb ở đây","Con đường đi xuống","Hãy nhìn lên bầu trời","Đang mở chòm sao…","Không có đối tượng cuộc sống nào khớp với các bộ lọc này.","Vào Tập trung","Tìm ký ức, người, địa điểm…","Ngôi sao Ký ức Tập trung","Ngôi sao ký ức đang nghỉ","Chọn một ngôi sao trong Bản đồ Cuộc sống để vào trường ký ức sao lưu giữ ký ức đó.","Kéo để xoay quanh. Cuộn hoặc chụm ngón tay để di chuyển theo chiều sâu. Dùng W A S D hoặc phím mũi tên để di chuyển. Đưa về trung tâm khôi phục góc nhìn khi đến. Escape quay về Bản đồ Cuộc sống.","Đang chuẩn bị trường ký ức sao…","Đang mở trường ký ức sao…","Chế độ xem không gian không khả dụng","Ký ức vẫn có thể truy cập qua các điều khiển và chi tiết ký ức.","Trường ký ức sao đã sẵn sàng","Trường sao trung tính","Đang mở ký ức đã chọn","Đang kiểm tra chế độ xem không gian…","Thử lại chế độ xem không gian","Tạm dừng ký ức","Tiếp tục ký ức","Chân trời ký ức","Đang mở trường ký ức","Một ký ức đang hiện ra.","Chọn một ký ức để vào Phát lại.","Chọn một ký ức","Bạn đang ngoại tuyến. Kết nối lại để tải những trải nghiệm cần mạng.","Trường ký ức sao Tập trung URAI","Trang chủ không gian sống động URAI","Đang tải","Chế độ xem không gian không khả dụng. Chi tiết ký ức và các điều khiển vẫn có thể truy cập."],
  'fil': ["Mga accessible na destinasyon sa Home","Buksan ang kasamang URAI Orb","Lupa","Direktang buksan ang Lupa","Hindi available ang WebGL. Available pa rin ang mga accessible na kontrol sa Home.","Hindi ma-load ang mga asset sa Home. Available pa rin ang mga accessible na kontrol.","Hindi naibalik ang spatial renderer. Available pa rin ang mga accessible na kontrol sa Home.","Subukang i-load muli ang Home","Ibinabalik ang spatial renderer ng Home.","Nabubuo ang iyong pribadong mundo","Umaakyat sa kalangitan","Bumababa sa Lupa","Narito ang Orb","Pababa ang landas","Tumingin sa langit","Binubuksan ang konstelasyon…","Walang bagay sa buhay na tumutugma sa mga filter na ito.","Pumasok sa Pokus","Maghanap ng mga alaala, tao, lugar…","Bituin ng Alaala sa Pokus","Nagpapahinga ang bituin ng alaala","Pumili ng bituin sa Mapa ng Buhay upang pumasok sa larangan ng alaala ng mga bituin na kinalalagyan ng alaalang iyon.","I-drag upang umikot. Mag-scroll o mag-pinch upang gumalaw sa lalim. Gamitin ang W A S D o mga arrow key upang lumipat. Igitna muli ibinabalik ang tanaw sa pagdating. Ibinabalik ng Escape ang Mapa ng Buhay.","Inihahanda ang larangan ng alaala ng mga bituin…","Binubuksan ang larangan ng alaala ng mga bituin…","Hindi available ang spatial na tanaw","Maaari pa ring ma-access ang alaala sa mga kontrol at detalye ng alaala.","Handa ang larangan ng alaala ng mga bituin","Neutral na larangan ng mga bituin","Binubuksan ang napiling alaala","Sinusuri ang spatial na tanaw…","Subukan muli ang spatial na tanaw","I-pause ang alaala","Ipagpatuloy ang alaala","Abot-tanaw ng alaala","Binubuksan ang larangan ng alaala","Lumilitaw ang isang alaala.","Pumili ng alaala upang pumasok sa Replay.","Pumili ng alaala","Offline ka. Kumonekta muli upang i-load ang mga karanasang nangangailangan ng network.","Larangan ng alaala ng mga bituin sa Pokus ng URAI","Buhay na spatial Home ng URAI","Naglo-load","Hindi available ang spatial na tanaw. Maa-access pa rin ang mga detalye at kontrol ng alaala."],
  'ko': ["접근 가능한 홈 목적지","URAI Orb 동반자 열기","그라운드","그라운드 바로 열기","WebGL을 사용할 수 없습니다. 홈의 접근성 제어는 계속 사용할 수 있습니다.","홈 자산을 불러오지 못했습니다. 접근성 제어는 계속 사용할 수 있습니다.","공간 렌더러를 복원하지 못했습니다. 홈의 접근성 제어는 계속 사용할 수 있습니다.","홈 불러오기 다시 시도","공간 홈 렌더러를 복원하고 있습니다.","나만의 세계가 만들어지고 있습니다","하늘을 통해 상승 중","그라운드로 하강 중","Orb가 여기 있습니다","길이 아래로 이어집니다","하늘을 바라보세요","별자리를 여는 중…","이 필터와 일치하는 삶의 객체가 없습니다.","포커스 진입","기억, 사람, 장소 검색…","포커스 기억 별","기억 별이 쉬고 있습니다","라이프 맵에서 별을 선택하여 그 기억을 담고 있는 별의 기억 공간으로 들어가세요.","드래그하여 둘러보세요. 스크롤하거나 손가락을 오므려 깊이를 이동하세요. W A S D 또는 방향키로 이동하세요. 중앙으로 복귀하면 도착 시점의 화면으로 돌아갑니다. Escape는 라이프 맵으로 돌아갑니다.","별의 기억 공간을 준비하는 중…","별의 기억 공간을 여는 중…","공간 화면을 사용할 수 없음","제어와 기억 상세 정보를 통해 기억에 계속 접근할 수 있습니다.","별의 기억 공간 준비 완료","중립적인 별 공간","선택한 기억을 여는 중","공간 화면을 확인하는 중…","공간 화면 다시 시도","기억 일시 정지","기억 계속 보기","기억의 지평선","기억 공간을 여는 중","기억이 모습을 드러냅니다.","다시 재생으로 들어갈 기억을 선택하세요.","기억 선택","오프라인 상태입니다. 네트워크가 필요한 경험을 불러오려면 다시 연결하세요.","URAI 포커스 별의 기억 공간","URAI 살아 있는 공간 홈","불러오는 중","공간 화면을 사용할 수 없습니다. 기억 상세 정보와 제어는 계속 접근할 수 있습니다."],
  'it': ["Destinazioni accessibili di Home","Apri il compagno Orb di URAI","Suolo","Apri direttamente il Suolo","WebGL non è disponibile. I controlli accessibili di Home restano disponibili.","Impossibile caricare le risorse di Home. I controlli accessibili restano disponibili.","Il renderer spaziale non è stato ripristinato. I controlli accessibili di Home restano disponibili.","Riprova a caricare Home","Ripristino del renderer spaziale di Home.","Il tuo mondo privato sta prendendo forma","Salita attraverso il cielo","Discesa verso il Suolo","L’Orb è qui","Il sentiero scende","Guarda il cielo","Apertura della costellazione…","Nessun oggetto di vita corrisponde a questi filtri.","Entra nel Focus","Cerca ricordi, persone, luoghi…","Stella della memoria del Focus","Stella della memoria a riposo","Scegli una stella nella Mappa della vita per entrare nel campo stellare che custodisce quel ricordo.","Trascina per orbitare. Scorri o pizzica per muoverti in profondità. Usa W A S D o le frecce per spostarti. Ricentra ripristina la vista di arrivo. Escape torna alla Mappa della vita.","Preparazione del campo stellare della memoria…","Apertura del campo stellare della memoria…","Vista spaziale non disponibile","Il ricordo resta accessibile attraverso i controlli e i dettagli della memoria.","Campo stellare della memoria pronto","Campo stellare neutro","Apertura del ricordo selezionato","Verifica della vista spaziale…","Riprova la vista spaziale","Metti il ricordo in pausa","Continua il ricordo","Orizzonte della memoria","Apertura del campo della memoria","Un ricordo sta apparendo.","Scegli un ricordo per entrare nella Riproduzione.","Scegli un ricordo","Sei offline. Riconnettiti per caricare le esperienze che richiedono la rete.","Campo stellare della memoria del Focus di URAI","Home spaziale vivente di URAI","Caricamento","Vista spaziale non disponibile. I dettagli della memoria e i controlli restano accessibili."],
  'fa': ["مقصدهای دسترس‌پذیر خانه","باز کردن همراه URAI Orb","زمین","باز کردن مستقیم زمین","WebGL در دسترس نیست. کنترل‌های دسترس‌پذیر خانه همچنان در دسترس هستند.","دارایی‌های خانه بارگذاری نشدند. کنترل‌های دسترس‌پذیر همچنان در دسترس هستند.","نمایشگر فضایی بازیابی نشد. کنترل‌های دسترس‌پذیر خانه همچنان در دسترس هستند.","تلاش دوباره برای بارگذاری خانه","در حال بازیابی نمایشگر فضایی خانه.","دنیای خصوصی شما در حال شکل‌گیری است","صعود در آسمان","فرود به زمین","Orb اینجاست","مسیر به پایین می‌رود","به آسمان نگاه کنید","در حال باز کردن صورت فلکی…","هیچ مورد زندگی با این فیلترها مطابقت ندارد.","ورود به تمرکز","جستجوی خاطرات، افراد، مکان‌ها…","ستاره خاطره تمرکز","ستاره خاطره در آرامش است","ستاره‌ای در نقشه زندگی انتخاب کنید تا وارد میدان ستاره‌ای شوید که آن خاطره را در خود نگه می‌دارد.","برای چرخش بکشید. برای حرکت در عمق پیمایش کنید یا با دو انگشت نزدیک کنید. برای حرکت از W A S D یا کلیدهای جهت استفاده کنید. بازگرداندن به مرکز نمای ورود را بازیابی می‌کند. Escape به نقشه زندگی بازمی‌گردد.","در حال آماده‌سازی میدان ستاره‌ای خاطره…","در حال باز کردن میدان ستاره‌ای خاطره…","نمای فضایی در دسترس نیست","خاطره همچنان از طریق کنترل‌ها و جزئیات خاطره در دسترس است.","میدان ستاره‌ای خاطره آماده است","میدان ستاره‌ای خنثی","در حال باز کردن خاطره انتخاب‌شده","در حال بررسی نمای فضایی…","تلاش دوباره برای نمای فضایی","توقف موقت خاطره","ادامه خاطره","افق خاطره","در حال باز کردن میدان خاطره","خاطره‌ای در حال نمایان شدن است.","خاطره‌ای انتخاب کنید تا وارد بازپخش شوید.","انتخاب خاطره","آفلاین هستید. برای بارگذاری تجربه‌های نیازمند شبکه دوباره متصل شوید.","میدان ستاره‌ای خاطره تمرکز URAI","خانه فضایی زنده URAI","در حال بارگذاری","نمای فضایی در دسترس نیست. جزئیات خاطره و کنترل‌ها همچنان در دسترس هستند."],
} satisfies Record<UraiLaunchLocale, readonly string[]>

export const URAI_JOURNEY_CATALOGS = Object.fromEntries(Object.entries(rows).map(([locale, row]) => {
  if (row.length !== ids.length || row.some(value => !value.trim())) throw new Error(`JOURNEY_CATALOG_LENGTH:${locale}`)
  return [locale, Object.fromEntries(ids.map((id, index) => [id, row[index]]))]
})) as Record<UraiLaunchLocale, Record<UraiJourneyMessageId, string>>
